### ISSUE TITLE
Whatsapp - Post message and image

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#100]
The idea is to be able to post a message and attach an image to a WhatsApp individual contact.

It seems like WhatsApp have opened its API recently. Here is the doc found: https://developers.facebook.com/docs/whatsapp/cloud-api/get-started

The idea is to be able to fit the API request to send a message and an image into the Naas IMO framework (check [README](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository-) )

Input: 
PHONE_NUMBER = "" 
MESSAGE = ""

Model: 
function to send a message to a phone

Output: 
"Message has been sent'

**Comment by jravenel** [comment]
First try but not working inside naas:
https://public.naas.ai/c2FuamF5LTJFcy00MGJyaWRnZS0yRGdsb2JhbC0yRWNvbQ==/asset/fcfd89bf7b37f5a850d671ee03e6f107577927a9965c0521b81a76e72f49

**Comment by jravenel** [comment]
https://github.com/jupyter-naas/awesome-notebooks/issues/1266#issue-1412381792


@muhtalhakhan following our conversation, I'm referring to your comment here and will close the other issue. 
Do you want to work on this with me next week and probably make a Youtube video about it that we can post on socials?

I understood that we can start with the dev account and work from there, then once we have a better understanding I will do the workflow as an end user paying for the service. 

What do you think?

**Comment by muhtalhakhan** [comment]
Hey J,

I would love to work with you about this for sure. Do let me know when we
can talk about it.

Sure, we can at least start over and get an endpoint then we can make it
available for others through our template.

Regards
Muhammad Talha Khan

**Comment by jravenel** [comment]
@muhtalhakhan we can work in here if you don't mind. Async is the key to making good progress fast.
Can you draft a first PR? I created the branch

**Comment by muhtalhakhan** [comment]
Sure, we are good to go. Give me a day or two as currently I got ill.
Rightnow, resting and doing nothing unless taking meds and eateries only.

Will look into it on Thursday or before that.

**Comment by jravenel** [comment]
Now that HF is in prod :) sky is the limit @muhtalhakhan :)

**Comment by muhtalhakhan** [comment]
HF = half or have fun here?

I will check it today and let you know. \o/

**Comment by jravenel** [comment]
HF: HuggingFace :)

**Comment by muhtalhakhan** [comment]
Btw when will you be free so that we can have a little video recording to be posted over socials as discussed.

**Comment by jravenel** [comment]
Hello @muhtalhakhan, can you please update the links shared today during our call and give me the instructions? 
I think I have to open meta account but not sure about the rest.
Thanks

**Comment by muhtalhakhan** [comment]
Hey @jravenel,

Yeah mentioning the links below:

1. [Facebook Developer](https://developers.facebook.com/docs/whatsapp/cloud-api/get-started)
2. [WhatsApp Business](https://www.facebook.com/business/help/2087193751603668?id=2129163877102343)
3. [Info related to pricing](https://www.sendinblue.com/blog/how-whatsapp-business-api-pricing-works/)
4. [WhatsApp Business Platform - Complete resources](https://business.whatsapp.com/developers/developer-hub)
5. [Meta Business Suite](https://business.facebook.com/)


Other way around it can be like that:

first up we need to "Set up Developer Assets and Platform Access" for setting this up we are required to register ourself as a "Meta Dev", "Enable 2FA", and create a "meta app" by selecting "Business" as type afterwards you are required to create a "Wapp Business Acc", and add a number to it that will redirect to "Getting Started" page after verification.

Ref: https://developers.facebook.com/docs/whatsapp/cloud-api/get-started

Well, this API costs according to session and a session here is a conversation of 24 hours between a contact and your business.

Ref: https://www.sendinblue.com/blog/how-whatsapp-business-api-pricing-works/

The complete resources -> https://business.whatsapp.com/developers/developer-hub

For businesses who want to get started with the WhatsApp Business Platform, please fill out the form below to talk to sales -> https://business.whatsapp.com/learn-more

**Comment by jravenel** [comment]
I think its find, Naas is on linux, do you see any issues @Dr0p42 ?

**Comment by muhtalhakhan** [comment]
Hey @jravenel , 
@Dr0p42 have not replied to your comment above!

Looking forward for all the requisites to be completed.

**Comment by Dr0p42** [comment]
Hello @muhtalhakhan, Docker + Linux is fine for us 👍

**Comment by muhtalhakhan** [comment]
Hey @Dr0p42 thats great!

@jravenel have you done with the requisites of it?

**Comment by omerkork** [comment]
selam benim arkadasim whatsapp numarasi whatsapp tarafindan surekli blog ve ya engelleniyor ve bunu icin whatsapp tarafinda whatsapp destek yardim etmiyor kendisi ajans eskort is alaninda ve surekli musterilerine resim mesaj gonderiyor ve whatsapp arkadasim numarasini blog ve engel koyuyor ve whatsap girisini yasakliyor bunu icin sizden tek ricam lutfen yardiminiz ve desteyinize ihtiyacim var gerekiyorsa maddi durumla ilgili hic bir sikinti yok sadece arkadasim is numarasini geri getirmek ve whatsapp tarafinda bir daha ne blok nedeki engell koyulmasin lutfen sizden cok rica ederim bu konuda ciddi bir destekinize ihtiyacim var

**Comment by muhtalhakhan** [comment]
> selam benim arkadasim whatsapp numarasi whatsapp tarafindan surekli blog ve ya engelleniyor ve bunu icin whatsapp tarafinda whatsapp destek yardim etmiyor kendisi ajans eskort is alaninda ve surekli musterilerine resim mesaj gonderiyor ve whatsapp arkadasim numarasini blog ve engel koyuyor ve whatsap girisini yasakliyor bunu icin sizden tek ricam lutfen yardiminiz ve desteyinize ihtiyacim var gerekiyorsa maddi durumla ilgili hic bir sikinti yok sadece arkadasim is numarasini geri getirmek ve whatsapp tarafinda bir daha ne blok nedeki engell koyulmasin lutfen sizden cok rica ederim bu konuda ciddi bir destekinize ihtiyacim var

Translation: hi my friend whatsapp number is constantly being blocked or blocked by whatsapp and whatsapp support does not help for this, he is in the agency escort work area and constantly sends a picture message to his customers and whatsapp my friend's number on the blog and blocks and forbids whatsapp login, my only request from you is please I need your help and support, if necessary, there is no problem about the financial situation, just to bring back my friend's work number and not to be blocked or blocked on whatsapp again, please, I ask you very much, I need your serious support in this matter

**Comment by omerkork** [comment]
hi my friend whatsapp number is constantly being blocked or blocked by whatsapp and whatsapp support does not help for this, he is in the agency escort area and constantly sends a picture message to his customers and whatsapp my friend's number on the blog and blocks and forbids whatsapp login, my only request from you is please help and I need your support, if necessary, there is no problem about the financial situation, just my friend, do not bring back his work number, please do not be blocked or blocked on whatsapp again, please, please, I need your serious support in this matter

**Comment by jravenel** [comment]
Hi @omerkork @muhtalhakhan, I will resume work on this on the next iteration so I assigned it to myself.

**Comment by jravenel** [comment]
Putting it back to Backlog

**Comment by FlorentLvr** [comment]
Closed to be reopened for hacktoberfest 2023
