### ISSUE TITLE
Youtube - Extract transcript from video ID

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#101]
Info : 
- https://www.youtube.com/watch?v=bzyE4c1obWM&feature=emb_logo
- https://towardsdatascience.com/extracting-speech-from-video-using-python-f0ec7e312d38

TBD

**Comment by tparente-ui** [comment]
Hi @jravenel, can you provide the information you want in the naas notebook framework please ?

**Comment by jravenel** [comment]
Hey @tparente-ui, here it is : 

# Youtube - Extract transcript from video ID

## Input 
pip install youtube_transcript_api

video_id = "9IauaPnBVd4"
file_name = "Elon Musk controversial speech"

## Model
### Extract the transcript in JSON
### Parse JSON in text string
### Count the number of words in the paragraph
### Add punctionation

## Output 
### Save to txt file

**Comment by jravenel** [comment]
Access : https://github.com/jupyter-naas/awesome-notebooks/tree/master/Youtube
