### ISSUE TITLE
Plotly - Create Barline chart

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1042]
**Describe the problem you are facing**
As a business user, I want to see a graph with 2 y-axis 
- one is a line with a trend (1000 → 100000)
- one is a bar with variation  (100 → x)
This will show the evolution and variation of sales.

**Describe the solution you'd like**

- Input 
setup data frame with one column with DATE, VALUE, VAR
- Model 
create barline chart from plotly library
- Output
generate PNG and HTML files via URL link.

**Comment by FlorentLvr** [comment]
@jravenel, Hi I would start working on this issue. Is it cool for you ?
