### ISSUE TITLE
Stop inviting me to jupyter-naas org

### ISSUE THREAD

**Issue by jk** [jupyter-naas/awesome-notebooks#1078]
@FlorentLvr Stop spaming me with invitations to jupyter-naas org every other week. I will not join even if you send more invitations 😠 

<img width="277" alt="2022-06-10 at 09 06 14@2x" src="https://user-images.githubusercontent.com/40043/173009764-ea76b78c-5db8-444e-a8bc-c5a2718ead37.png">

**Comment by FlorentLvr** [comment]
@jk , sorry for that, it's done now! 🙏 
It seems someone enter your GitHub account in our contributor's program.
I removed it.
Have a good day
