### ISSUE TITLE
Naas - Download Content Engine

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1098]
Create a content engine that will aggregate data from social media platforms into a Notion page.

**Comment by jravenel** [comment]
This will hopefully we can start user testing.

**Comment by FlorentLvr** [comment]
@jravenel , the notebook is ready to review. It should clone or pull the naas content engine on your naas. You can test the process with LinkedIn and YouTube. Could you please have a look?

**Comment by FlorentLvr** [comment]
@jravenel, the template is now only doing the installation of the project on your naas. Could you please check if it's good for you?
