### ISSUE TITLE
LinkedIn - Get posts from profile

### ISSUE THREAD

**Issue by QuentinKlebaur** [jupyter-naas/awesome-notebooks#110]
Get all posts of a user by passing his profile url/urn

- rename function to 
df_posts = linkedin.connect(LI_AT, JSESSIONID).profile.get_posts_stats(PROFILE_URL)
- remove line without information
- rename column DATE to TIMEDELTA
- create column DATE_APPROX = now - timedelta() in format %Y-%m-%d
- sort by DATE_APPROX (descending)

**Comment by jravenel** [comment]
Done but not closed.
