### ISSUE TITLE
LinkedIn - Send follower demographics to a google sheet

### ISSUE THREAD

**Issue by Asif1310** [jupyter-naas/awesome-notebooks#1108]
**Describe the problem you are facing**

I would like to be able to perform a demographic analysis of my followers which helps me optimize my content to their needs and interests.

**Describe the solution you'd like**
For each follower, I would need the following data:
Their country
Name of the company they are working at
The industry they are associated with

- Input: LinkedIn cookies 
- Model: Fetches the profile URL for each follower and gets their profile and job details
- Output: A data frame with columns - Profile_URL, Country, Industry, and Company name 

**Additional context**

**Comment by FlorentLvr** [comment]
Hi @Asif1310 ! Just saw your post on LinkedIn about it! Glad you can share it with us :)
