### ISSUE TITLE
LinkedIn - Send invitations to post commenters template is sending invitations even to the profiles already connected.

### ISSUE THREAD

**Issue by Asif1310** [jupyter-naas/awesome-notebooks#1114]
**Describe the bug**
.Send invitations to post commenters template of LinkedIn is sending invitations to all the profiles that commented, even if those profiles are already connected or if it is the user's own profile.

**To Reproduce**
1. Input the Li cookies and post URL, and run the template
2. Go to 'My network' on LinkedIn.
3. Click on '.Manage'
4. You could see that the connections and the user are sent an invitation to connect.

**Expected behavior**
This template should send invitations only to the profiles not yet connected.

**Screenshots**
![image](https://user-images.githubusercontent.com/96224247/178095923-a4276649-dcd5-4160-8530-fa68e2a935df.png)

**Additional context**
Profile URL list needs to be filtered to remove own profile and connections

**Comment by FlorentLvr** [comment]
@Asif1310 , TY to let us about this issue. 
I noticed it as well and the only solution is to make sure you send invitations to people not in your connections already. To do that you have 2 options:
 - If you want to check by profile, you can use linkedin.profile.get_network(). It will return a dataframe with the distance and then you create a condition to send or not
- The other option will be to get your connections and ensure the people who commented on your post are not already in your connections.

Let me know if it's not clear enough!
