### ISSUE TITLE
Create dags(network) graph from GitHub Repo or local folder

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1120]
https://wimyedema.medium.com/drawing-dags-5cadcb452115
The idea is to provide like DBT a network graph where we see all the dependencies

https://wimyedema.medium.com/drawing-dags-5cadcb452115

This will enable better documentation and transparency over what's going on in a data product.

**Comment by cholu6768** [comment]
This is the one I would like to collaborate in but from which repo do you need help with?

**Comment by jravenel** [comment]
Hey @cholu6768 I'm pushing this to ready as discussed, we need to make sure this is inspired by the current template: https://github.com/jupyter-naas/awesome-notebooks/issues/1125 

and take as input a folder where the function is going to look for dependencies and generate the network graph.
