### ISSUE TITLE
Snowflake - Demo drivers in a template

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1122]
Following the work done on Snowflake by Mateus, we need to showcase it and create content via a template.

Ref: https://github.com/jupyter-naas/drivers/issues/274

**Comment by jravenel** [comment]
@mckraqs can we work on this together? I would like too understand and document it in docs.naas.ai 

@chicken-biryani will help me out as well.

**Comment by mckraqs** [comment]
Sure, I can take care of it in the following days. Do you need any specific use case, or should it be just overall step-by-step guide, e.g., similar to Notion notebooks?

**Comment by jravenel** [comment]
We can make it more specific during a quick scoping call if you want @mckraqs I sent you link in private

**Comment by jravenel** [comment]
We just talked about this during the product roadmap today @mckraqs, let's build this use case together with 2 templates: 
- one to send data to snowflake 
- one to get data from snowflake and use naas notification to update the end user.

**Comment by mckraqs** [comment]
I revamped Snowflake directory a little - added 2 datasets (`csv` and `json` formats) and 4 new Jupyter templates.

So far I focused on basic usage and data ingestion from local/cloud. Please let me know if something is unclear @jravenel so we can schedule a call and walk through the issues.

In terms of the second template you mentioned (naas notifications) - what do you think about moving it to another issue as it involves other naas features @jravenel ? Here I thought that our main task is to show how to ingest data to Snowflake and how to query it.
