### ISSUE TITLE
LinkedIn - Get posts stats from post

### ISSUE THREAD

**Issue by QuentinKlebaur** [jupyter-naas/awesome-notebooks#113]
Get the informations of a post by passing its url/urn

Rename function to linkedin.connect(LI_AT, JSESSIONID).post.get_stats(url)

Not working @QuentinKlebaur => 
![image](https://user-images.githubusercontent.com/48032461/122883243-49d39180-d33d-11eb-9c5b-15fe707cf3a8.png)

**Comment by jravenel** [comment]
Done but not closed.
