### ISSUE TITLE
LinkedIn - Get conversations from message

### ISSUE THREAD

**Issue by QuentinKlebaur** [jupyter-naas/awesome-notebooks#114]
Get all opened conversations 

- decode LAST_ACTIVITY in format = "%Y-%m-%d %H:%M:%S"
- get last message LAST_MESSAGE =>  'eventContent': {'$type': 'com.linkedin.voyager.messaging.event.MessageEvent',
                  'attributedBody': {'$type': 'com.linkedin.pemberly.text.AttributedText',
                                     'text': 'Salut'},
                                     
 Fix isssue with Valentin credentials

**Comment by FlorentLvr** [comment]
@QuentinKlebaur , 

![image](https://user-images.githubusercontent.com/48032461/126291400-0b842b39-bbbc-4538-a0e7-8112ed7cafbf.png)

**Comment by jravenel** [comment]
Done but not closed.
