### ISSUE TITLE
Dash - Deploy add to production using (Knative)

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1157]
INPUT:
Notebook path
Dependencies
Target URL

MODEL:
Deploy app

OUTPUT:
Target URL

**Comment by jravenel** [comment]
After discussion with @Dr0p42, this template is a way to show how a naas_drivers.dash.deploy works.
Here is the target formula: 

`naas_drivers.dash.deploy(path, dependencies, name, requirements, users)`

`path` is the path to the notebook file hosting the code of the dashboard 

`dependencies` are the list of files required by the notebook to run the dashboard

`name` is the target value showed in the deployed URL  followed by .live.naas.ai (eg. https://dashboard-linkedin.live.naas.ai)

`requirements` are the list of python packages to be installed 
```
    requirements=[
        "pandas==1.2.3",
        "plotly==2.3.4",
        "pydash",]
```

`users` are the list of users and passwords that will be allow to access the dashboard
```
    users=[
        "jeremy@naas.ai:12345",
        "florent@naas.ai:12345",
        "maxime@naas.ai:12345",],   
```

**Comment by jravenel** [comment]
@FlorentLvr as discussed, we can close this by creating a template that will prepare the instructions to be runned in the backend (manually so far by core team). 

List of items: 
- endpoint 
- file to run 
- repo to clone
