### ISSUE TITLE
Vizzu - Create interactive story

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1160]
Use https://vizzuhq.github.io/ipyvizzu-story/examples/demo/ipyvizzu-story_example.html

to create an awesome-notebooks template.
Following discussion with [Peter Vidos](https://www.linkedin.com/in/ACoAAALjHh0Bwvr-fukGkP_zEzamaCtZ3EhzSLE/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base%3BOvyXiyV0TICpZdTWUM0AYQ%3D%3D) on LinkedIn.

Peter mentioned we can get review from the tech team: 
@simzer @veghdev

**Comment by jravenel** [comment]
@Dr0p42 it seems I cannot install because of pip version issues.
Should I open a PR to upgrade pip on naas? It seems I cannot do that from my machine
<img width="1189" alt="Screenshot 2022-08-30 at 12 50 31" src="https://user-images.githubusercontent.com/21052349/187418347-9fca74f6-8240-4800-9008-380467a5b9f0.png">

**Comment by veghdev** [comment]
@jravenel Hi, please use `!pip install ipyvizzu-story`, for more info, check our installation [guide](https://vizzuhq.github.io/ipyvizzu-story/docs/installation.html)

**Comment by jravenel** [comment]
Seems it does not work for me on my naas server, I have `/bin/bash: pip: command not found` error. 
I will check internally @veghdev

**Comment by jravenel** [comment]
@simzer @veghdev @petervidos I've done the first template and posted about it :) 

Template: https://github.com/jupyter-naas/awesome-notebooks/tree/master/Vizzu
Asset link: https://public.naas.ai/amVyZW15LTQwbmFhcy0yRWFp/asset/c5b597e8eba8936b180f5539cbc6aec5656c469bec204d476b079e8e1514

**Comment by simzer** [comment]
@jravenel Cool, It's awesome! Thanks!
