### ISSUE TITLE
Hugging Face - Naas drivers integration

### ISSUE THREAD

**Issue by muhtalhakhan** [jupyter-naas/awesome-notebooks#1164]
**Describe the bug**
When I tried to run the template of it comes out with a TYPE ERROR.

**To Reproduce**
1. Go to 'Text Generation'
2. Click on 'Run this cell'
3. Scroll down to 'Output'
4. See error : TypeError: can only concatenate tuple (not "type") to tuple

**Expected behavior**
Expected behavior should be that it would run like the other templates.

**Screenshots**

![image](https://user-images.githubusercontent.com/63025804/188737164-1d791dc0-0874-4e0f-b908-0dfaa704537e.png)

Nope.

I hope you guys will make a change to this template.
Thanks

Muhammad Talha aka Spidey

**Comment by Mukhtarmid** [comment]
@muhtalhakhan you need to look into get API, pipeline might not have been implemented correctly. With pipeline from huggingface's transformer model, I was able to get the output.

**Comment by muhtalhakhan** [comment]
@Mukhtarmid Hey, thanks for the information. It's so old now. Currently, I am looking to create a LLM to analyse the PCAP files by converting them to text or pdf but- couldn't find one. can you help me with it?

any pipeline or opensource LLM that can work over PCAP.

**Comment by Mukhtarmid** [comment]
@muhtalhakhan Sure! I'm on it, further communication on slack.

**Comment by muhtalhakhan** [comment]
@Mukhtarmid add me on slack -> [email](talhakhan325@gmail.com)
