### ISSUE TITLE
BigQuery - Update templates with import naas_drivers

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1171]
Update BigQuery templates using naas_drivers + Add setup videos

**Comment by jravenel** [comment]
@MinuraPunchihewa we just talked about this during the product roadmap today, is there any way we can help you on this? 
Let us know so we can more things further with BigQuery, and communicate :)

**Comment by MinuraPunchihewa** [comment]
@jravenel Hey sorry for the delay. I just made the updates to my notebooks, but when I importing the BigQuer driver to test them out, I came across the following issues,
```
WARNING: naas-drivers 0.106.0 does not provide the extra 'google-cloud-bigquery'
WARNING: naas-drivers 0.106.0 does not provide the extra 'pandas-gbq'
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.6.0 requires six~=1.15.0, but you have six 1.16.0 which is incompatible.
tensorflow 2.6.0 requires typing-extensions~=3.7.4, but you have typing-extensions 4.1.1 which is incompatible.
tensorboard 2.10.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.1 which is incompatible.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/opt/conda/lib/python3.9/site-packages/naas_drivers/__init__.py in wrapper(mod)
     45                 try:
---> 46                     loaded = loader_fn()
     47                     __loaded_drivers[name] = loaded

/opt/conda/lib/python3.9/site-packages/naas_drivers/__init__.py in bigquery()
    433 def bigquery():
--> 434     from naas_drivers.tools.bigquery import BigQuery
    435 

/opt/conda/lib/python3.9/site-packages/naas_drivers/tools/bigquery.py in <module>
----> 1 from google.cloud import bigquery
      2 from google.oauth2 import service_account
      3 import pandas as pd

ImportError: cannot import name 'bigquery' from 'google.cloud' (unknown location)

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-2-104abf9ca366> in <module>
----> 1 from naas_drivers import bigquery

/opt/conda/lib/python3.9/site-packages/naas_drivers/__init__.py in wrapper(mod)
     73                         print(stdout.decode("utf-8"))
     74                         print(stderr.decode("utf-8"), file=sys.stderr)
---> 75                         loaded = loader_fn()
     76                         __loaded_drivers[name] = loaded
     77                     else:

/opt/conda/lib/python3.9/site-packages/naas_drivers/__init__.py in bigquery()
    432 @load_driver(extra_requires="google-cloud-bigquery,pandas-gbq")
    433 def bigquery():
--> 434     from naas_drivers.tools.bigquery import BigQuery
    435 
    436     return BigQuery()

/opt/conda/lib/python3.9/site-packages/naas_drivers/tools/bigquery.py in <module>
----> 1 from google.cloud import bigquery
      2 from google.oauth2 import service_account
      3 import pandas as pd
      4 import logging
      5 

ImportError: cannot import name 'bigquery' from 'google.cloud' (unknown location)
```
Can someone help me with this?

I am faced with this when trying to run from `naas_drivers import bigquery` on naas.

I think it has to do with the dependencies required for the packages used in the driver.

FYI: @FlorentLvr @Dr0p42

**Comment by jravenel** [comment]
@MinuraPunchihewa I think @Dr0p42 can help. Thanks for bringing it up.

**Comment by FlorentLvr** [comment]
> pandas-gbq

Hi @MinuraPunchihewa !

You are right! We need to update the requirements in Naas drivers.
Does it work if you install the version manually on your naas using `!pip install` ?
Could you please provide me the version we need to use for:
- google-cloud-bigquery
- pandas-gbq?

**Comment by MinuraPunchihewa** [comment]
Hey @FlorentLvr,

These are the versions that I have used,
Name: google-cloud-bigquery
Version: 3.3.0

Name: pandas-gbq
Version: 0.17.7

**Comment by FlorentLvr** [comment]
> Hey @FlorentLvr,
> 
> These are the versions that I have used, Name: google-cloud-bigquery Version: 3.3.0
> 
> Name: pandas-gbq Version: 0.17.7

Hi @MinuraPunchihewa!
I just updated the naas_drivers. I should work now with the latest version of Naas.
🙏 

![image](https://user-images.githubusercontent.com/48032461/191212770-957e285b-c621-4a88-98ed-b55e17911a5a.png)

**Comment by MinuraPunchihewa** [comment]
Hey guys,
I updated the notebook templates to use the driver. They seem to be working fine now. Please have a look at the PR.

Could you guys also let me know if there are any other templates that you think will be useful? If so, you can open issues and assign them to me. I will work on them.

Furthermore, I have also been thinking of working on a Redshift driver. Do you guys think that will be useful?

@FlorentLvr @jravenel @Dr0p42
