### ISSUE TITLE
Hugging Face - Question Answering Notebook 

### ISSUE THREAD

**Issue by muhtalhakhan** [jupyter-naas/awesome-notebooks#1189]
Question Answering models can retrieve the answer to a question from a given text, which is useful for searching for an answer in a document. Some question answering models can generate answers without context!

Loading the pipeline
Import Pipeline from Transformer after installing the transformers and tensorflow.

Input
The input would be the text.

Output
For the output a new window is opened at the link provided above by Gradio, where you can enter your context and get your answer delivered.

**Comment by jravenel** [comment]
Add ref to Product Roadmap and label in Project section

**Comment by muhtalhakhan** [comment]
> Add ref to Product Roadmap and label in Project section

I think you have added ref already cause I don't know about it and I know about how to add labels.

**Comment by jravenel** [comment]
yes i did it no problem. Labels are simple and straight forward. Enhancement for new features, bug, good first issue for new things.

**Comment by muhtalhakhan** [comment]
@jravenel please review the request and deploy.

**Comment by jravenel** [comment]
Putting the issue back to Backlog as per my comment on the PR, I cannot get any result from the question asked.

**Comment by jravenel** [comment]
⚡️ This template has been promoted on:

- my LinkedIn account: 
- reposted on Naas's LinkedIn account: 
- my Twitter account: 
- reposted on Naas's Twitter account: 

To let people know how awesome you are @muhtalhakhan

**Comment by muhtalhakhan** [comment]
Thank you @jravenel B)
