### ISSUE TITLE
Python - Create strong random passwords

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1193]
**Describe the problem you are facing**
There are many reasons to create strong random passwords, from onboarding new users to providing a password-reset workflow to creating a new password when rotating credentials. 

**Describe the solution you'd like**
You can easily use a dependency-free Python script to automate this process.

- Input 
word_length = 18
components
- Model 
generate password 
- Output
show password 

**Additional context**
check example here → https://www.airplane.dev/blog/12-useful-python-scripts-for-developers

**Comment by Shivashish-rwt** [comment]
I can create. Can u assign this to me??

**Comment by jravenel** [comment]
> I can create. Can u assign this to me??

Sure, I also added you to the open source Contributor team, welcome to the club ;)

**Comment by Shivashish-rwt** [comment]
Thanks!!!
I'll be providing with PR within few days.

**Comment by Shivashish-rwt** [comment]
@jravenel 
Just wanna ask one thing where should i add my code.

**Comment by paras3624** [comment]
Hey! I would like to contribute to this issue.

**Comment by jravenel** [comment]
@Shivashish-rwt are you still consider contributing on this? The README.md has all the instructions on how to do it.

if not please let us know! 
@paras3624 are you still open to help in case @Shivashish-rwt can't contribute, you can try openning a PR. Thanks ;)

**Comment by SunnyChugh99** [comment]
Hi @jravenel, i would like to contribute to this issue if still open.

**Comment by jravenel** [comment]
@SunnyChugh99 sorry for the late reply it slipped through me. You can do it. 
Here is how to contribute: https://github.com/jupyter-naas/awesome-notebooks#how-to-contribute-
