### ISSUE TITLE
Python - Extract text from a PDF

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1194]
example → https://www.airplane.dev/blog/12-useful-python-scripts-for-developers to be turned into the [Naas template framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository) for production use.

**Comment by MinuraPunchihewa** [comment]
Hey @jravenel, I would like to take this up!

**Comment by jravenel** [comment]
⚡️ This template + the one associated to refine the text without spaces has been promoted on:

- my LinkedIn account: https://www.linkedin.com/posts/jeremyravenel_opensource-github-templates-activity-6988264193925775360-cEtr?utm_source=share&utm_medium=member_desktop
- reposted on Naas's LinkedIn account: https://www.linkedin.com/feed/update/urn:li:activity:6988266098538258432
- my Twitter account: https://twitter.com/ravenel_jeremy/status/1582501853928906753?s=20&t=r77oM5jE9Ouorcpp2mXmJA
- reposted on Naas's Twitter account: https://twitter.com/JupyterNaas/status/1582502355395702785?s=20&t=WtcrpZMbyNVsFum3LvmTVg

To let people know how awesome you are! Thanks for the support :)
