### ISSUE TITLE
Python - Copy text from two PDFs and merge into a new one

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1195]
example → https://www.airplane.dev/blog/12-useful-python-scripts-for-developers to be templated using [Naas template framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository) for production use.

**Comment by MinuraPunchihewa** [comment]
Hey @jravenel, I would like to take this up along with the other PDF issue!

**Comment by jravenel** [comment]
@MinuraPunchihewa Awesome let's start with this one 🤩 I updated the readme for contribution process - we need to make sure the pdf are accessible via URLs so that it can be tested/used/reproduced easily. I was thinking maybe something like combining Bitcoin white paper + ethereum ones, we could just what do you think?

**Comment by MinuraPunchihewa** [comment]
@jravenel Sounds good. I will start working on this.
