### ISSUE TITLE
Python - Convert audio file from wav to mp3

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1196]
example → https://www.airplane.dev/blog/12-useful-python-scripts-for-developers to be templated using [Naas template framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository) for production use.

**Comment by devgenix** [comment]
@jravenel I'll take this up too.

**Comment by jravenel** [comment]
cool  :)

**Comment by jravenel** [comment]
@devgenix hi! do you still consider contributing? end of hacktobefest is approaching and i'd like to make sure we can hit the deadlines. Thanks

**Comment by Mohwit** [comment]
Hey @jravenel can I do this, if it's available?

**Comment by devgenix** [comment]
I've been grossly unavailable due to a number of reasons. Please take it
up.

**Comment by devgenix** [comment]
Hi, Jeremy.

I apologize I wasn't available all these while, I'm really sorry.

**Comment by jravenel** [comment]
No problem @devgenix you are welcome to contribute here whenever you have time :)

**Comment by FlorentLvr** [comment]
@Mohwit, following our conversation on Slack, i would like to review your code to try to help you on this issue. 
Do you work on a branch? Can you create a PR ?

**Comment by Mohwit** [comment]
Yes, I have created a separate branch named 'wav_to_mp3'. I am raising PR.
