### ISSUE TITLE
Python - Filter text

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1197]
example → https://www.airplane.dev/blog/12-useful-python-scripts-for-developers to be templated using [Naas template framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository) for production use.

**Comment by shivam-Purohit** [comment]
Hey can you elaborate a little more ,I can work on this if you like.

**Comment by jravenel** [comment]
Hey @shivam-Purohit, in the article above, section 5 there is a bit more context that can help you buid the template

Quote: 
Matching and filtering text with regular expressions in Python is simple, and the benefits can be enormous. Say you have a system for batch processing sales-confirmation messages, and you need to extract a credit card from the text of an email message. The script below can quickly find any credit card number that matches the pattern, allowing you to easily filter this information from any textual content:

`# Filter Text
# Import re module
import re
# Take any string data
string = """a string we are using to filter specific items.
perhaps we would like to match credit card numbers
mistakenly entered into the user input. 4444 3232 1010 8989
and perhaps another? 9191 0232 9999 1111"""

# Define the searching pattern
pattern = '(([0-9](\s+)?){4}){4}'

# match the pattern with input value
found = re.search(pattern, string)
print(found)
# Print message based on the return value
if found:
  print("Found a credit card number!")
else:
  print("No credit card numbers present in input")`

**Comment by shivam-Purohit** [comment]
sure, I can work on this issue. Seems pretty interesting.

**Comment by jravenel** [comment]
@shivam-Purohit Looking forward to see your contribution 🤙

**Comment by knshkp** [comment]
could i work on this issue

**Comment by jravenel** [comment]
@knshkp already taken by @shivam-Purohit

**Comment by jravenel** [comment]
@shivam-Purohit just a friendly reminder that the deadline for submitting a summary is coming soon 'end of october' :) 
Don't hesitate to let us know if you cannot do it.

**Comment by shivam-Purohit** [comment]
sorry @jravenel got stuck with college and exams. But I am working on it ,if I could not do it I would unassign myself.

**Comment by shivam-Purohit** [comment]
I have come up with something very primitive. What modification we need to come up in this ?
![Screenshot (94)](https://user-images.githubusercontent.com/91889807/198865425-a271400a-359e-4b09-a3f5-36556cf499cb.png)
and is the formatting alright and suggest changes.

**Comment by kaushalkrishna2000** [comment]
Hello @jravenel is this issue still worked on ?

If not then what type of filter are you expecting ?

Thanks

**Comment by kaushalkrishna2000** [comment]
Hello ?
