### ISSUE TITLE
Python - Locate addresses

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1198]
example → https://www.airplane.dev/blog/12-useful-python-scripts-for-developers to be templated using [Naas template framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository) for production use.

**Comment by SuhasBRao** [comment]
HI there, I would like to work on this issue

**Comment by jravenel** [comment]
@SuhasBRao hi, great! I've added you to the open source community group on github to your email. This was you will be able to follow the contribution process in README ;)

**Comment by SuhasBRao** [comment]
Thank you, I have started working on this.

**Comment by jravenel** [comment]
@SuhasBRao Well done 😇 thanks @FlorentLvr for the review

**Comment by jravenel** [comment]
FYI guys, @FlorentLvr @SuhasBRao, just posted about it on: 

- LinkedIn personal account: https://www.linkedin.com/posts/jeremyravenel_hacktoberfest2022-opensource-contribution-activity-6982823114468392960-qoP9?utm_source=share&utm_medium=member_desktop
- LinkedIn Naas account: https://www.linkedin.com/feed/update/urn:li:activity:6982824029627785216
- Twitter personal account: 
https://twitter.com/ravenel_jeremy/status/1577060662928609280?s=20&t=P7BRd_UcppO6b10gvh5Kug
- Twitter Naas account: https://twitter.com/JupyterNaas/status/1577061018999484417?s=20&t=V3zI7sYMrQJWTpdOcp2AnA
