### ISSUE TITLE
Python - Convert a CSV to Excel

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1199]
example → https://www.airplane.dev/blog/12-useful-python-scripts-for-developers to be templated using [Naas template framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository) for production use.

**Comment by devgenix** [comment]
@jravenel I'll take this up.

**Comment by Sophyia7** [comment]
@jravenel I want to take this up.

**Comment by devgenix** [comment]
Okay Sophia, I'm already working on other issues so I'll let you take this.

**Comment by devgenix** [comment]
@jravenel I'm handling this to @Sophyia7 

@Sophyia7 follow the guide to contribute in the project README.

**Comment by jravenel** [comment]
Thanks @devgenix that's good spirit :) @Sophyia7 the key idea here is to use a CSV file URL so that anybody can test without being dependent on local drive files. 

I just added you to the contributor team so you can start follow the contribution process.

**Comment by Sophyia7** [comment]
@jravenel I am having an issue creating a PR that runs all checks, one of the checks says I exposed a secret key, but I didn't include any key in my code. It may be an issue from another folder. Please could you help me look at this issue?

**Comment by jravenel** [comment]
@Sophyia7 looking at it now

**Comment by Sophyia7** [comment]
@jravenel I have resolved the issues, thanks.
