### ISSUE TITLE
Python - Match pattern with regular expressions

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1200]
example → https://www.airplane.dev/blog/12-useful-python-scripts-for-developers to be templated using [Naas template framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository) for production use.

**Comment by srini047** [comment]
I would like to work on this issue.

**Comment by knshkp** [comment]
i would like to work on this issue. could you assign me this issue to me

**Comment by jravenel** [comment]
Hi @knshkp, @srini047 already mentionned he wanted to work on this. Let's find another one for you if you don't mind.

**Comment by jravenel** [comment]
> I would like to work on this issue.

@srini047 just assigned you to this one. Please make sure to follow the instructions on the README :)

**Comment by knshkp** [comment]
yeah sure @jravenel

**Comment by jravenel** [comment]
@srini047 

⚡️ This template has been promoted on:

- my LinkedIn account: https://www.linkedin.com/posts/jeremyravenel_python-opensource-templates-activity-6988619693620084736-Zd_J?utm_source=share&utm_medium=member_desktop
- reposted on Naas's LinkedIn account: https://www.linkedin.com/feed/update/urn:li:activity:6988622485508235264
- my Twitter account: https://twitter.com/ravenel_jeremy/status/1582858201548324865?s=20&t=sJSNYF9oy7oMgMU3rPOAAQ
- reposted on Naas's Twitter account: https://twitter.com/ravenel_jeremy/status/1582858201548324865?s=20&t=sJSNYF9oy7oMgMU3rPOAAQ

To let people know how awesome you are!

**Comment by srini047** [comment]
Thanks Jeremy for sharing it 😊
