### ISSUE TITLE
Python - Convert PNG images to JPG

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1201]
example → https://www.airplane.dev/blog/12-useful-python-scripts-for-developers to be templated using [Naas template framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository) for production use.

**Comment by devgenix** [comment]
Hey, @jravenel 

I can work on this. 
I'll follow the steps to contribute and complete the prerequisites in a jiffy.

**Comment by jravenel** [comment]
@devgenix Cool 👍 let me know if you need help

**Comment by devgenix** [comment]
@jravenel I've accepted the invite and I see that I've been added to a team, do I still need to register to the [Contributor Program](https://form.typeform.com/to/jdls9qZf?typeform-source=www.naas.ai)?

**Comment by jravenel** [comment]
@devgenix it's up to you. If you want to get the latest updates, community events, etc...

**Comment by devgenix** [comment]
@jravenel I have registered to the program and joined the slack community. 
You can now assign this to me and I'll take it up from there.

**Comment by jravenel** [comment]
@devgenix I believe you can assign it to you directly, you dont need me, can you confirm ?

**Comment by devgenix** [comment]
> @devgenix I believe you can assign it to you directly, you dont need me, can you confirm ?

Oh yes, I forgot I now have access.

**Comment by devgenix** [comment]
@jravenel In creating branches, master is the one to use, right?

**Comment by jravenel** [comment]
@devgenix Correct you need to create your branch out of master

**Comment by devgenix** [comment]
@jravenel I've worked on this and create a PR, #1204 for your review.
