### ISSUE TITLE
Python - Compress images

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1202]
example → https://www.airplane.dev/blog/12-useful-python-scripts-for-developers to be templated using [Naas template framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository) for production use.

**Comment by devgenix** [comment]
@jravenel I'd like to work on this.

**Comment by FlorentLvr** [comment]
Hi @devgenix! Hope you are doing well? Did you work on this issue? Do you need any help? 
As no PR is open for this issue, I will move the issue to "Ready" 🙏
