### ISSUE TITLE
Merge Pandas folder into Python folder

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1203]
As of today, Pandas is separated from the Python folder but it is still a part of the Python standard libraries. I think we should consider putting all the standard libraries in the Python folder as people will search for actions they can do + I don't think creating a folder for each lib (os, datetime, etc... is easy to maintain as we want to focus on third party tool in the outline of the awesome-notebooks repo)

What do you think @FlorentLvr ?

**Comment by FlorentLvr** [comment]
@jravenel, I think we should keep it that way because in Pandas we should have all notebooks to manipulate tables which is super usefull for a user coming from Excel. This is something we need to highlight for our business user. Do you agree?

**Comment by jravenel** [comment]
Yes makes sense @FlorentLvr I get your point
