### ISSUE TITLE
Python - Get current city weather

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1207]
Using the following as example : https://github.com/hastagAB/Awesome-Python-Scripts/blob/master/Current_City_Weather/Weather.py

let's build a template following the IMO framework where 

Input: 
CITY = ""

Model: 
Use the code in the above URL 

Output: 
sentence saying 
"The weather in {} is currently {} with a temperature of {} degrees and wind speeds reaching {} km/ph"

**Comment by jravenel** [comment]
@knshkp would you like to work on this one?

**Comment by knshkp** [comment]
yeah sure Thanks for Choosing me!
