### ISSUE TITLE
Python - Convert file from .pptx to .pdf

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1208]
Let's find a way to do it so we can render pptx via pdf inside Jupyter env.

**Comment by rexdivakar** [comment]
Hey @jravenel i would like to work on this, can u please assign it to my name

**Comment by jravenel** [comment]
Hey @rexdivakar thanks for the suggestion. Let me connect you to @FlorentLvr that will be the reviewer. 

I just added you to the contributor team on the GitHub org. 
Let's ensure the pptx is accessible over the internet so anyone can reproduce. 
I found this one for example : https://www.just.edu.jo/~zasharif/Web/SE495/Python/Slides/python1.ppt

So the template would look like: 

Input: 
FILE = "https://www.just.edu.jo/~zasharif/Web/SE495/Python/Slides/python1.ppt"

Model: 
function to transform the file into pdf

Output: 
fallback message "✅ {FILE} has been successfully converted to PDF" 

is that clear for you?
Let me know.

**Comment by rexdivakar** [comment]
Thanks for explaining, will raise a PR once completed.

**Comment by jravenel** [comment]
@rexdivakar Thanks for your message, did you try this lib? 

https://pypi.org/project/ppt2pdf/

+ https://gist.github.com/vikram-ai/5c811d076f7c4d17d3b497fc5fff8224

? 
Let me know 🙏

**Comment by rexdivakar** [comment]
Yup they all have dependency over PowerPoint software and cannot be used across platforms without office softwares installed.

**Comment by jravenel** [comment]
I guess this on is the same ? https://community.esri.com/t5/python-questions/how-can-i-use-python-to-convert-ppt-to-pdf/td-p/310114

It looks like it works for them by reading the thread

**Comment by Venkatakrishnan-Ramesh** [comment]
Hey @jravenel  i would like to work on this ,is it not assigned to anyone, can u please assign it to my name

**Comment by rexdivakar** [comment]
> I guess this on is the same ? https://community.esri.com/t5/python-questions/how-can-i-use-python-to-convert-ppt-to-pdf/td-p/310114
> 
> It looks like it works for them by reading the thread

Testing the same will rasie a PR asap, kindly assign it to my name

**Comment by rexdivakar** [comment]
![image](https://user-images.githubusercontent.com/15235122/194684428-b33906e1-4927-455b-b117-970a9e9aac28.png)


All the snippets you shared require some form of office installation over the device, as i mentioned earlier we cannot directly convert it as its a binary module. Do you have any other suggestions ?

**Comment by jravenel** [comment]
> Hey @jravenel  i would like to work on this ,is it not assigned to anyone, can u please assign it to my name

@Venkatakrishnan-Ramesh It's already assigned as you may see the discussion on this thread 😉

**Comment by jravenel** [comment]
> ![image](https://user-images.githubusercontent.com/15235122/194684428-b33906e1-4927-455b-b117-970a9e9aac28.png)
> 
> 
> 
> 
> 
> All the snippets you shared require some form of office installation over the device, as i mentioned earlier we cannot directly convert it as its a binary module. Do you have any other suggestions ?

- [ ] @rexdivakar we have not been able to sync with @Dr0p42 about this but we will discuss it during the weekly product roadmap next Monday ! Thanks for the research on this 🙏 you can join the meeting next Monday it's public

**Comment by rexdivakar** [comment]
sure definitely !

**Comment by jravenel** [comment]
@rexdivakar moved it to in progress for discussion, I'm wondering if it would not be better to just use the Google Slide API to build slides and export them as a PPT or whatever format programatically, google slides API seems better option, what do you think guys @FlorentLvr @Dr0p42 ?

**Comment by jravenel** [comment]
@Dr0p42 do you think we can set this up in naas? https://colab.research.google.com/drive/1LzpwMj2sktmQYnpo-Tht0k2p84NXAuAb?usp=sharing
