### ISSUE TITLE
Python - Organize directory based on file types

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1213]
The objective is to create a template using [Naas IMO framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository-) inspired by the code on this [LINK](https://github.com/hastagAB/Awesome-Python-Scripts/blob/master/Directory-organizer/Directory-oraganiser.py)

**Comment by knshkp** [comment]
i would like to work on this issue

**Comment by rexdivakar** [comment]
Hey @jravenel if this issue is unassigned i can work on this and raise a PR

**Comment by jravenel** [comment]
Go ahead @rexdivakar

**Comment by rexdivakar** [comment]
Can u eloborate more on the issue please, like how would u like to segrigate the directories to be ? with your feedback i can come up with some good logic

**Comment by jravenel** [comment]
> Can u eloborate more on the issue please, like how would u like to segrigate the directories to be ? with your feedback i can come up with some good logic

Maybe we can just try to make the directory to be organized by file types extension?  ppt, ipynb, etc... 
What do you think @rexdivakar ?

**Comment by rexdivakar** [comment]
cool that can be done, so let me work on this!!

**Comment by jravenel** [comment]
Cool.
