### ISSUE TITLE
Python - Download webpage as PDF

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1214]
The objective is to create a template using [Naas IMO framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository-) inspired by the code on this [LINK](https://github.com/hastagAB/Awesome-Python-Scripts/tree/master/Download-page-as-pdf)

**Comment by sudojarvis** [comment]
@jravenel  can i work on this issue?

**Comment by jravenel** [comment]
Sure I just added you to the community team so you can follow the step by step contribution process here: https://github.com/jupyter-naas/awesome-notebooks#how-to-contribute-

**Comment by sudojarvis** [comment]
@jravenel   I am facing the issue. I am attaching the screenshot. Is there any way I can resolve it?  I tried different things as per StackOverflow. 
![Screenshot from 2022-10-27 19-08-26](https://user-images.githubusercontent.com/75030755/198304068-df786c56-b8d6-447c-9f91-14232dd3a703.png)

![Screenshot from 2022-10-27 19-08-26](https:/
![Screenshot from 2022-10-27 19-09-13](https://user-images.githubusercontent.com/75030755/198303902-dd72401c-c73a-43ca-96f7-ac24b7495be4.png)
/user-images.githubusercontent.com/75030755/198303670-d9240e3e-6
![Screenshot from 2022-10-27 19-09-26](https://user-images.githubusercontent.com/75030755/198303931-8df5807f-1e87-4fd0-bdb2-e0fc70c06fbc.png)
635-4d7c-9cd4-c9279d0c44b0.png)

**Comment by sudojarvis** [comment]
I have unassigned myself.  If some one want takes over they can go ahead.

**Comment by jravenel** [comment]
Ok @sudojarvis you don't think you can finalize?

**Comment by Mukhtarmid** [comment]
I tried with the given link, please don't go with that method, it takes to much time. Should I use a different method and try to solve this ticket? @jravenel

**Comment by jravenel** [comment]
> I tried with the given link, please don't go with that method, it takes to much time. Should I use a different method and try to solve this ticket? @jravenel 

Yes 🙌 go ahead if you think you can solve the issue, please submit PR and let me know I will review!
