### ISSUE TITLE
Python - Display word definition

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1215]
The objective is to create a template using [Naas IMO framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository-) inspired by the code on this link https://github.com/hastagAB/Awesome-Python-Scripts/blob/master/English_Theasauras/app.py

**Comment by srini047** [comment]
I would like to take up this issue.

**Comment by jravenel** [comment]
go ahead @srini047

**Comment by srini047** [comment]
Fix typo in issue name: ~~world~~ -> word

**Comment by srini047** [comment]
I just have a small doubt. I have used the same code (as the reference [provided](https://github.com/hastagAB/Awesome-Python-Scripts/blob/master/English_Theasauras/app.py)) and also implemented using a [pydictionary](https://pypi.org/project/PyDictionary/) model which is better and has lots of features.

With which shall I proceed?
Any support is appreciated🚀

**Comment by jravenel** [comment]
Hi @srini047, I let you judge but I really like this pydictionary from what I see. Go ahead with it.

**Comment by srini047** [comment]
> Hi @srini047, I let you judge but I really like this pydictionary from what I see. Go ahead with it.

Great!!
