### ISSUE TITLE
Python - Find phone number in string

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1216]
The objective is to create a template using [Naas IMO framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository-) inspired by the code on this link https://github.com/hastagAB/Awesome-Python-Scripts/blob/master/Find-PhoneNumber-in-String/Find-PhoneNumber-in-String.py

**Comment by anastazir** [comment]
!assign

**Comment by anastazir** [comment]
Hi @jravenel, can I be assigned to work on this issue?

**Comment by jravenel** [comment]
Sure, I just added you to the contributor list, please let me know if you need help, the process is on the README.

**Comment by jravenel** [comment]
⚡️ This template has been promoted on:

- my LinkedIn account: https://www.linkedin.com/posts/jeremyravenel_feat-python-find-phone-number-in-string-activity-6987542479856140288-Ybr9?utm_source=share&utm_medium=member_desktop
- reposted on Naas's LinkedIn account: https://www.linkedin.com/posts/jeremyravenel_feat-python-find-phone-number-in-string-activity-6987542479856140288-Ybr9?utm_source=share&utm_medium=member_desktop
- my Twitter account: https://twitter.com/ravenel_jeremy/status/1581779495085694976
- reposted on Naas's Twitter account: https://twitter.com/JupyterNaas/status/1581781046906871808

To let people know how awesome you are @anastazir !
