### ISSUE TITLE
Python - Create GitHub repository

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1217]
The objective is to create a template using [Naas IMO framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository-) inspired by the code on this link: https://github.com/hastagAB/Awesome-Python-Scripts/blob/master/Git_repo_creator/git_repo_creator.py

**Comment by knshkp** [comment]
i would like to work on this issue

**Comment by jravenel** [comment]
@knshkp great, just assigned you.
