### ISSUE TITLE
Twilio - Call API to verify phone numbers

### ISSUE THREAD

**Issue by srini047** [jupyter-naas/awesome-notebooks#1224]
This is the Template to make calls to verified phone numbers using Twilio.

**Comment by jravenel** [comment]
adding the product roadmap reference here in Projects section (you did it in the PR)

**Comment by jravenel** [comment]
adding Labels

**Comment by jravenel** [comment]
modifiying the name for clarity and better understanding. Is that ok @srini047 ?

**Comment by srini047** [comment]
> modifiying the name for clarity and better understanding. Is that ok @srini047 ?

Yeah. That's absolutely cool!!
