### ISSUE TITLE
Python - Rename file

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1233]
Rename file.

**Comment by rexdivakar** [comment]
Hey i would like to work on this pls

**Comment by jravenel** [comment]
⚡️ This template has been promoted on: 

- my LinkedIn account: https://www.linkedin.com/posts/jeremyravenel_opensource-love-python-activity-6986072705175318528-dYMo?utm_source=share&utm_medium=member_desktop
- reposted on Naas's LinkedIn account: https://www.linkedin.com/feed/update/urn:li:activity:6986076006495223808
- my Twitter account: https://twitter.com/ravenel_jeremy/status/1580312050663755777?s=20&t=HLSGbTzFfNx3Rdm7TsIC4Q
- reposted on Naas's Twitter account: https://twitter.com/JupyterNaas/status/1580312714743644160?s=20&t=HLSGbTzFfNx3Rdm7TsIC4Q

to let people know how awesome you are @rexdivakar  :)
