### ISSUE TITLE
Kaggle - Download Datasets

### ISSUE THREAD

**Issue by waqarg2001** [jupyter-naas/awesome-notebooks#1234]
**Describe the problem you are facing**
Instead of downloading Kaggle data in pc, it should be directly downloaded in the notebook where it has to be used.

**Describe the solution you'd like**
a function which takes the URL of the dataset and downloads the data in the notebook directory.

- Input 
URL
- Model 
Python Function
- Output
Data downloaded in notebook directory.

**Comment by rexdivakar** [comment]
Hey @waqarg2001 i would like to work on this, pls assign it to me

**Comment by waqarg2001** [comment]
.take

**Comment by waqarg2001** [comment]
@rexdivakar how to assign? I am new here.

**Comment by rexdivakar** [comment]
Got it thanks buddy

**Comment by waqarg2001** [comment]
@rexdivakar  i want to self assign

**Comment by jravenel** [comment]
@waqarg2001 ⚡️ This template has been promoted on:

- my LinkedIn account: https://www.linkedin.com/posts/jeremyravenel_opensource-love-kaggle-activity-6991149228962017281-BW_G?utm_source=share&utm_medium=member_desktop
- reposted on Naas's LinkedIn account: https://www.linkedin.com/posts/naas-ai_opensource-love-kaggle-activity-6991150789998080001-LbgA?utm_source=share&utm_medium=member_desktop
- my Twitter account: https://twitter.com/ravenel_jeremy/status/1585385759577886722?s=20&t=kTiacKKxOMZqL_7PuBzW5w
- reposted on Naas's Twitter account: https://twitter.com/JupyterNaas/status/1585386265306103808?s=20&t=kTiacKKxOMZqL_7PuBzW5w

To let people know how awesome you are!
