### ISSUE TITLE
Generate contribution certificate when PR is merged

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1235]
As a contributor, anytime my PR is successfully merged into awesome-notebooks repo, I would like to receive a github notification in the comment that my PR was merged + certificate. 

"Thank you for your contribution @slug, your PR has been merged into the master branch of awesome-notebook. 
Here is the contribution certificate you can share on social media so everybody knows how awesome you are 🤙🌎. 
Spread the #opensource love 💚" + image of the certificate. 

Reference: https://github.com/jupyter-naas/awesome-notebooks/blob/master/Pillow/Pillow_Generate_A_Certificate_Template.ipynb

The idea is to add a generate_certificate.yaml inside the following folder: https://github.com/jupyter-naas/awesome-notebooks/tree/master/.github/workflows

**Comment by jravenel** [comment]
@SuhasBRao maybe you would like to take a look at this at you created the PR.

**Comment by SuhasBRao** [comment]
Yes, I will work on it.

**Comment by jravenel** [comment]
Cool 👍 @Dr0p42 can help if you need

**Comment by SuhasBRao** [comment]
I might need help while creating a workflow

**Comment by jravenel** [comment]
no problem, just prepare a PR as you think it should be and @Dr0p42 will check and answer questions based on the PR. 
The essential point here is to commit your work and try to be as explicit as you can be in the questions 🤙 🔥🔥

**Comment by SuhasBRao** [comment]
@jravenel is there a way to modify variables used in .ipynb using .yaml. To generate a certificate I need to modify certain variables like date_of_contribution, contributor_name etc.

**Comment by jravenel** [comment]
I think it should be a copy of your code from the .ipynb, not the same so you can do what you want

**Comment by SuhasBRao** [comment]
Hi @jravenel , I am able to generate certificate as PR comment, I'm using Python script to create certificate and .yaml file runs this script during workflow. 

Below is a certificate that I have generated on my forked repository, However, You can see that under Organization, name **SuhasBRao** in this case, I am not able to fetch user bio,
![Screenshot from 2022-10-14 08-30-46](https://user-images.githubusercontent.com/65769327/195752750-6bcf8189-0662-4def-91a6-5fd24db0557d.png)

I am using this inside my python script to fetch organization bio, 

![Screenshot from 2022-10-14 08-37-17](https://user-images.githubusercontent.com/65769327/195753211-2b2dfcc8-dff8-4c52-86a5-ff49310854e4.png)

Can you help me with this, or is there a way to add bio without making requests calls.

**Comment by SuhasBRao** [comment]
@jravenel I solved it instead of making requests from .py I used API's in .yaml file, Heres the output. Let me know what you think I will create a PR.
![Screenshot from 2022-10-14 11-28-58](https://user-images.githubusercontent.com/65769327/195773168-8abb4e3e-5d95-49ca-b0dc-af831cc782a2.png)

**Comment by jravenel** [comment]
Let's go for the PR!! that's awesome man! put @Dr0p42 and myself as reviewer please

**Comment by jravenel** [comment]
@SuhasBRao after discussion internally, we are not going to do it now (not a priority to follow this new process on top of what we are already doing) but we may reopen it later.
