### ISSUE TITLE
Add a sentence to add new template or report a bug below all "Open in Naas" button in awesome-notebooks

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1236]
This will enable anyone to report problems and suggest new templates more easily.

**Comment by FlorentLvr** [comment]
@jravenel, as we discussed, I proposed to add this solution:
![image](https://user-images.githubusercontent.com/48032461/196377170-32f81da6-1831-497f-89f1-19fcc227feaa.png)

I will add this syntaxe on the create open button function:
<br><br>
<a href="https://github.com/jupyter-naas/awesome-notebooks/issues/new?assignees=&labels=&template=template-request.md&title=Tool+-+Action+of+the+notebook+">💡 Template request</a> | <a href="https://github.com/jupyter-naas/awesome-notebooks/issues/new?assignees=&labels=&template=bug_report.md&title=">🚨 Bug report</a>
