### ISSUE TITLE
Naas - Send awesome-notebooks template list to Gsheet

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1237]
Fields to be accessed: 

root
subdir
github_url
title
download_url
tags
author
description
author_url
date_merged
librairies
modules
domain

**Comment by jravenel** [comment]
This will personally help me monitor the templates where content where published @FlorentLvr thanks :)

**Comment by FlorentLvr** [comment]
@jravenel, done on another repo.

**Comment by jravenel** [comment]
which one @FlorentLvr ?

**Comment by FlorentLvr** [comment]
> which one @FlorentLvr ?

a private repo as we don't have automation yet on this topic
