### ISSUE TITLE
Python - Create directory

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1248]
- Input
dir_path = ""

- Model
check if dir_path exists if not create  dir

- Output
print(f'Directly successfully created {dir_path}')

**Comment by yashsarnaik22** [comment]
Can I do this?
please assign this to me.

**Comment by FlorentLvr** [comment]
> Can I do this? please assign this to me.

@yashsarnaik22! Sure, I just added you as an open-source contributor!
You can follow the steps on our README to contribute to our repository: https://github.com/jupyter-naas/awesome-notebooks#readme
Let me know if I can help! 🙏

**Comment by Sarthak02g** [comment]
Hey there,
If not resolved, Kindly assign me this issue.

**Comment by moe-men** [comment]
Hey @FlorentLvr 
please if still open, assign me this issue

**Comment by jravenel** [comment]
@moe-men just added you to the team, you can take this up if you want!

@Sarthak02g are you still interested? Maybe you could help on other issues?

**Comment by rudrakshkarpe** [comment]
Can I work on this issue?

**Comment by jravenel** [comment]
> Can I work on this issue?

@rudrakshkarpe as you can see this is already a busy thread. Can we find other issues to contribute to?
