### ISSUE TITLE
Dash Plotly - Add dynamic link on label click on plotly chart python

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1249]
I would like to be able to click on the label displayed on my horizontal barchart in Plotly / Dash Plotly: 
https://stackoverflow.com/questions/25148462/open-a-url-by-clicking-a-data-point-in-plotly

- Input
App setup

- Model
Create plotly graph
Create a Dash app with Plotly graph
Setup callback

- Output
Display app

Start from awesome-notebooks template: https://github.com/jupyter-naas/awesome-notebooks/blob/master/Dash/Dash_Deploy_app_in_Naas.ipynb

**Comment by jravenel** [comment]
Hi @oguzakif , glad you want to contribute, please follow the instructions in the awesome-notebook readme to start contributing. -> https://github.com/jupyter-naas/awesome-notebooks#how-to-contribute-

Cheers!
