### ISSUE TITLE
Python - Get all files from directory

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1250]
As a user, I would like to get all files from a directory even in a sub-directory.
I recommend to use the library 'glob'

- Input
Setup Variables
dir_path = ""

- Model 
Get all files

- Output
Display result
print(files)

**Additional context**

**Comment by kunalsingh1301** [comment]
import glob
  
  
# Returns a list of names in list files.
print("Using glob.glob()")
files = glob.glob('/home/kunal/Desktop/ks/**/*.txt', 
                   recursive = True)
for file in files:
    print(file)
  
  
# It returns an iterator which will be printed simultaneously.
print("\nUsing glob.iglob()")
for filename in glob.iglob('/home/kunal/Desktop/ks/**/*.txt',
                           recursive = True):
    print(filename)`

**Comment by FlorentLvr** [comment]
> @FlorentLvr can you asssign it to me?

@kunalsingh1301! Sure, I just added you as open-source contributor!
You can follow the steps on our README to contribute to our repository: https://github.com/jupyter-naas/awesome-notebooks#readme
Let me know if I can help!

**Comment by FlorentLvr** [comment]
@kunalsingh1301, all good on your side? I saw you didn't accept our invitation on GitHub (open source contributor). You should have received an email! Let me know if you have any doubts.

**Comment by ayoub-berdeddouch** [comment]
@FlorentLvr assign, if not taken already!

**Comment by FlorentLvr** [comment]
> @FlorentLvr assign, if not taken already!

As you did not answer @kunalsingh1301, I reassign the issue to @ayoub-berdeddouch!
Hope you will be able to contribute on naas on another issue @kunalsingh1301!
@ayoub-berdeddouch, glad you want to contribute, please follow the instructions in the awesome-notebook readme to start contributing. -> https://github.com/jupyter-naas/awesome-notebooks#readme

**Comment by FlorentLvr** [comment]
> > @FlorentLvr assign, if not taken already!
> 
> As you did not answer @kunalsingh1301, I reassign the issue to @ayoub-berdeddouch! Hope you will be able to contribute on naas on another issue @kunalsingh1301! @ayoub-berdeddouch, glad you want to contribute, please follow the instructions in the awesome-notebook readme to start contributing. -> https://github.com/jupyter-naas/awesome-notebooks#readme

**Comment by ayoub-berdeddouch** [comment]
Description: This notebook gives you the ability to get all files from a directory even in a sub-directory.
@FlorentLvr please check and give me your feedback!
