### ISSUE TITLE
PowerPoint - Add title + line in presentation

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1251]
- Input
Create a presentation

- Model 
Create title
Create line below title

- Output
Save presentation

**Comment by jravenel** [comment]
@ayoub-berdeddouch it seems like @Eviaiy is already on it, @Eviaiy can you confirm that? 

cc @FlorentLvr

**Comment by Eviaiy** [comment]
Yes @jravenel. 
@FlorentLvr and I are working on it.

**Comment by jravenel** [comment]
@ayoub-berdeddouch would you like to work on the same but for google slides? 

Thanks would be super useful. If you do, I will create Issue.

**Comment by ayoub-berdeddouch** [comment]
@jravenel yes why not, just create the issue I will work on it with Google slide API using python.

**Comment by ayoub-berdeddouch** [comment]
@FlorentLvr I have created a template for Powerpoint! 
and if @jravenel could create the issue for Google Slides I will try to finish it by tomorrow. 🚀

**Comment by ayoub-berdeddouch** [comment]
@jravenel could you check it and merge if it's good!!
