### ISSUE TITLE
Python - Copy files and subdir from directory to another directory

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1253]
Copy all elements inside a directory to another directory
Overwrite duplicates elements

- Input 
dir_path_src = "" #Directory path source
dir_path_des = "" #Directory path destination

- Model 
Get elements from the source directory
Copy elements in the destination directory (manage duplicate)

- Output
Display all elements duplicated.

**Comment by hitchhicker007** [comment]
@FlorentLvr I want to work on this issue. can you please assign it to me?

**Comment by FlorentLvr** [comment]
@hitchhicker007! Sure, I just added you as an open-source contributor!
You can follow the steps on our README to contribute to our repository: https://github.com/jupyter-naas/awesome-notebooks#readme
Let me know if I can help! 🙏

**Comment by hitchhicker007** [comment]
@FlorentLvr what should be the folder name?

**Comment by jravenel** [comment]
Python @hitchhicker007 the framework we use is "Tool/folder - action" in the issue

**Comment by hitchhicker007** [comment]
@FlorentLvr should I overwrite duplicated files or just print the message that the file already exists?

**Comment by FlorentLvr** [comment]
> @FlorentLvr should I overwrite duplicate files or just print the message that the file already exists?

@hitchhicker007! Could you create a parameter in your function to overwrite? In this way, we could choose:
`def copy_folder(dir_src, dir_des, overwrite=True)`
