### ISSUE TITLE
XGBoost - A binary classification example with hyper-parameters optimization

### ISSUE THREAD

**Issue by Rayryu** [jupyter-naas/awesome-notebooks#1258]
### The problem
As a data scientist, I would like solve binary classification problems on tabular datasets using a performing Machine learning model. 

### Suggested solution
[XGBoost outperforms ML/DL models ](https://arxiv.org/pdf/2106.03253.pdf) when it comes to tabular data. 
A template with sample training code of a XGBoost classification model, including hyper-parameters optimization would be very handy to fit datasets.

- Input
Dataset (to be read as a pandas DataFrame)
- Model
XGBoost classification model with hyper-parameters search using a grid search.
- Output
A trained XGBoost classification model, including performance metrics.

**Comment by jravenel** [comment]
⚡️ This template has been promoted on:

- my LinkedIn account: 
- reposted on Naas's LinkedIn account: 
- my Twitter account: 
- reposted on Naas's Twitter account: 

To let people know how awesome you are, well done @Rayryu
