### ISSUE TITLE
Add message with link of the template when PR is merged

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1261]
When a PR is merged, the CI (github action) should add a message to the PR (and if possible in the Issue as well) saying "The template is now available on the master branch on this link: https://github..... "

**Comment by jravenel** [comment]
@SuhasBRao do you want to keep up working on the CI?

**Comment by SuhasBRao** [comment]
Sure, I would love to. Do I need to create a PR comment.

**Comment by jravenel** [comment]
> Sure, I would love to. Do I need to create a PR comment.

Yes that's the idea.

**Comment by SuhasBRao** [comment]
Cool, And what exactly do I need to link. Is it a link to .ipynb file that solves the issue

**Comment by jravenel** [comment]
Yes to the ipynb file in master branch that solve issue

**Comment by SuhasBRao** [comment]
Okay, I will work this issue.

**Comment by SuhasBRao** [comment]
@jravenel, is this the kind of comment you asked for.

![Screenshot from 2022-10-18 19-10-32](https://user-images.githubusercontent.com/65769327/196446471-043a9329-4cb9-4213-ac9c-41fbf1a1701e.png)

This generates comment only if .ipynb file is detected in PR chagnes and when that PR is merged to master branch.

**Comment by SuhasBRao** [comment]
@jravenel let me know what you think about this so I can modify it as required.

**Comment by FlorentLvr** [comment]
@jravenel, I think you missed the last comment of @SuhasBRao ! The proposition seems good. Do you agree ?

**Comment by jravenel** [comment]
Hi @SuhasBRao, happy new year. 
We discussed about it with the team during the team and we think that to make this more useful, we need to use OpenAI to generate automatically and propose linkedin and twitter post. Wanna work on this update?

**Comment by SuhasBRao** [comment]
Thanks a lot @jravenel, wish you the same.
That sounds great, but i don't have much exposure on OpenAI. I might need to time to learn few things.

**Comment by jravenel** [comment]
✌️

**Comment by jravenel** [comment]
Do you need help on this @SuhasBRao we are moving it next week iteration FYI/.
