### ISSUE TITLE
Add CI task "Update /templates page in docs from awesome-notebooks Readme.md"

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1262]
@chicken-biryani  this is linked to your suggestion on the gdoc, I believe the readme and the landing page in the doc should be the same and hence be automated. 

What do you think?

Source: https://github.com/jupyter-naas/awesome-notebooks/blob/master/README.md
Target: https://github.com/jupyter-naas/docs/blob/master/templates.md

**Comment by FlorentLvr** [comment]
Done
