### ISSUE TITLE
HubSpot - Create / Update / Delete / Get company in HubSpot

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1263]
API: https://developers.hubspot.com/docs/api/crm/companies

Create 4 notebooks (IMO framework) in the HubSpot folder to interact with the company object.

**Comment by srini047** [comment]
Hi @FlorentLvr !!

I would like to work on this issue.

**Comment by FlorentLvr** [comment]
> Hi @FlorentLvr !!
> 
> I would like to work on this issue.
> 

Sure! TY! Let me know if you need anymore info!

**Comment by jravenel** [comment]
@srini047 hi! do you still consider contributing on this? as hacktobefest end is approaching, let me know if you are available for this.

**Comment by srini047** [comment]
> @srini047 hi! do you still consider contributing on this? as hacktobefest end is approaching, let me know if you are available for this.

Yeah, @jravenel ! You can expect an update from me by EOD (IST).

**Comment by jravenel** [comment]
@srini047 Good thanks

**Comment by srini047** [comment]
@jravenel Sorry to say that since I had my GCCP exam scheduled today, it altered all my plans of contributing. But I would like to contribute to the issue even after Hacktoberfest. Is that fine?

Once again, sorry for the inconvenience.

**Comment by jravenel** [comment]
of course no problem

**Comment by jravenel** [comment]
Hey @srini047 as you are already on the search project I'll just remove you from this now and put it back to backlog

**Comment by FlorentLvr** [comment]
To be created in separated issues next week
