### ISSUE TITLE
Windsor.ai - Generate dashboard from API Key

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1264]
**Describe the problem you are facing**
As a watson.ai python user, I would like to use Jupyter to generate dashboard

**Describe the solution you'd like**
A Dash app/dashboard where I can put my API key in the front end so it refreshes the dashboard

Example to follow to structure the notebook in the awesome-notebooks IMO framework : https://github.com/jupyter-naas/awesome-notebooks/blob/master/Naas%20Dashboard/Naas_Dashboard_Financial_Consolidation.ipynb

**Additional context**
This should be then further deployed to as-a-service to enable user to test for a webinar between @eliasdabbas, windsor.ai,  an naas.

**Comment by Dr0p42** [comment]
Hello everyone, 

for the url it will be something like https://<app_name>.windsor.service.naas.ai/ (I still need to configure `service.naas.ai` for now it's `kn.naas.ai`).

I will have some setup to do for you @eliasdabbas before you can deploy your Dashboard in our new cluster.

Is your Notebook stored somewhere on Github ? 

Best

**Comment by Dr0p42** [comment]
> It's going to be on here imo. Awesome notebooks @Dr0p42

Oki doki 👍

**Comment by eliasdabbas** [comment]
@jravenel  @Dr0p42 I just created a [pull request for this notebook](https://github.com/jupyter-naas/awesome-notebooks/pull/1274).
Happy to make any changes if required.

**Comment by jravenel** [comment]
@eliasdabbas FYI I made the necessary changes because it was not following the framework, I will follow up on deployment later  today or tmwr

**Comment by eliasdabbas** [comment]
Thanks for doing it @jravenel, and sorry I didn't get the change to make the changes.

Looking forward to the deployed version!
