### ISSUE TITLE
Whatsapp - Automate the Text Message 

### ISSUE THREAD

**Issue by muhtalhakhan** [jupyter-naas/awesome-notebooks#1266]
**Can We Automate Messaging on WhatsApp?**
_Yes, it is possible through WhatsApp Business API to automate WhatsApp messaging._

**Describe the problem you are facing**
My idea is to automate the text message at first then we can automate other stuff easily.

**Describe the solution you'd like**
For this we will be requiring its API (Business). I will be attaching the links down in the issue.

- Input : It would require the phone numbers of the receiver and sender along with the text message.
- Model : the model here would be our API i.e. Business Cloud API of Wapp.
- Output : Automation of text messages will be the first priority afterwards we try to automate other stuff.

**Additional context**

Would like to summarise the process:

first up we need to "Set up Developer Assets and Platform Access" for setting this up we are required to register ourself as a "Meta Dev", "Enable 2FA", and create a "meta app" by selecting "Business" as type afterwards you are required to create a "Wapp Business Acc", and add a number to it that will redirect to "Getting Started" page after verification.

Ref: https://developers.facebook.com/docs/whatsapp/cloud-api/get-started

Well, this API costs according to session and a session here is a conversation of 24 hours between a contact and your business.

Ref: https://www.sendinblue.com/blog/how-whatsapp-business-api-pricing-works/

The complete resources -> https://business.whatsapp.com/developers/developer-hub

For businesses who want to get started with the WhatsApp Business Platform, please fill out the form below to talk to sales -> https://business.whatsapp.com/learn-more

**Comment by jravenel** [comment]
>Closed as conflict with : https://github.com/jupyter-naas/awesome-notebooks/issues/100
