### ISSUE TITLE
PowerPoint- Create Report

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1271]
This notebook creates a PowerPoint presentation.

**Comment by ayoub-berdeddouch** [comment]
@FlorentLvr assign me to it!

**Comment by jravenel** [comment]
⚡️ @ayoub-berdeddouch this template has been promoted on:

- my LinkedIn account:
- reposted on Naas's LinkedIn account: 
- my Twitter account: 
- reposted on Naas's Twitter account: 

To let people know how awesome you are!

**Comment by ayoub-berdeddouch** [comment]
Thank you @jravenel for the promotion 😸
Always a pleasure to contribute!!
