### ISSUE TITLE
Medium - Publish article from Mardown file via API

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1275]
The objective is to create a template using [Naas IMO framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository-) inspired by the code on this link https://betterprogramming.pub/programmatically-publish-a-markdown-file-as-a-medium-story-with-python-b2b072a5f968

**Comment by Venkatakrishnan-Ramesh** [comment]
Hey @jravenel i would like to work on this issue, so can you kindly assign me

**Comment by FlorentLvr** [comment]
To be reopened with draft.
