### ISSUE TITLE
Naas Dashboards - Web Analytics

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1280]
As discussed @techgoddess1, here is the good first issue for you on the cyber security dashboard.
The objective is to review the notebook structure/outline first. We will do other issues for what comes next (coding the components)

It should follow the template example : https://github.com/jupyter-naas/awesome-notebooks/blob/master/Dash/Dash_Deploy_app_in_Naas.ipynb

But things should be a bit more elaborated in the model section with the different components of the dashboards, cf the example below:
<img width="1098" alt="Screenshot 2022-08-02 at 18 13 30" src="https://user-images.githubusercontent.com/21052349/182422725-cf41712d-f0d9-4e93-b680-5ed803b55c56.png">

**Comment by jravenel** [comment]
@techgoddess1 let's take a look at the dashboard you have done tomorrow

**Comment by FlorentLvr** [comment]
@techgoddess1, hope you are doing well :)! Do you need any support on this one? Let me know, I will be happy to help 😄 🙏

**Comment by jravenel** [comment]
pushing back to backlog @techgoddess1, let me know when you have to time to restart.
