### ISSUE TITLE
FEC - Create dashboard Dash

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1281]
Notebook name: FEC_Create_dashboard_Dash

**Data source:**

Google Sheet => https://docs.google.com/spreadsheets/d/1Sz4tDDFYvCCSQj5Pywk0ybrWbrLW8QKqNN8_nq6Kpp8/edit#gid=1166311839

**Comment by FlorentLvr** [comment]
> Notebook name: FEC_Create_dashboard_Dash
> 
> **Data source:**
> 
> Google Sheet => https://docs.google.com/spreadsheets/d/1Sz4tDDFYvCCSQj5Pywk0ybrWbrLW8QKqNN8_nq6Kpp8/edit#gid=1166311839

@Eviaiy, you can start this template using the data stored in Gsheet. (@jravenel )

**Comment by jravenel** [comment]
@Eviaiy all clear for you?

**Comment by Eviaiy** [comment]
@jravenel  Yes everything is clear

**Comment by jravenel** [comment]
cool, just pass this issue to InProgress when you are on it then ;)

**Comment by ayoub-berdeddouch** [comment]
@jravenel can I join? 
The access to Gsheet is refused!!

**Comment by jravenel** [comment]
> @jravenel can I join? The access to Gsheet is refused!!

@ayoub-berdeddouch as Meriem is on it I don't think it's needed. Don't you want to start template the things we discussed Saturday about market data prediction like oil? or maybe recommender example?

**Comment by ayoub-berdeddouch** [comment]
Sure I started some research on it! just wanted to complete the #hacktoberfest 😸 !!
Good luck @Eviaiy 👍🏻

**Comment by jravenel** [comment]
Hey @Eviaiy, any progress on this? :)

**Comment by FlorentLvr** [comment]
@Eviaiy, just checking ? Do you make progress on this one?
