### ISSUE TITLE
H20 - Get started with autoML 

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1288]
**Describe the problem you are facing**
I want to get started with using H20 in my notebooks. 

**Describe the solution you'd like**
A clear and simple template to implement H20 in my notebooks following the IMO framework. 

- Input 
- Model 
- Output

**Additional context**
Here is how to contribute: https://github.com/jupyter-naas/awesome-notebooks#how-to-contribute-

**Comment by Mohwit** [comment]
I would like to work on this. Can I take this?

**Comment by srini047** [comment]
> I would like to work on this. Can I take this?

Sure. Go ahead🚀

**Comment by Mohwit** [comment]
Ok, Thanks!

**Comment by mukhtarmid** [comment]
@Mohwit, What's the status?! Should I pick up this ticket?

**Comment by Mohwit** [comment]
> @Mohwit, What's the status?! Should I pick up this ticket? 

We need java for h2o to work and Java is not available in naas environment. @jravenel I guess we need to close this issue.

**Comment by jravenel** [comment]
Yes !
