### ISSUE TITLE
Pandas - Drop multiples columns in dataframe

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1304]
#datacleaning

• Input

list of columns to drop
to_drop = []

• Model

df = df.drop(to_drop, axis=1)

• Output

df

**Comment by SunnyChugh99** [comment]
Hi @FlorentLvr , i can work on this issue, will start once you acknowledge.

**Comment by FlorentLvr** [comment]
> Hi @FlorentLvr, I can work on this issue, will start once you acknowledge.

@SunnyChugh99, this is already done, the issue is closed! But thank you for asking!
