### ISSUE TITLE
Pandas - Drop Duplicate Columns in Pandas

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1309]
Template to be duplicated in awesome notebooks "[Pandas_Drop_First_Column.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/master/Pandas/Pandas_Drop_First_column.ipynb)"

Reference: https://www.statology.org/pandas-drop-duplicate-columns/

**Comment by SunnyChugh99** [comment]
Hi @FlorentLvr, I would like to work on this issue.

**Comment by FlorentLvr** [comment]
> Hi @FlorentLvr, I would like to work on this issue.

Sure! You can working on it :) TY

**Comment by FlorentLvr** [comment]
@SunnyChugh99, hope you are doing well! 
Did you start working on this issue yet ? If you do, you can open a PR and tag me once it's done! TY

**Comment by SunnyChugh99** [comment]
Yes I have started on this,  will raise a PR once done.

**Comment by SunnyChugh99** [comment]
Hi @FlorentLvr , @jravenel  I have attached a PR for this issue. Thanks!
