### ISSUE TITLE
Pandas - Drop Columns by Index

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1310]
Template to be duplicated in awesome notebooks "[Pandas_Drop_First_Column.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/master/Pandas/Pandas_Drop_First_column.ipynb)"

Reference: https://www.statology.org/pandas-drop-column-by-index/

**Comment by jravenel** [comment]
What do you mean by duplicated @FlorentLvr? == use the article mentionned above to create the template or duplicate another template?

**Comment by FlorentLvr** [comment]
> What do you mean by duplicated @FlorentLvr? == use the article mentionned above to create the template or duplicate another template?

Use the template mentionned above to kick start the new template because it's the same logic, tags... etc

**Comment by SunnyChugh99** [comment]
Hi @FlorentLvr, I can work on this issue. Do let me know if this needs to be done.

**Comment by FlorentLvr** [comment]
> Hi @FlorentLvr, I can work on this issue. Do let me know if this needs to be done.

Sure! @SunnyChugh99

**Comment by SunnyChugh99** [comment]
Yes I have started on this,  will raise a PR once done.

**Comment by SunnyChugh99** [comment]
Hi @FlorentLvr, @jravenel  I have attached a PR for this issue. Thanks!
