### ISSUE TITLE
GitHub - Create leaderboard of contributors

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1318]
**Describe the problem you are facing**
Create a leaderboard of all the contributors and the points they have win via contributions. 
We made a v0 we would like to resurect. 

Contact me if you are interested to learn more.
![Screenshot 2022-12-01 at 00 04 11](https://user-images.githubusercontent.com/21052349/204927061-acb70d08-c04c-4e3a-929c-d329adef368c.png)

**Comment by jravenel** [comment]
@SuhasBRao following our conversation by email, here is the issue :)

**Comment by SuhasBRao** [comment]
> **Describe the problem you are facing**
> Create a leaderboard of all the contributors and the points they have win via contributions. 
> We made a v0 we would like to resurect. 
> 
> Contact me if you are interested to learn more.
> ![Screenshot 2022-12-01 at 00 04 11](https://user-images.githubusercontent.com/21052349/204927061-acb70d08-c04c-4e3a-929c-d329adef368c.png)
> 

I think we can work on this.

**Comment by SuhasBRao** [comment]
> @SuhasBRao following our conversation by email, here is the issue :) @FlorentLvr can share the code and we can provide more context, I think what we need something like in Pioneer, maybe we can do this with Dash. 
> ![Screenshot 2022-12-01 at 00 08 15](https://user-images.githubusercontent.com/21052349/204927463-df92ed6f-ee12-404b-adea-82b39aee328b.png)
> 

I did not get what you meant by ' in Pioneer'? . We can work on creating a dashboard like system though.

**Comment by FlorentLvr** [comment]
@SuhasBRao, hope you are doing well! 
Are you still interested to your on this issue ?
We were thinking to create a scoring system based on GitHub activity:
- Commits
- Issue created
- PR merged
- File added

So first, I should be great to start with the commits activity and have a list of all contributors scoring by number of commits. 
1 | FlorentLvr | 1000
2 | jravenel | 1000
3 | SushasBRao | 1000
Do you think it is doable ? 🙏

**Comment by SuhasBRao** [comment]
Hi @FlorentLvr, I'm doing awesome, sorry for the delayed response, I have to explore more on Github API's, has this been started if so, It would be helpful if i get some code files.

**Comment by FlorentLvr** [comment]
> Hi @FlorentLvr, I'm doing awesome, sorry for the delayed response, I have to explore more on Github API's, has this been started if so, It would be helpful if i get some code files.

@SuhasBRao! Amazing!
I think you can start by using this template for the commits: https://github.com/jupyter-naas/awesome-notebooks/blob/master/GitHub/GitHub_Get_commits_ranking_from_repository.ipynb
And then try to do the same the issue created, PR merged, file added.
Is that clear for you ? 🙏

**Comment by SuhasBRao** [comment]
Hi @FlorentLvr, Hope you are doing good, The template you shared gave me an idea of how to get the details, I was working to get the number of issues created by a user, I'm able to get an output like this, 

![Screenshot from 2023-01-26 16-53-35](https://user-images.githubusercontent.com/65769327/214824346-251cd15b-bfd3-4543-abe5-771b873edb23.png)

are these details enough or do i need to add any other columns for the dataframe. 
And I think we can do the same with PR as well.

**Comment by jravenel** [comment]
@SuhasBRao we just talked about with core team, we are putting this task in the current iteration starting today and finishing next Thursday. 

Let me know if you want me to clearly define output and the calculation we need to do. I'm thinking of a simple notebook with dataframe we can push to Notion first using Naas Notion driver for the output.

**Comment by SuhasBRao** [comment]
Sure let's work on this. I might need some help with notion and few other things. 🤘😊

**Comment by jravenel** [comment]
Just go for a simple data frame as a first iteration @SuhasBRao the difficult part is to figure out how to get meta data from GitHub project for the Estimate field, rest should be ok but happy to help !

**Comment by SuhasBRao** [comment]
Hi @jravenel, to get the leaderboard, i'm planning to  first get a list of contributors with the details you have mentioned above, right now it looks something like this,

![Screenshot from 2023-01-31 20-24-16](https://user-images.githubusercontent.com/65769327/215794968-ee84132b-c685-4b97-98bc-8162c5d19630.png)

I think once we get all the required fields we need to use the weight you described above to calculate the points based on which we can rank the contributors. 

I'm sharing this to know if i'm going in a proper direction. Please do let me know what you think.

**Comment by jravenel** [comment]
amazing @SuhasBRao don't hesitate to push something then we iterate from that.

**Comment by FlorentLvr** [comment]
> Hi @jravenel, to get the leaderboard, i'm planning to first get a list of contributors with the details you have mentioned above, right now it looks something like this,
> 
> ![Screenshot from 2023-01-31 20-24-16](https://user-images.githubusercontent.com/65769327/215794968-ee84132b-c685-4b97-98bc-8162c5d19630.png)
> 
> I think once we get all the required fields we need to use the weight you described above to calculate the points based on which we can rank the contributors.
> 
> I'm sharing this to know if i'm going in a proper direction. Please do let me know what you think.

Can you add the number of commits as well?

**Comment by SuhasBRao** [comment]
> > Hi @jravenel, to get the leaderboard, i'm planning to first get a list of contributors with the details you have mentioned above, right now it looks something like this,
> > ![Screenshot from 2023-01-31 20-24-16](https://user-images.githubusercontent.com/65769327/215794968-ee84132b-c685-4b97-98bc-8162c5d19630.png)
> > I think once we get all the required fields we need to use the weight you described above to calculate the points based on which we can rank the contributors.
> > I'm sharing this to know if i'm going in a proper direction. Please do let me know what you think.
> 
> Can you add the number of commits as well?

Yes will try to add that as well

**Comment by SuhasBRao** [comment]
Hi @FlorentLvr, I have added two more columns like **issue_pr_comments**, **commits** and **pts**. And i'm trying to calculate points for a contributor. Here's a snapshot of the output.

![Screenshot from 2023-02-01 15-04-46](https://user-images.githubusercontent.com/65769327/216005993-a4402245-b6b5-40db-9b00-65773861cd92.png)

I think now we can have order the df using points. Is this the expected output? Let me know what you think

**Comment by jravenel** [comment]
Putting it to the next iteration.

**Comment by SuhasBRao** [comment]
> Putting it to the next iteration.

So what other columns do we need to add in this iteration .

**Comment by FlorentLvr** [comment]
> > Putting it to the next iteration.
> 
> So what other columns do we need to add in this iteration.

@SuhasBRao, we are good for now. Thank you! Can you open a PR? I would be happy to review your work :)

**Comment by Dr0p42** [comment]
@SuhasBRao @jravenel @FlorentLvr this is nice guys! Looking forward to have a deployed version of this 🚀

**Comment by SuhasBRao** [comment]
> > > Putting it to the next iteration.
> > 
> > 
> > So what other columns do we need to add in this iteration.
> 
> @SuhasBRao, we are good for now. Thank you! Can you open a PR? I would be happy to review your work :)

Sure will create a PR, @Dr0p42  I couldn't work on the push link to the notion database, Can you work on it. I don't have much familiarity with Notion so.

**Comment by srini047** [comment]
> @srini047, can you review this PR and let me know if it's good for you ?

Sure @FlorentLvr 👍
