### ISSUE TITLE
pandasql - Query CSV File Using SQL

### ISSUE THREAD

**Issue by MinuraPunchihewa** [jupyter-naas/awesome-notebooks#1337]
**Describe the problem you are facing**
I want to be able to query my CSV files using SQL.

**Describe the solution you'd like**

- Input: path or URL to the CSV file that I want to query, query to be run
- Model: read the data in the file to a DataFrame, run the provided SQL query
- Output: result of the query as a new DataFrame

Given below is a guide on how pandasql is used,
https://towardsdatascience.com/how-to-run-sql-queries-on-your-pandas-dataframes-with-python-4237ffecc43b

**Comment by MinuraPunchihewa** [comment]
Hey @jravenel, based on our conversation, I have added this issue for querying CSV files using SQL statements through pandasql.

**Comment by jravenel** [comment]
Go ahead
