### ISSUE TITLE
FED - Visualize inflation rate for the past 80 years

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1338]
Asked chatGPT

can you write a python script that connect to the FED open data sources and plot the inflation rate using plotly for the last 80 years?

then

can you split this in 3 parts: input, model, output?

**Comment by Mohwit** [comment]
I will work on this!

**Comment by Mohwit** [comment]
@jravenel @FlorentLvr just one doubt, do I need to create a new folder for FED we should I create new file under plotly?

**Comment by jravenel** [comment]
New FED folder @Mohwit ✊

**Comment by jravenel** [comment]
@FlorentLvr do you think we can use your awesome model to generate the first shot ?
