### ISSUE TITLE
Whatsapp - Create heatmap of activites

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1340]
Following this post : https://www.linkedin.com/feed/update/urn:li:activity:7015938553721307137?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7015938553721307137%2C7016310458919878657%29&replyUrn=urn%3Ali%3Acomment%3A%28activity%3A7015938553721307137%2C7016314364739653632%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287016310458919878657%2Curn%3Ali%3Aactivity%3A7015938553721307137%29&dashReplyUrn=urn%3Ali%3Afsd_comment%3A%287016314364739653632%2Curn%3Ali%3Aactivity%3A7015938553721307137%29

Create a template.

**Comment by jravenel** [comment]
@muhtalhakhan want to investigate on this??

**Comment by muhtalhakhan** [comment]
yeah @jravenel would love it to complete under your guidance.

**Comment by jravenel** [comment]
Cool, @FlorentLvr and myself are adding this to the sprint of this week (from today to next Thursday) then.

**Comment by muhtalhakhan** [comment]
Sure, I am looking into that code right now.

**Comment by FlorentLvr** [comment]
@muhtalhakhan, hope you are doing well! Did you start working on this issue yet ? Let me know if you need some help!

**Comment by muhtalhakhan** [comment]
Hey @FlorentLvr, Yeah I am good, hoping all's well there. I was thinking that do we need to provide chat log for any of the platform?

**Comment by muhtalhakhan** [comment]
Alright, its good to work on it but- I would be needing lots of help as I just saw the process of getting chat logs. 
One would go to the chat or group and then by clicking the menu button can export the chat and will use it as a data source for this heatmap.

**Comment by FlorentLvr** [comment]
> 

Ok, got it! Let's try to extract with python => https://github.com/jupyter-naas/awesome-notebooks/issues/1346
If it's not working, we will create this notebook based on the manual export :)
