### ISSUE TITLE
Twitter - Get Members(Name and Username) of list created by user

### ISSUE THREAD

**Issue by kaushalkrishna2000** [jupyter-naas/awesome-notebooks#1347]
**Describe the problem you are facing**
Get the members of a list of a particular user

**Describe the solution you'd like**

- Input : Bearer_token, UserName of the account
- Model : Custom Function to extract the same
- Output : Print of the data (if the runner wants ) and a dataframe with the details

**Additional context**
None

**Comment by kaushalkrishna2000** [comment]
Hello @FlorentLvr 
Can you include this issue in the backlog and assign me to this issue ?
I had filled the contributor form but it seems that I have not been added yet.

**Comment by kaushalkrishna2000** [comment]
Hello ?

**Comment by FlorentLvr** [comment]
> Hello @FlorentLvr @jravenel @Dr0p42 Can you include this issue in the backlog and assign me to this issue ? I had filled the contributor form but it seems that I have not been added yet.

@kaushalkrishna2000, You should have a received an email now and you should be able to work on this issue :)

Let me know if you need my help! 🙏

**Comment by kaushalkrishna2000** [comment]
Thanks
