### ISSUE TITLE
LinkedIn - Get profile information: Error short description

### ISSUE THREAD

**Issue by JJayasri** [jupyter-naas/awesome-notebooks#1391]
**Describe the bug**

**To Reproduce**
4. See the error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by FlorentLvr** [comment]
Hi @JJayasri, sorry for the late reply. Can you elaborate on this error and fill in the information below? Thank you 🙏

**Comment by FlorentLvr** [comment]
@JJayasri, closing this issue. Please let me know if you encountered this issue again
