### ISSUE TITLE
Python - Replace value in text in a specific paragraph

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1410]
Replace value in specific paragraph of text

**Comment by kaushalkrishna2000** [comment]
Hello @FlorentLvr 

Can I get an example of the same ?

**Comment by FlorentLvr** [comment]
> Hello @FlorentLvr
> 
> Can I get an example of the same?

@kaushalkrishna2000, sure I will create a new issue and assign you today!
