### ISSUE TITLE
pandasql - Query Excel file

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1413]
Query Excel file using pandassql

**Comment by ameygoes** [comment]
Hi, @MinuraPunchihewa are you taking this one? If not, have far have you progressed on this? Can I take this one?

**Comment by FlorentLvr** [comment]
> Hi, @MinuraPunchihewa are you taking this one? If not, have far have you progressed on this? Can I take this one?

Hi @ameygoes! Sure you can take over! :)

**Comment by ameygoes** [comment]
Can you give me some KT( Knowledge Transfer) on this ticket, what needs to
be done? What have you done so far?

Would like to connect eith you on this one.

Amey Sign

**Comment by MinuraPunchihewa** [comment]
Hey @FlorentLvr and @ameygoes,
Sorry for the late reply, but I had already done some work on this before. I've just created a PR.
I will assign this back to myself.
