### ISSUE TITLE
Update Notebooks Meta Data on header

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1430]
As we were talking about it early, I propose to make the following change on all notebooks:
- add "Last updated": this will give information about when was the last time the notebook was edited.

To perform this action, I will create notebook to update all notebooks and then edit the generate_readme.iypnb template on the repos to unforce last updated date everytime a branch is merged.

![image](https://user-images.githubusercontent.com/48032461/219063144-b6a6179b-ae69-4b5f-b54a-6e25ed30cf24.png)

**Comment by FlorentLvr** [comment]
@jravenel, do you agree with the changes

**Comment by Dr0p42** [comment]
> @jravenel, @Dr0p42, do you agree with the changes?

Yes @FlorentLvr I think it's a good idea 👍

**Comment by jravenel** [comment]
Add : 
- Creation Date: 2020-12-05
- Last Update: 2020-12-05

And : 
- Authors: list of people who contributed to the notebook separated with comma.

References should have the same display as the rest of meta data headers (like Description)
