### ISSUE TITLE
Polars - pandas Operations

### ISSUE THREAD

**Issue by MinuraPunchihewa** [jupyter-naas/awesome-notebooks#1434]
Hey @FlorentLvr and @jravenel,
I recently discovered this really cool package for working with DataFrames called Polars. It is described as a blazingly fast DataFrames library implemented in Rust using Apache Arrow Columnar Format as the memory model.

This allows you to process those large volumes of data that is typically quite frustrating to do with pandas.

I thought that this would be a great addition to naas.

I don't really have any templates in mind, but if you guys have any ideas, you can assign the issues to me.

**Comment by jravenel** [comment]
I saw that Polar promo on LinkedIn and I'm also interested to see that @MinuraPunchihewa ✌️

**Comment by FlorentLvr** [comment]
@MinuraPunchihewa, hope you are doing well!
I just created an issue for you to start working on Polars: https://github.com/jupyter-naas/awesome-notebooks/issues/1542

We pre-generated a template using OpenAI and already push it to a branch! Let me know what do you think about our new process 🙏

**Comment by MinuraPunchihewa** [comment]
@FlorentLvr Sure thing, I will have a look.
