### ISSUE TITLE
WAQI - Get Daily Air Quality Data for a city

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1477]
This notebook will demonstrate how to use the WAQI API to get daily air quality data for a city.

**Comment by jravenel** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [1477-waqi-get-daily-air-quality-data-for-a-city](https://github.com/jupyter-naas/awesome-notebooks/tree/1477-waqi-get-daily-air-quality-data-for-a-city)
- Notebook: [WAQI/WAQI_Get_Daily_Air_Quality_Data_for_a_city.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/1477-waqi-get-daily-air-quality-data-for-a-city/WAQI/WAQI_Get_Daily_Air_Quality_Data_for_a_city.ipynb)

**Comment by kaushalkrishna2000** [comment]
Hello @jravenel  Can I take up on the issue ?

**Comment by jravenel** [comment]
> Hello @jravenel Can I take up on the issue ?

I have added comment on the PR _ resolution is already on the way. We just need review and confirmation it works fine.

**Comment by kaushalkrishna2000** [comment]
Sure .
