### ISSUE TITLE
LinkedIn - Get My Last 30 days posts stats

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1479]
This notebook will show how to get the stats of the last 30 days posts on LinkedIn.

**Comment by jravenel** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [1479-linkedin-get-my-last-30-days-posts-stats](https://github.com/jupyter-naas/awesome-notebooks/tree/1479-linkedin-get-my-last-30-days-posts-stats)
- Notebook: [LinkedIn/LinkedIn_Get_My_Last_30_days_posts_stats.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/1479-linkedin-get-my-last-30-days-posts-stats/LinkedIn/LinkedIn_Get_My_Last_30_days_posts_stats.ipynb)

**Comment by FlorentLvr** [comment]
Template: https://github.com/jupyter-naas/awesome-notebooks/blob/master/LinkedIn/LinkedIn_Get_stats_from_post.ipynb
