### ISSUE TITLE
PyTorch - Create daylight image from dark image

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#150]
As a user, I want to improve the quality of a dark image to daylight quality. 

Task: 
- create folder "Pytorch" in awesome-notebooks 
- create notebook respecting the norm (title, input,  model, output)
- create branch and push

**Comment by jravenel** [comment]
@haresh121 can we help you finish this task?

**Comment by jravenel** [comment]
Hello @haresh121, without answer from your end, I will move the card back to backlog. Feel free to reach out when you can jump again. 🙏

**Comment by tdubon** [comment]
Hi @jravenel I can work on this. Please assign me to the ticket.

**Comment by jravenel** [comment]
Hey @tdubon this is on hold until we provide GPU :) coming soon.

**Comment by jravenel** [comment]
FYI @tdubon @haresh121 Closing as we now longer prioritize computer vision, too resource intensive no direct link to a business problem.
