### ISSUE TITLE
Bitly - Get Metrics for a Bitlink by Device Type

### ISSUE THREAD

**Issue by FlorentRvl** [jupyter-naas/awesome-notebooks#1510]
This notebook will show how to use the Bitly API to get metrics for a Bitlink by device type.

**Comment by FlorentLvr** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [1510-bitly-get-metrics-for-a-bitlink-by-device-type](https://github.com/jupyter-naas/awesome-notebooks/tree/1510-bitly-get-metrics-for-a-bitlink-by-device-type)
- Notebook: [Bitly/Bitly_Get_Metrics_for_a_Bitlink_by_Device_Type.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/1510-bitly-get-metrics-for-a-bitlink-by-device-type/Bitly/Bitly_Get_Metrics_for_a_Bitlink_by_Device_Type.ipynb)
