### ISSUE TITLE
gTTS - Save Text to Speech to MP3

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1523]
This notebook will demonstrate how to use the gTTS library to save text to speech as an MP3 file.

**Comment by FlorentLvr** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [1523-gtts-save-text-to-speech-to-mp3](https://github.com/jupyter-naas/awesome-notebooks/tree/1523-gtts-save-text-to-speech-to-mp3)
- Notebook: [gTTS/gTTS_Save_Text_to_Speech_to_MP3.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/1523-gtts-save-text-to-speech-to-mp3/gTTS/gTTS_Save_Text_to_Speech_to_MP3.ipynb)

**Comment by FlorentLvr** [comment]
@srini047, as you used it on your issue OpenAI Text to Speech, I created this template for you. Can you check if the PR is correct 🙏

**Comment by srini047** [comment]
> @srini047, as you used it on your issue OpenAI Text to Speech, I created this template for you. Can you check if the PR is correct 🙏

Sure👍
