### ISSUE TITLE
PyGWalker - Analyze Pandas dataframe

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1540]
This notebook will demonstrate how to analyze a Pandas dataframe in Jupyter using a Tableau-style interface.

Sources: 
- https://www.linkedin.com/posts/avi-chawla_python-datascience-pandas-activity-7036283018474364928-duoC?utm_source=share&utm_medium=member_desktop
- https://github.com/ChawlaAvi/Daily-Dose-of-Data-Science/blob/main/Pandas/Pandas-With-Tableau.ipynb

**Comment by FlorentLvr** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [1540-pygwalker-analyze-pandas-dataframe](https://github.com/jupyter-naas/awesome-notebooks/tree/1540-pygwalker-analyze-pandas-dataframe)
- Notebook: [PyGWalker/PyGWalker_Analyze_Pandas_dataframe.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/1540-pygwalker-analyze-pandas-dataframe/PyGWalker/PyGWalker_Analyze_Pandas_dataframe.ipynb)

**Comment by aybruhm** [comment]
Awesome! Let's gooooooooo. 👏🏾
