### ISSUE TITLE
Python - Read pickle file

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1564]
This notebook will show how to read a pickle file in Python.

**Comment by FlorentLvr** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [1564-python-read-pickle-file](https://github.com/jupyter-naas/awesome-notebooks/tree/1564-python-read-pickle-file)
- Notebook: [Python/Python_Read_pickle_file.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/1564-python-read-pickle-file/Python/Python_Read_pickle_file.ipynb)

**Comment by kaushalkrishna2000** [comment]
Cool!
