### ISSUE TITLE
Formant - Automate robot network reporting via email 

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1575]
**Describe the problem you are facing**
As a Formant platform user, I want to automatically get an email report showing a vertical barchart of download/upload data of the past 12 hours everyday at 9am.

**Describe the solution you'd like**

- Input 
FORMANT_API
ROBOT_ID
SCHEDULER_CRON
EMAIL

- Model 
Get data 
Transform data into dataframe 
Create vertical barchart and generate naas asset for the graph 
Create email 

- Output
Show email 
Send email 

**Additional resources**
We can use this template to build a similar worflow : https://github.com/jupyter-naas/awesome-notebooks/blob/master/YahooFinance/YahooFinance_Send_daily_prediction_to_Email.ipynb
and this template to create the graph: https://github.com/jupyter-naas/awesome-notebooks/blob/master/Plotly/Plotly_Create_Vertical_Barchart_group.ipynb

**Comment by jravenel** [comment]
@tanim-islm let's get this merged :)

**Comment by tanim-islm** [comment]
@jravenel as per the link above, this is the issue for our notebook. The next step in the doc is to assign ourselves, but we are not able to do that here..

**Comment by tanim-islm** [comment]
So we need some assistance branching off master so we can add our code and submit the PR.

**Comment by jravenel** [comment]
Now it's merge @tanim-islm we should do a promo about it.
