### ISSUE TITLE
Template analytics not working and panel image of contributors to be added

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1578]
Following our dicusssion @srini047 for the picture of contributors: 

- Rename "Support us on social media" by "Support us" 
- Add a paragraph Saying "We are a community of Notebook and data lovers from all over the world"
- Then below this add your snippet with the image of all contributors 
`<a href = "https://github.com/jupyter-naas/awesome-notebooks/graphs/contributors">
  <img src = "https://contrib.rocks/image?repo=jupyter-naas/awesome-notebooks"/>
</a>`
- Then change the following sentence to "We are committed to sharing templates and giving shout outs to the contributors on our social media platforms, folllow us on:"

Also the template anlaytics part is not showing anything. I don't know if you or @FlorentLvr can try fix this.
<img width="246" alt="2023-03-21_10h12_02" src="https://user-images.githubusercontent.com/21052349/226561826-4f010fdb-b65a-4c22-b28d-21c23e4ec93b.png">

**Comment by srini047** [comment]
> cc @FlorentLvr maybe you can help on the template analytics part.

@jravenel @FlorentLvr I can view the templates from my end.

<img width="1799" alt="Screenshot 2023-03-21 at 2 44 34 PM" src="https://user-images.githubusercontent.com/81156510/226562536-461d5cea-ba45-41d2-92eb-20c3f469d2fb.png">

**Comment by jravenel** [comment]
@srini047 the chart does not look up to date.

**Comment by srini047** [comment]
> @srini047 the chart does not look up to date.

Yes. That's correct!
