### ISSUE TITLE
Google Calendar - List calendars

### ISSUE THREAD

**Issue by FlorentRvl** [jupyter-naas/awesome-notebooks#1596]
This notebook will demonstrate how to use the Google Calendar API to list the calendars on the user's calendar list.

**Comment by FlorentLvr** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [1596-google-calendar-list-calendars](https://github.com/jupyter-naas/awesome-notebooks/tree/1596-google-calendar-list-calendars)
- Notebook: [Google%20Calendar/Google_Calendar_List_calendars.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/1596-google-calendar-list-calendars/Google%20Calendar/Google_Calendar_List_calendars.ipynb)
