### ISSUE TITLE
Python - Clean your download folder

### ISSUE THREAD

**Issue by Mohwit** [jupyter-naas/awesome-notebooks#1606]
This template will go through your download folder and check each file last modification time, and if it's been more than 30 days it will move those file to new folder say 'files_to_delete'. So, that user can review that folder for important file and then delete it.

Solution: A python script can help to achieve the same.

Input: Path of download folder

Model: Python script

Output: Files to delete folder

**Comment by devgenix** [comment]
Hi, can I take this up?

**Comment by jravenel** [comment]
@devgenix I think @Mohwit is on it. We have more templates to do if you want.
