### ISSUE TITLE
Vizzu - transform docs examples in Naas templates

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1608]
As a data analyst, I want to use Vizzu and want to run notebook templates as fast as possible to gain conviction or not if the library fit my use case. 

Batch 1 → Static charts : 

1. [Column Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/02_C_R_column/)
2. [Grouped Column Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/03_C_R_grouped_column_negative/)
3. [Stacked Column Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/04_C_R_stacked_column/)
4. [Splitted Column Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/05_C_R_splitted_column/)
5. [Percentage Column Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/06_C_R_percentage_column/)
6. [Waterfall Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/08_C_R_waterfall/)
7. [Stacked Mekko Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/09_C_R_stacked_mekko/)
8. [Marimekko Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/10_C_R_marimekko/)
9. [Bar Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/13_C_R_bar_negative/)
10. [Grouped Bar Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/14_C_R_grouped_bar_negative/)
11. [Stacked Bar Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/15_C_R_stacked_bar/)
12. [Splitted Bar Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/16_C_R_splitted_bar/)
13. [Percentage Bar Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/17_C_R_percentage_bar/)
14. [Lollipop Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/20_C_C_lollipop_chart/)
15. [Scatter Plot](https://ipyvizzu.vizzuhq.com/latest/examples/presets/22_C_C_scatter/)
16. [Bubble Plot](https://ipyvizzu.vizzuhq.com/latest/examples/presets/24_C_C_bubbleplot/)
17. [Area Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/27_C_A_area_negative/)
18. [Stacked Area Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/28_C_A_stacked_area/)
19. [Percentage Area Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/29_C_A_percentage_area/)
20. [Splitted Area Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/31_C_A_splitted_area/)
21. [Stream Graph](https://ipyvizzu.vizzuhq.com/latest/examples/presets/32_C_A_stream/)
22. [Vertical Stream Graph](https://ipyvizzu.vizzuhq.com/latest/examples/presets/33_C_A_vertical_stream/)
23. [Violin Graph](https://ipyvizzu.vizzuhq.com/latest/examples/presets/34_C_A_violin/)
24. [Vertical Violin Graph](https://ipyvizzu.vizzuhq.com/latest/examples/presets/35_C_A_vertical_violin/)
25. [Line Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/38_C_L_line/)
26. [Vertical Line Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/39_C_L_vertical_line/)
27. [Pie Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/40_P_R_pie/)
28. [Polar Column Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/42_P_R_polar_column/)
29. [Polar Stacked Column Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/42a_P_R_polar_stacked_column/)
30. [Variable Radius Pie Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/44_P_R_variable_radius_pie_chart/)
31. [Radial Bar Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/49_P_R_radial_bar/)
32. [Radial Stacked Bar Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/50_P_R_radial_stacked_bar/)
33. [Donut Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/51_P_R_donut/)
34. [Nested Donut Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/52_P_R_nested_donut/)
35. [Polar Scatter Plot](https://ipyvizzu.vizzuhq.com/latest/examples/presets/53_P_C_polar_scatter/)
36. [Polar Line Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/56_P_A_polar_line/)
37. [Treemap](https://ipyvizzu.vizzuhq.com/latest/examples/presets/58_W_R_treemap/)
38. [Stacked Treemap](https://ipyvizzu.vizzuhq.com/latest/examples/presets/59_W_R_stacked_treemap/)
39. [Heatmap](https://ipyvizzu.vizzuhq.com/latest/examples/presets/60_W_R_heatmap/)
40. [Bubble Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/61_W_R_bubble_chart/)
41. [Stacked Bubble Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/62_W_R_stacked_bubble/)

**Comment by jravenel** [comment]
@petervidos

Here is the current status: blocked on HTML rendering and chart display for [Grouped Column Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/03_C_R_grouped_column_negative/)
[Stacked Column Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/04_C_R_stacked_column/)

Video: https://www.linkedin.com/safety/go?url=https%3A%2F%2Fwww.loom.com%2Fshare%2F79c6201ab02a4fcdb79ca252f6b92072&trk=flagship-messaging-web&messageThreadUrn=urn%3Ali%3AmessagingThread%3A2-YzM5ZTg0NzMtZWYyYS00MGYyLTlmMTUtOTE2NDk4YmY1NDRiXzAxMw%3D%3D&lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3BL8pThp0ZRECdwAzFqzge7A%3D%3D

**Comment by jravenel** [comment]
@petervidos

Here is the current status: blocked on HTML rendering and chart display for [Grouped Column Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/03_C_R_grouped_column_negative/)
[Stacked Column Chart](https://ipyvizzu.vizzuhq.com/latest/examples/presets/04_C_R_stacked_column/)

Video: https://www.linkedin.com/safety/go?url=https%3A%2F%2Fwww.loom.com%2Fshare%2F79c6201ab02a4fcdb79ca252f6b92072&trk=flagship-messaging-web&messageThreadUrn=urn%3Ali%3AmessagingThread%3A2-YzM5ZTg0NzMtZWYyYS00MGYyLTlmMTUtOTE2NDk4YmY1NDRiXzAxMw%3D%3D&lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3BL8pThp0ZRECdwAzFqzge7A%3D%3D

**Comment by srini047** [comment]
@jravenel I would like to work on a few of them.
Let me take 4 create a PR, then would like to contribute to more based on the PR review.

Does that sound good @jravenel ?

**Comment by jravenel** [comment]
Let's wait before I have feedback from @petervidos on how to get HTML file to expose it in Naas asset. We will talk about it in community call.

**Comment by srini047** [comment]
> Let's wait before I have feedback from @petervidos on how to get HTML file to expose it in Naas asset. We will talk about it in community call.

Sure. Makes sense.

**Comment by veghdev** [comment]
Hi @jravenel ,
I've checked the [first](https://github.com/jupyter-naas/awesome-notebooks/blob/98e640aeea6e4164660abd199d0658bd4da17660/Vizzu/Vizzu_Create_Column_Chart.ipynb) notebook,

Currently in manual display mode, the chart can only be displayed once, but we plan to change this in the future.
With the following workaround (using a private variable and function), you can skip this problem and export the html string:

```python
chart._showed = False
rawhtml = chart._repr_html_()

with open("Vizzu_Create_column_chart.html", "w", encoding="utf8") as file_desc:
    file_desc.write(rawhtml)
```

**Comment by jravenel** [comment]
> Hi @jravenel , I've checked the [first](https://github.com/jupyter-naas/awesome-notebooks/blob/98e640aeea6e4164660abd199d0658bd4da17660/Vizzu/Vizzu_Create_Column_Chart.ipynb) notebook,
> 
> Currently in manual display mode, the chart can only be displayed once, but we plan to change this in the future. With the following workaround (using a private variable and function), you can skip this problem and export the html string:
> 
> ```python
> chart._showed = False
> rawhtml = chart._repr_html_()
> 
> with open("Vizzu_Create_column_chart.html", "w", encoding="utf8") as file_desc:
>     file_desc.write(rawhtml)
> ```

@veghdev thanks, it worked on Column chart but not on the Grouped column chart, any reason you can see? 
We have arranged the Column chart code to intergrate it with Naas asset features, it enables any vizzu chart to be shared via a URL . 

cc @petervidos

**Comment by veghdev** [comment]
Hi @jravenel, you redefine the chart in the "Generate chart" cell, just remove the second one.

```pyhton
# initialize Chart
chart = Chart(width="640px", height="360px", display="manual")
...
# add config to Chart
chart = Chart()
```

**Comment by jravenel** [comment]
Oh ok @veghdev thanks will try it out.

**Comment by jravenel** [comment]
![vizzu+naas](https://user-images.githubusercontent.com/21052349/229313269-cb024432-0b89-4cdb-9763-61e240ff4954.gif)

@veghdev @petervidos I think we are on track :) 
The Naas asset formulas to share Vizzu graph is working good now. I'll extend this to the other charts

→ One question on the waterfall, can we do steps like this? 
<img width="800" alt="Screenshot 2023-04-01 at 22 43 34" src="https://user-images.githubusercontent.com/21052349/229313225-ae1d3675-a434-4604-880d-5e9d9cb55070.png">
