### ISSUE TITLE
k-NN - Find the stock with closest performance

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#161]
Input:
List of stocks data 

Model:
Find the stock with the closest performance attribute

Output:
Graph of clusters (with each cluster having a different color)

Resources / Inspiration: 
https://towardsdatascience.com/in-12-minutes-stocks-analysis-with-pandas-and-scikit-learn-a8d8a7b50ee7

**Comment by MoomalQ** [comment]
hello @jravenel  I would like to work on this Issue.

**Comment by jravenel** [comment]
Hey @MoomalQ, I added you to the contributor's group, you can start working on it. 
The idea is to adap the current article in medium to the Naas framework (input/.model./.output)
OK for you?

Reminder of the steps: 

Step 1: Open free account on Naas.ai
Step 2: Clone awesome-notebooks repo
Step 3:  Change status of this Issue to "In progress" so we can know you are working on it
Step 4: Create new branch with a short name of the issue (ex: “gsheet-notion”)
Step 5: Create folder named with the source tool (if it does not already exist in the awesome-notebooks folder), and adapt notebook template to the current use case.
Step 6:  Once you are happy with the result, commit to the branch
Step 7: Open a pull request and tag me as a reviewer with a little comment on what you have done, but most of the explanations should be in the notebook itself
Step 8:  Change status of this Issue to "Review" so we can know a review is pending
Step 9:  Link the PR to this issue for tracking in the backlog
Step 10:  Expect a feedback and merge in the next 48h-72h 👍 

PS. if you need more credits on your naas, just ask us in private slack message.

Feel free to ask here any question you may have.

**Comment by MoomalQ** [comment]
Hello ! I was away for a few days.. I will hopefully put something up in a couple of days.

**Comment by jravenel** [comment]
Hey @MoomalQ do you need help on this? We can sync if you want.

**Comment by raiharshit47** [comment]
Hey @jravenel I would like to work on this issue

**Comment by Valpiquard** [comment]
Hi @jravenel @FlorentLvr @Dr0p42 , 

I just had a conversation with @raiharshit47 , he is available to take this issue and work on it since it seems to be frozen. 

Can you confirm he can start working on it ?

**Comment by jravenel** [comment]
> Hello ! I was away for a few days.. I will hopefully put something up in a couple of days.

Hey @MoomalQ, do you think @raiharshit47 can proceed or do you have a PR to propose soon?

**Comment by FlorentLvr** [comment]
Hi @raiharshit47 , @MoomalQ !
I hope you are doing well.
Did you advance on this issue ? Need any help ? 
Let us know if we can do something for you 😇

**Comment by Dr0p42** [comment]
Hello @abhinav3398, as requested you are assigned to this issue now.

This is the branch you must use: https://github.com/jupyter-naas/awesome-notebooks/tree/161-k-nn-find-the-stock-with-closest-performance

Here is the [Code contributo journey](https://www.notion.so/naas-official/Code-contributor-journey-164779502e2a4ca5950d63eea7a2d39f) in case you need it.

I will move the card to `In Progress` in the [Roadmap](https://github.com/orgs/jupyter-naas/projects/4) if it's fine with you.
