### ISSUE TITLE
Clockify - Get all projects on workspace

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1643]
This notebook will show how to get all projects on a workspace using the Clockify API.

**Comment by FlorentLvr** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [1643-clockify-get-all-projects-on-workspace](https://github.com/jupyter-naas/awesome-notebooks/tree/1643-clockify-get-all-projects-on-workspace)
- Notebook: [Clockify/Clockify_Get_all_projects_on_workspace.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/1643-clockify-get-all-projects-on-workspace/Clockify/Clockify_Get_all_projects_on_workspace.ipynb)

**Comment by abhigyan631** [comment]
Hi,
  Is this issue still open or closed? Thank you.

**Comment by FlorentLvr** [comment]
> Hi, Is this issue still open or closed? Thank you.

Hi @abhigyan631, it is still open! You can take over. :)
Have you ever worked with Clockify before?

**Comment by abhigyan631** [comment]
I have not worked on Clockify before but I can look into the project and do some tests on the notebook provided. Does it sound fair to you? Thank you.

**Comment by FlorentLvr** [comment]
> I have not worked on Clockify before but I can look into the project and do some tests on the notebook provided. Does it sound fair to you? Thank you.

Since we are using Clockify internally, I will handle this issue. Testing and result verification will be easier for us this way. I'll look for a more suitable issue for you and get in touch with you on Slack to discuss it further. Would it be okay with you to continue our conversation there?

**Comment by abhigyan631** [comment]
Yes, I will ping you on Slack then.
