### ISSUE TITLE
Naas Dashboard - Financial Consolidation: Error on import

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1649]
**Describe the bug**
An error message occured at importing librairies.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
naas 2.10.2 requires MarkupSafe==2.0.1, but you have markupsafe 2.1.2 which is incompatible.
naas 2.10.2 requires pyvis==0.3.0, but you have pyvis 0.2.1 which is incompatible.

**To Reproduce**
Run the notebook 

**Expected behavior**
Should go till the end and show a dashboard

**Screenshots**
![Screenshot 2023-04-07 at 21 32 22](https://user-images.githubusercontent.com/21052349/230666662-0f2e66c1-1cdf-410c-9ca0-28ce36f90baa.png)

**Comment by jravenel** [comment]
Can you reproduce @FlorentLvr ? Can you advise on how to fix? Thanks

**Comment by FlorentLvr** [comment]
> Can you reproduce @FlorentLvr ? Can you advise on how to fix? Thanks

@jravenel, TY for reaching out. I can not reproduce this error on my naas. It tooks 9 min to install all package required but i can access the dashboard at the end. I suggest you uninstall all your package and try it again: https://www.notion.so/naas-official/How-to-reset-user-installs-of-pip-6ba49314d1fd41e3b17053a5f2142838?pvs=4

<img width="598" alt="image" src="https://user-images.githubusercontent.com/48032461/230864916-0d230a2f-6350-4065-9230-6d2ca05aa408.png">

<img width="626" alt="image" src="https://user-images.githubusercontent.com/48032461/230864995-764adac4-3054-41e0-8a20-a8677c4dd564.png">

**Comment by FlorentLvr** [comment]
@jravenel, just checking out. Is it working now? Have you tried to remove your install ?
