### ISSUE TITLE
Data Product Framework - Convert template to data product

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1652]
@jravenel  @Dr0p42 
As we discussed together, we will first create a a link in each notebook header to download the template to "Naas - Create naas data product"
<img width="518" alt="image" src="https://user-images.githubusercontent.com/48032461/231114148-59841c30-00ca-4a02-a953-3288f6070e3e.png">

**Comment by jravenel** [comment]
Yes @FlorentLvr but not sure to put it green as it will be hard to read on light mode.

**Comment by FlorentLvr** [comment]
@jravenel >> https://www.notion.so/naas-official/Start-Your-Data-Product-232d1feccb1b49e7a21ff5da6ed6e2a1?pvs=4
