### ISSUE TITLE
Python - Download ZIP from URL

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1657]
This notebook will show how to download a ZIP file from a URL using urllib.request.

**Comment by FlorentLvr** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [1657-python-download-zip-from-url](https://github.com/jupyter-naas/awesome-notebooks/tree/1657-python-download-zip-from-url)
- Notebook: [Python/Python_Download_ZIP_from_URL.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/1657-python-download-zip-from-url/Python/Python_Download_ZIP_from_URL.ipynb)

**Comment by Mukhtarmid** [comment]
@FlorentLvr I would to give it a try this, could you please assign it to me.

**Comment by FlorentLvr** [comment]
> @FlorentLvr I would to give it a try this, could you please assign it to me.

Sure! You can update your name as Author and review if the code works fine 😁🙏

**Comment by Mukhtarmid** [comment]
@FlorentLvr Done with the notebook, but having some issues while pushing. Need a helping hand over here!

**Comment by FlorentLvr** [comment]
> @FlorentLvr Done with the notebook, but having some issues while pushing. Need a helping hand over here!

@Mukhtarmid, sure! Can you elaborate on your error? With a screen shot maybe?

**Comment by FlorentLvr** [comment]
> > @FlorentLvr Done with the notebook, but having some issues while pushing. Need a helping hand over here!
> 
> @Mukhtarmid, sure! You should have a receive an invitation (email) to join the open source contributors team. Please accept it and try again to push your change. 🙏 
Let me know if you are still stuck!

**Comment by FlorentLvr** [comment]
@Mukhtarmid, did you receive the invitation ? Do you need my help on something?

**Comment by Mukhtarmid** [comment]
@FlorentLvr, yup I did received an invitation. I'm bit busy and having some issues. Need your time in next week.

**Comment by FlorentLvr** [comment]
> @FlorentLvr, yup I did received an invitation. I'm bit busy and having some issues. Need your time in next week.

@Mukhtarmid, no pb! Once you will accept the invitation you will be able to push your change and I could review your work! Please tag me on the PR and I will check. Thank you 🙏

**Comment by Mukhtarmid** [comment]
@FlorentLvr could you please contact me on mukhtarmid@gmail.com. I'm having branching issue.

**Comment by FlorentLvr** [comment]
> @FlorentLvr could you please contact me on [mukhtarmid@gmail.com](mailto:mukhtarmid@gmail.com). I'm having branching issue.

Hello @Mukhtarmid! I see you accepted our invitation. It should be ok by now. 
What kind of issue do you have? Can you be more specific and add some screenshots?
Did you create a [personal access token](https://github.com/settings/tokens) and try to push your work? (Step 6: https://github.com/jupyter-naas/awesome-notebooks#step-by-step-process).
I am available on our [Slack](https://join.slack.com/t/naas-club/shared_invite/zt-1tql56o07-LJNO_~~HQ_w4x1pYVlHBTQ) if you want to talk directly. 🙏
