### ISSUE TITLE
Trello - List Boards

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1665]
This notebook would allow you to retrieve a list of all the boards that you have access to in Trello. You could then use this information to perform further actions on the boards, such as listing the cards or updating their details.

**Comment by jravenel** [comment]
@asnamaqba ready to take this on?

**Comment by FlorentLvr** [comment]
@Benjifilly, can you have a look at this one?

**Comment by Benjifilly** [comment]
hey, @FlorentLvr i did, it take a look and tell me if you wanna add something, i tried to add listing card but it was messy and not really useful

**Comment by Benjifilly** [comment]
Ready to review

**Comment by FlorentLvr** [comment]
@Benjifilly, i created a function to get Trello token more easily. Can you please test it and let me know if it's clear for you? If it is good! You can merge this PR! Great job 👍
