### ISSUE TITLE
Notion - Get database

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#167]
Display as a data frame, the same database as the one I can see when I connect to Notion (without the formatting properties)

Input: 
- API_TOKEN = "***********"
- DATABASE_URL = full URL where the database is located to facilitate UX 

Model: 
create a function to get the database = get_database

Output: 
Display df

**Comment by FlorentLvr** [comment]
@axelearning , could you please push your code in a branch from master ? Thank you.

**Comment by axelearning** [comment]
@FlorentLvr @jravenel work done guys ! Need to make some refactoring but it's working on my machine
