### ISSUE TITLE
CICD - Push template.json to Algolia API

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1677]
Everytime a PR is merged, we need to send the template.json to Algolia

**Comment by srini047** [comment]
@FlorentLvr Any updates on this. Actually I find the latest templated being able to be searched in the Naas search feature of the workspace. So is this issue still relevant?

**Comment by FlorentLvr** [comment]
@srini047, thanks for the reminder. This issue was done 2 weeks ago :)
