### ISSUE TITLE
Pydub - Convert audio file M4A to MP3

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1681]
This notebook would allow you to transform an audio file from M4A to MP3. It can be further used by people who want to use their Iphone voice recording mémos file and generate transcripts with AI.

**Comment by jravenel** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [1681-pydub-convert-audio-file-m4a-to-mp3](https://github.com/jupyter-naas/awesome-notebooks/tree/1681-pydub-convert-audio-file-m4a-to-mp3)
- Notebook: [Pydub/Pydub_Convert_audio_file_M4A_to_MP3.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/1681-pydub-convert-audio-file-m4a-to-mp3/Pydub/Pydub_Convert_audio_file_M4A_to_MP3.ipynb)

**Comment by FlorentLvr** [comment]
@Benjifilly, can you have a look at this issue?
