### ISSUE TITLE
Notion - Create record in database

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#169]
Create record in database with page data

Input:
- API_TOKEN = "***********"
- DATABASE_URL = full URL where the DB is located to facilitate UX

Model:
- create a function to create record properties
- create a function to create record blocks 

Output:
- "✅ Record successfully sent to Notion"

**Comment by axelearning** [comment]
@FlorentLvr are we done with this PR ?

**Comment by jravenel** [comment]
As discussed this morning, to close this PR let's try to add the embed function. @axelearning 👍👍

**Comment by axelearning** [comment]
> As discussed this morning, to close this PR let's try to add the embed function. @axelearning 👍👍

@jravenel i can't handle it for any type of file this work with figma file but not with maps !
 **Can you send me the plotly url i will try with it** 

<img width="512" alt="Screen Shot 2021-09-08 at 12 42 48 PM" src="https://user-images.githubusercontent.com/55969238/132477611-76f14579-a349-45c8-9fc9-f8ef2266c565.png">

**Comment by jravenel** [comment]
@axelearning we followed on this subject in private message. 
=> Conclusion: we need to have a pre-built page so that the embed can be a replace and not a create (it will therefore keep the same format)

**Comment by axelearning** [comment]
A last note, for the moment Notion API can't update embed file ! 

I keep you updated in private about the changelog 🤝

**Comment by jravenel** [comment]
Ok ok, but at least we can create it and change the display manually. That's ok for me.
