### ISSUE TITLE
Azure Machine Learning - Univariate Timeseries Inference

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1726]
This notebook provides an example of how to use Azure Machine Learning to perform univariate timeseries inference. It is useful for organizations that need to analyze and predict future trends in their data.

**Comment by FlorentLvr** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [1726-azure-machine-learning-univariate-timeseries-inference](https://github.com/jupyter-naas/awesome-notebooks/tree/1726-azure-machine-learning-univariate-timeseries-inference)
- Notebook: [Azure%20Machine%20Learning/Azure_Machine_Learning_Univariate_Timeseries_Inference.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/1726-azure-machine-learning-univariate-timeseries-inference/Azure%20Machine%20Learning/Azure_Machine_Learning_Univariate_Timeseries_Inference.ipynb)

**Comment by jravenel** [comment]
hey @tobiaszwingmann do you think you will be able to work on it for this sprint ending may 31? thanks

**Comment by tobiaszwingmann** [comment]
I’ll try. We have three sick kids at home for the past 3 weeks. it’s too crazy. On 25. May 2023, at 16:50, Jeremy Ravenel ***@***.***> wrote:﻿
hey @tobiaszwingmann do you think you will be able to work on it for this sprint ending may 31? thanks

**Comment by tobiaszwingmann** [comment]
@jravenel Please check the upload
