### ISSUE TITLE
Streamlit - Create prediction app: Error short description

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1804]
**Describe the bug**
When I run the notebook
<img width="1540" alt="Screenshot 2023-05-25 at 16 58 52" src="https://github.com/jupyter-naas/awesome-notebooks/assets/21052349/bad9da7a-e20e-476c-8bee-6e4e81b26af1">
 I have an error page :

**Comment by jravenel** [comment]
cc @Dr0p42 following discussion with Maarten Breddels (https://www.linkedin.com/in/maartenbreddels/) he will be happy to contribute on the basis of this Streamlit template to do it for Solara (he is the creator). 

That would be awesome if you can help debug!

**Comment by maartenbreddels** [comment]
Yeah, subscribed here, so if this is fixed I can open a PR for a demo notebook / template.

**Comment by FlorentLvr** [comment]
Fixed
