### ISSUE TITLE
LinkedIn - Add legal mention in templates 

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1812]
@jravenel 
This code is in no way affiliated with, authorized, maintained, sponsored or endorsed by Linkedin or any of its affiliates or subsidiaries. It uses an independent and unofficial API. Use at your own risk.

This project violates Linkedin's User Agreement Section 8.2, and because of this, Linkedin may (and will) temporarily or permanently ban your account. We are not responsible for your account being banned.

**Comment by FlorentLvr** [comment]
@jravenel, here below an example in a notebook. Does it sound good for you?
![image](https://github.com/jupyter-naas/awesome-notebooks/assets/48032461/0faa2ed5-2ec8-4901-a6e2-9b8f4b0fff91)

**Comment by jravenel** [comment]
yes!
