### ISSUE TITLE
YahooFinance - Generate AI powered chat plugin

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1819]
This notebook will generate an AI powered chat plugin for YahooFinance. It will use Python to access the YahooFinance API and create a plugin that can be used to answer questions about stocks and financial markets.

**Comment by FlorentLvr** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [1819-yahoofinance-generate-ai-powered-chat-plugin](https://github.com/jupyter-naas/awesome-notebooks/tree/1819-yahoofinance-generate-ai-powered-chat-plugin)
- Notebook: [YahooFinance/YahooFinance_Generate_AI_powered_chat_plugin.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/1819-yahoofinance-generate-ai-powered-chat-plugin/YahooFinance/YahooFinance_Generate_AI_powered_chat_plugin.ipynb)

**Comment by FlorentLvr** [comment]
@jravenel, could you please provide me the json structure + prompt and completion expected for each elements ? 🙏

**Comment by jravenel** [comment]
json =
meta: 
  title: my finance assistant 
  repo:
  model:
  temperature:
  max_tokens:

data:
 csv:
  prompt:
  completion:
  raw_data: 
    col1
    col2
 png:
 html:
 

Does that makes sense @FlorentLvr , @Dr0p42 ?

**Comment by FlorentLvr** [comment]
@jravenel
Name: Yahoo_Chat_about_a_stock_trend.ipynb

Questions:
- What's the currents stock trend?
- When did the 20MA crossed the 50MA?

Output:
json with asset to integrate with MyChatGPT
