### ISSUE TITLE
Advertools - Audit robots txt and xml sitemap issues: Minor changes

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1821]
Minor changes:
- add a link to it in the references section:
[advertools XML sitemaps](https://advertools.readthedocs.io/en/master/advertools.sitemaps.html)

- Remove the following lines:
```
# just for testing:
robotstxt_url = "https://www.google.com/robots.txt"
```

- Split into two cells, the cell that starts with # Get users agent, with the first cell being:
```
# Get users agent
user_agents = robots_df[robots_df['directive'].str.contains('user-agent', case=False)]['content']
user_agents
```

**Comment by FlorentLvr** [comment]
@eliasdabbas, just created a new issue and branch regarding your comment on the PR. :)

**Comment by eliasdabbas** [comment]
Thanks!

Just made a pull request (sorry for the minor merge conflicts which I thought I already resolved!) Happy to resolve them whichever way you want.

https://github.com/jupyter-naas/awesome-notebooks/pull/1822
