### ISSUE TITLE
LangChain - CSV Agent

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1835]
This notebook shows how to use agents to interact with a csv. It is mostly optimized for question answering.

**Comment by FlorentLvr** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [1835-langchain-csv-agent](https://github.com/jupyter-naas/awesome-notebooks/tree/1835-langchain-csv-agent)
- Notebook: [LangChain/LangChain_CSV_Agent.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/1835-langchain-csv-agent/LangChain/LangChain_CSV_Agent.ipynb)

**Comment by FlorentLvr** [comment]
@Mukhtarmid, just created a new issue for you if you are interested to work on LangChain, if not let me know. You can use the template "LangChain_Pandas_Dataframe_Agent.ipynb" as an example and find a CSV URL and a good question to make sure the template will work in any case 🙏

**Comment by jravenel** [comment]
@mukhtarmid did you get time to work on it?

**Comment by mukhtarmid** [comment]
@FlorentLvr, I'm having issue with API key. I'm dropping from this issue.

**Comment by FlorentLvr** [comment]
> @FlorentLvr, I'm having issue with API key. I'm dropping from this issue.

Okok, no pb. What kind of issue did you have with your API key?

**Comment by mukhtarmid** [comment]
@FlorentLvr, Sure, I'm not able to generate the key, its having some issue with my email id. Trying to fix that with the support team.

**Comment by FlorentLvr** [comment]
> @FlorentLvr, Sure, I'm not able to generate the key, its having some issue with my email id. Trying to fix that with the support team.

Oh! I see. Hope they will find a way to fix it @mukhtarmid 🙏
