### ISSUE TITLE
Youtube Downloader issue

### ISSUE THREAD

**Issue by stkarlos** [jupyter-naas/awesome-notebooks#1845]
**Describe the bug**

I tried to run the notebook YouTube_Download_video.ipynb.

After installing the pytube version 9.6.4 i get the next error:

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Cell In[3], line 3
      1 youtube_video_url = "https://www.youtube.com/watch?v=fqEmGXu8HEk"
----> 3 yt_obj = YouTube(youtube_video_url)

File ~\anaconda3\envs\sklearn122\Lib\site-packages\pytube\__main__.py:91, in YouTube.__init__(self, url, defer_prefetch_init, on_progress_callback, on_complete_callback, proxies)
     88     install_proxy(proxies)
     90 if not defer_prefetch_init:
---> 91     self.prefetch()
     92     self.descramble()

File ~\anaconda3\envs\sklearn122\Lib\site-packages\pytube\__main__.py:181, in YouTube.prefetch(self)
    176 else:
    177     self.vid_info_url = extract.video_info_url(
    178         video_id=self.video_id, watch_url=self.watch_url
    179     )
--> 181 self.vid_info_raw = request.get(self.vid_info_url)
    182 if not self.age_restricted:
    183     self.js_url = extract.js_url(self.watch_html)

File ~\anaconda3\envs\sklearn122\Lib\site-packages\pytube\request.py:36, in get(url)
     27 def get(url) -> str:
     28     """Send an http GET request.
     29 
     30     :param str url:
   (...)
     34         UTF-8 encoded string of response
     35     """
---> 36     return _execute_request(url).read().decode("utf-8")

File ~\anaconda3\envs\sklearn122\Lib\site-packages\pytube\request.py:24, in _execute_request(url, method, headers)
     22 else:
     23     raise ValueError("Invalid URL")
---> 24 return urlopen(request)

File ~\anaconda3\envs\sklearn122\Lib\urllib\request.py:216, in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    214 else:
    215     opener = _opener
--> 216 return opener.open(url, data, timeout)

File ~\anaconda3\envs\sklearn122\Lib\urllib\request.py:525, in OpenerDirector.open(self, fullurl, data, timeout)
    523 for processor in self.process_response.get(protocol, []):
    524     meth = getattr(processor, meth_name)
--> 525     response = meth(req, response)
    527 return response

File ~\anaconda3\envs\sklearn122\Lib\urllib\request.py:634, in HTTPErrorProcessor.http_response(self, request, response)
    631 # According to RFC 2616, "2xx" code indicates that the client's
    632 # request was successfully received, understood, and accepted.
    633 if not (200 <= code < 300):
--> 634     response = self.parent.error(
    635         'http', request, response, code, msg, hdrs)
    637 return response

File ~\anaconda3\envs\sklearn122\Lib\urllib\request.py:557, in OpenerDirector.error(self, proto, *args)
    555     http_err = 0
    556 args = (dict, proto, meth_name) + args
--> 557 result = self._call_chain(*args)
    558 if result:
    559     return result

File ~\anaconda3\envs\sklearn122\Lib\urllib\request.py:496, in OpenerDirector._call_chain(self, chain, kind, meth_name, *args)
    494 for handler in handlers:
    495     func = getattr(handler, meth_name)
--> 496     result = func(*args)
    497     if result is not None:
    498         return result

File ~\anaconda3\envs\sklearn122\Lib\urllib\request.py:749, in HTTPRedirectHandler.http_error_302(self, req, fp, code, msg, headers)
    746 fp.read()
    747 fp.close()
--> 749 return self.parent.open(new, timeout=req.timeout)

File ~\anaconda3\envs\sklearn122\Lib\urllib\request.py:525, in OpenerDirector.open(self, fullurl, data, timeout)
    523 for processor in self.process_response.get(protocol, []):
    524     meth = getattr(processor, meth_name)
--> 525     response = meth(req, response)
    527 return response

File ~\anaconda3\envs\sklearn122\Lib\urllib\request.py:634, in HTTPErrorProcessor.http_response(self, request, response)
    631 # According to RFC 2616, "2xx" code indicates that the client's
    632 # request was successfully received, understood, and accepted.
    633 if not (200 <= code < 300):
--> 634     response = self.parent.error(
    635         'http', request, response, code, msg, hdrs)
    637 return response

File ~\anaconda3\envs\sklearn122\Lib\urllib\request.py:563, in OpenerDirector.error(self, proto, *args)
    561 if http_err:
    562     args = (dict, 'default', 'http_error_default') + orig_args
--> 563     return self._call_chain(*args)

File ~\anaconda3\envs\sklearn122\Lib\urllib\request.py:496, in OpenerDirector._call_chain(self, chain, kind, meth_name, *args)
    494 for handler in handlers:
    495     func = getattr(handler, meth_name)
--> 496     result = func(*args)
    497     if result is not None:
    498         return result

File ~\anaconda3\envs\sklearn122\Lib\urllib\request.py:643, in HTTPDefaultErrorHandler.http_error_default(self, req, fp, code, msg, hdrs)
    642 def http_error_default(self, req, fp, code, msg, hdrs):
--> 643     raise HTTPError(req.full_url, code, msg, hdrs, fp)

HTTPError: HTTP Error 410: Gone

Any ideas?

Thank you.

**Comment by FlorentLvr** [comment]
@stkarlos, thank you for reaching out! It seems the version of the `pytub3` library we are using is not the right one. I will fix the template and update it in the awesome notebook repo!
