### ISSUE TITLE
LinkedIn - Send invitation to profile: No 'invitation' attribute

### ISSUE THREAD

**Issue by alextbogdanov** [jupyter-naas/awesome-notebooks#1853]
In "LinkedIn - Send invitation to profile" no matter what session storage you provide you get this error:
AttributeError: 'LinkedIn' object has no attribute 'invitation'

**Comment by FlorentLvr** [comment]
Hi @alextbogdanov, 
Thank you for raising the error! Could you please give me more context on this error? What is the exact line of code in error?

**Comment by FlorentLvr** [comment]
@alextbogdanov, I am closing this issue as you didn't answer to my last message. Please don't hesitate to reopen the issue if needed
