### ISSUE TITLE
Pandas - Concatenate dataframe fix

### ISSUE THREAD

**Issue by Benjifilly** [jupyter-naas/awesome-notebooks#1878]
**Describe the bug**
just a syntax fix 

**To Reproduce**
1. Scroll down to 'diplay dataframe 1'
2. See error

**Expected behavior**
need to change the syntax

**Screenshots**
![image](https://github.com/jupyter-naas/awesome-notebooks/assets/112804903/07ca0bd8-9cb7-4017-9f5f-862b7d28d893)

**Comment by Benjifilly** [comment]
@mukhtarmid Are you sure, I can still see it, it's in the model section

**Comment by Benjifilly** [comment]
no problem, I'm happy to help

**Comment by FlorentLvr** [comment]
@Benjifilly, is this issue fixed?

**Comment by mukhtarmid** [comment]
@FlorentLvr, Yes! But haven't pushed yet.

**Comment by FlorentLvr** [comment]
> @FlorentLvr, Yes! But haven't pushed yet.

@mukhtarmid, okai got it! Did you already create a branch?

**Comment by mukhtarmid** [comment]
@FlorentLvr, not yet! Should I create one or where should I push that changes? On master?
