### ISSUE TITLE
Langchain - Vector search on the PDF using langchain abstraction

### ISSUE THREAD

**Issue by srini047** [jupyter-naas/awesome-notebooks#1893]
**Describe the solution you'd like**
1. Load the PDF file.
2. Split the document into smaller chunks.
3. Embed each chunk using OpenAI's ada-002 model.
4. Store the embeddings in an in-memory Faiss Vector DB.
5. Ask questions about the PDF.

**Additional context**
- Reference: https://www.linkedin.com/posts/itamar-g1_talk-to-your-pdf-using-just-10-lines-of-code-activity-7073527643924496384-jeSv?utm_source=share&utm_medium=member_desktop
- Similar to #1835 but for PDFs

cc @jravenel @FlorentLvr

**Comment by FlorentLvr** [comment]
@srini047! That's good idea! Did you work on it already?

**Comment by srini047** [comment]
> @srini047! That's good idea! Did you work on it already?

@FlorentLvr I'm on it.



> It's what Maxime did I think, with embedding

@Dr0p42 Can you share the link or references on how did you build it?

**Comment by jravenel** [comment]
Maybe we should use weviate, open source for the win :)
