### ISSUE TITLE
Update generate readme “Open in myChatGPT”  

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1901]
if "plugin" in parameters in notebook:
- create button: "open in myChatGPT" in header
- update json as output with new key "open in myChatGPT"

**Comment by jravenel** [comment]
Hi guys, 

I did have 2 options:  Open in Lab + Open in Chat vs Open in NaasLab + Open in MyChatGPT

<img src='https://img.shields.io/badge/-Open%20in%20Lab-success?labelColor=000000&logo=data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iMTAyNHB4IiBoZWlnaHQ9IjEwMjRweCIgdmlld0JveD0iMCAwIDEwMjQgMTAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgdmVyc2lvbj0iMS4xIj4KIDwhLS0gR2VuZXJhdGVkIGJ5IFBpeGVsbWF0b3IgUHJvIDIuMC41IC0tPgogPGRlZnM+CiAgPHRleHQgaWQ9InN0cmluZyIgdHJhbnNmb3JtPSJtYXRyaXgoMS4wIDAuMCAwLjAgMS4wIDIyOC4wIDU0LjUpIiBmb250LWZhbWlseT0iQ29tZm9ydGFhLVJlZ3VsYXIsIENvbWZvcnRhYSIgZm9udC1zaXplPSI4MDAiIHRleHQtZGVjb3JhdGlvbj0ibm9uZSIgZmlsbD0iI2ZmZmZmZiIgeD0iMS4xOTk5OTk5OTk5OTk5ODg2IiB5PSI3MDUuMCI+bjwvdGV4dD4KIDwvZGVmcz4KIDx1c2UgaWQ9Im4iIHhsaW5rOmhyZWY9IiNzdHJpbmciLz4KPC9zdmc+Cg=='>

<img src='https://img.shields.io/badge/-Open%20in%20Chat-black?labelColor=000000&logo=data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iMTAyNHB4IiBoZWlnaHQ9IjEwMjRweCIgdmlld0JveD0iMCAwIDEwMjQgMTAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgdmVyc2lvbj0iMS4xIj4KIDwhLS0gR2VuZXJhdGVkIGJ5IFBpeGVsbWF0b3IgUHJvIDIuMC41IC0tPgogPGRlZnM+CiAgPHRleHQgaWQ9InN0cmluZyIgdHJhbnNmb3JtPSJtYXRyaXgoMS4wIDAuMCAwLjAgMS4wIDIyOC4wIDU0LjUpIiBmb250LWZhbWlseT0iQ29tZm9ydGFhLVJlZ3VsYXIsIENvbWZvcnRhYSIgZm9udC1zaXplPSI4MDAiIHRleHQtZGVjb3JhdGlvbj0ibm9uZSIgZmlsbD0iI2ZmZmZmZiIgeD0iMS4xOTk5OTk5OTk5OTk5ODg2IiB5PSI3MDUuMCI+bjwvdGV4dD4KIDwvZGVmcz4KIDx1c2UgaWQ9Im4iIHhsaW5rOmhyZWY9IiNzdHJpbmciLz4KPC9zdmc+Cg=='>

<img src='https://img.shields.io/badge/-Open%20in%20NaasLab-success?labelColor=000000&logo=data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iMTAyNHB4IiBoZWlnaHQ9IjEwMjRweCIgdmlld0JveD0iMCAwIDEwMjQgMTAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgdmVyc2lvbj0iMS4xIj4KIDwhLS0gR2VuZXJhdGVkIGJ5IFBpeGVsbWF0b3IgUHJvIDIuMC41IC0tPgogPGRlZnM+CiAgPHRleHQgaWQ9InN0cmluZyIgdHJhbnNmb3JtPSJtYXRyaXgoMS4wIDAuMCAwLjAgMS4wIDIyOC4wIDU0LjUpIiBmb250LWZhbWlseT0iQ29tZm9ydGFhLVJlZ3VsYXIsIENvbWZvcnRhYSIgZm9udC1zaXplPSI4MDAiIHRleHQtZGVjb3JhdGlvbj0ibm9uZSIgZmlsbD0iI2ZmZmZmZiIgeD0iMS4xOTk5OTk5OTk5OTk5ODg2IiB5PSI3MDUuMCI+bjwvdGV4dD4KIDwvZGVmcz4KIDx1c2UgaWQ9Im4iIHhsaW5rOmhyZWY9IiNzdHJpbmciLz4KPC9zdmc+Cg=='>

<img src='https://img.shields.io/badge/-Open%20in%20MyChatGPT-black?labelColor=000000&logo=data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iMTAyNHB4IiBoZWlnaHQ9IjEwMjRweCIgdmlld0JveD0iMCAwIDEwMjQgMTAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgdmVyc2lvbj0iMS4xIj4KIDwhLS0gR2VuZXJhdGVkIGJ5IFBpeGVsbWF0b3IgUHJvIDIuMC41IC0tPgogPGRlZnM+CiAgPHRleHQgaWQ9InN0cmluZyIgdHJhbnNmb3JtPSJtYXRyaXgoMS4wIDAuMCAwLjAgMS4wIDIyOC4wIDU0LjUpIiBmb250LWZhbWlseT0iQ29tZm9ydGFhLVJlZ3VsYXIsIENvbWZvcnRhYSIgZm9udC1zaXplPSI4MDAiIHRleHQtZGVjb3JhdGlvbj0ibm9uZSIgZmlsbD0iI2ZmZmZmZiIgeD0iMS4xOTk5OTk5OTk5OTk5ODg2IiB5PSI3MDUuMCI+bjwvdGV4dD4KIDwvZGVmcz4KIDx1c2UgaWQ9Im4iIHhsaW5rOmhyZWY9IiNzdHJpbmciLz4KPC9zdmc+Cg=='>

Both options are technically accurate, but they convey slightly different information to the user.

Open in Lab + Open in Chat: This option is more concise and to the point. It immediately tells the user what action they can perform - they can open the application either in a Lab or in a Chat. However, it doesn't specify which Lab or Chat, which could potentially be confusing if there are other Labs or Chats that your users might be using (like Colab, SageMaker...)

Open in NaasLab + Open in MyChatGPT: This option is more explicit. It tells the user exactly which Lab and Chat they can open the application in. This can be helpful if your users are using multiple Labs or Chats and you want to specify exactly where they should go.

In general, clarity and specificity are usually beneficial for users, especially if there could be any potential for confusion. So I would lean towards using the "Open in NaasLab + Open in MyChatGPT" option. However, if there's no chance of confusion or if you want to keep the badges as concise as possible, "Open in Lab + Open in Chat" could also work.

I also wanted to consider how well the text fits within the badges. But even if the one option "Open in NaasLab + Open in MyChatGPT" leads to a larger badge it does fit well with our design.

**Comment by jravenel** [comment]
As a conclusion, here is what we decided to settle on: Naas Lab + MyChatGPT. 

Here is how it should look in a notebook: 
<img width="842" alt="Screenshot 2023-06-13 at 12 01 05" src="https://github.com/jupyter-naas/awesome-notebooks/assets/21052349/f415855f-f48f-4e7e-8435-7897b3ebadf5">


Here is how it should like in Search: 
<img width="1057" alt="Screenshot 2023-06-13 at 12 04 43" src="https://github.com/jupyter-naas/awesome-notebooks/assets/21052349/d0740dc8-6f43-468d-a01e-f673c67fb8ab">

**Comment by FlorentLvr** [comment]
> As a conclusion, here is what we decided to settle on: Naas Lab + MyChatGPT.
> 
> Here is how it should look in a notebook: <img alt="Screenshot 2023-06-13 at 12 01 05" width="842" src="https://user-images.githubusercontent.com/21052349/245437855-f415855f-f48f-4e7e-8435-7897b3ebadf5.png">
> 
> Here is how it should like in Search: <img alt="Screenshot 2023-06-13 at 12 04 43" width="1057" src="https://user-images.githubusercontent.com/21052349/245438691-d0740dc8-6f43-468d-a01e-f673c67fb8ab.png">
> 
> Also the good thing is that it says consistent with the launchpad: <img alt="Screenshot 2023-06-13 at 12 02 42" width="420" src="https://user-images.githubusercontent.com/21052349/245438857-81218336-42c7-4b60-af4a-094ca4ba24a8.png">



> As a conclusion, here is what we decided to settle on: Naas Lab + MyChatGPT.
> 
> Here is how it should look in a notebook: <img alt="Screenshot 2023-06-13 at 12 01 05" width="842" src="https://user-images.githubusercontent.com/21052349/245437855-f415855f-f48f-4e7e-8435-7897b3ebadf5.png">
> 
> Here is how it should like in Search: <img alt="Screenshot 2023-06-13 at 12 04 43" width="1057" src="https://user-images.githubusercontent.com/21052349/245438691-d0740dc8-6f43-468d-a01e-f673c67fb8ab.png">
> 
> Also the good thing is that it says consistent with the launchpad: <img alt="Screenshot 2023-06-13 at 12 02 42" width="420" src="https://user-images.githubusercontent.com/21052349/245438857-81218336-42c7-4b60-af4a-094ca4ba24a8.png">

@jravenel, I am almost done with this task but i would need an static svg url like the one we used (https://naasai-public.s3.eu-west-3.amazonaws.com/open_in_naas.svg). Do you think it would be possible to have it?
