### ISSUE TITLE
LinkedIn - Modify get posts stats from profile to have a JSON plugin

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1939]
At the end of the notebook we want to generate something like this: 

{
  "data": "< The data frame we generate in dict >",
  "schema": {
    "ENTITY": {
      "type": "string",
      "description": "The entity that the content is associated with."
    },
    "SCENARIO": {
      "type": "string",
      "description": "The scenario or context for the content."
    },
    "SOURCE": {
      "type": "string",
      "description": "The platform where the content was posted."
    },
    "DATE": {
      "type": "string",
      "format": "date",
      "description": "The date when the content was posted."
    },
    "TIME": {
      "type": "string",
      "format": "time",
      "description": "The time when the content was posted."
    },
    "TITLE": {
      "type": "string",
      "description": "The title of the content."
    },
    "CONTENT": {
      "type": "string",
      "description": "The full content text."
    },
    "VIEWS": {
      "type": "integer",
      "description": "The number of views the content received."
    },
    "LIKES": {
      "type": "integer",
      "description": "The number of likes the content received."
    },
    "COMMENTS": {
      "type": "integer",
      "description": "The number of comments the content received."
    },
    "SHARES": {
      "type": "integer",
      "description": "The number of shares the content received."
    },
    "ENGAGEMENT RATE": {
      "type": "number",
      "description": "The engagement rate calculated based on likes, comments, shares, and views."
    },
    "SOURCE TYPE": {
      "type": "string",
      "description": "The type of the source platform (e.g., 'Social Media', 'Blog', 'Video')."
    },
    "CONTENT LENGTH": {
      "type": "integer",
      "description": "The length of the content in terms of number of words or characters."
    },
    "KEYWORDS": {
      "type": "string",
      "description": "The keywords or hashtags associated with the content."
    },
    "URL": {
      "type": "string",
      "format": "uri",
      "description": "The URL of the content."
    },
    "SENTIMENT": {
      "type": "string",
      "description": "The sentiment of the content (e.g., 'Positive', 'Negative', 'Neutral')."
    },
    "MEDIA TYPE": {
      "type": "string",
      "description": "The type of media used in the content (e.g., 'Text', 'Image', 'Video')."
    },
  },
  "required": ["ENTITY", "SCENARIO", "SOURCE", "DATE", "TIME", "TITLE", "CONTENT", "VIEWS", "LIKES", "COMMENTS", "SHARES"]
}

**Comment by FlorentLvr** [comment]
@jravenel 
Name: LinkedIn_Chat_about_my_lastest_profile_posts.ipynb

Input:
Limit: 15

Output:
json with asset to integrate with MyChatGPT
