### ISSUE TITLE
CICD - Fix Generate certificate error

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1958]
@SuhasBRao, just created the issue to fix the error here.
Sorry for merging it too early, i thought it was done 🙏 

<img width="1052" alt="image" src="https://github.com/jupyter-naas/awesome-notebooks/assets/48032461/dffb18fc-6433-485c-ab8d-3bfb22ada155">

**Comment by SuhasBRao** [comment]
Hey @FlorentLvr, we need to create a secret in this repo with name IMGBB_API, I couldn't create the secret, you can create this and add the value it will work.

**Comment by FlorentLvr** [comment]
@Dr0p42, just checking! Could you please add the ENV variable in awesome-notebook repo to be able to generate a certificate? TY

**Comment by FlorentLvr** [comment]
Fixed: API key added by @Dr0p42
