### ISSUE TITLE
LinkedIn - Create post from profile

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#201]
As a LinkedIn user, I would like to send a post programmatically with a notebook. 

Input : 
LIAT =
JSESSIONID = 
POST = "my message in html" 

Model:
connect. + send post 

Output:  
return "✅ Your post as been sent successfully"

**Comment by jravenel** [comment]
@mellamomark just created the issue as we talked about. 
Feel free to ask here for any support you may need from @jupyter-naas/core-team

**Comment by FlorentLvr** [comment]
Template available here: https://github.com/jupyter-naas/awesome-notebooks/blob/master/LinkedIn/LinkedIn_Create_Post.ipynb
