### ISSUE TITLE
Google Sheet - Calculate distance and price 

### ISSUE THREAD

**Issue by tony-georgiev** [jupyter-naas/awesome-notebooks#2025]
Description:
By integrating Google Sheets, this Naas notebook determines the cost and distance between a number of locations. It uses the Routes API to estimate the price depending on the distance between sites.

- Input 
Google Sheet including coordinates or addresses for the origin and destination locations
- Model 
Integration with Google Sheets to read location information.
Routes API for distance and price calculations between locations
- Output
Updated Google Sheet with the calculated distance and price for each location pair

**Comment by niccm** [comment]
I am planning on working on this issue with DiegoEspinoza1 as part of the CTI summer open source experience. Can you assign this issue to me?

**Comment by tony-georgiev** [comment]
> I am planning on working on this issue with DiegoEspinoza1 as part of the CTI summer open source experience. Can you assign this issue to me?

Hey @niccm ,
I have finished and I am waiting for a review. If you are interested in adding up and improving, I would be more than happy to assign it to you and DiegoEspinoza1.
Let me know.

**Comment by niccm** [comment]
> > I am planning on working on this issue with DiegoEspinoza1 as part of the CTI summer open source experience. Can you assign this issue to me?
> 
> Hey @niccm , I have finished and I am waiting for a review. If you are interested in adding up and improving, I would be more than happy to assign it to you and DiegoEspinoza1. Let me know.

Hi @tony-georgiev that would be great!

**Comment by tony-georgiev** [comment]
> > > I am planning on working on this issue with DiegoEspinoza1 as part of the CTI summer open source experience. Can you assign this issue to me?
> > 
> > 
> > Hey @niccm , I have finished and I am waiting for a review. If you are interested in adding up and improving, I would be more than happy to assign it to you and DiegoEspinoza1. Let me know.
> 
> Hi @tony-georgiev that would be great!

Done, I was having an issue assigning DiegoEspinoza1 as well. You can try :)
