### ISSUE TITLE
LinkedIn - Chat about my latest profile posts: Error short description

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#2109]
**Describe the bug**

→ When I am on the world cloud step I have this error : ValueError: Only supported for TrueType fonts
![Uploading Screenshot 2023-08-03 at 14.09.28.png…]()

**Comment by FlorentLvr** [comment]
@jravenel, The error message you're seeing, `ValueError: Only supported for TrueType fonts`, typically occurs when you're trying to use a font in your Jupyter notebook that is not a TrueType font. 

To fix it, you have to use the default font in matplotlib. It should work if you run this command:

```
import matplotlib as mpl
import matplotlib.pyplot as plt

# Reset the default parameters
mpl.rcParams.update(mpl.rcParamsDefault)

# Now create a plot to see the results
plt.plot([1, 2, 3, 4])
plt.ylabel('Numbers')
plt.show()
```

If you continue to experience this issue, please provide more details about your code and environment so I can provide more specific guidance.
