### ISSUE TITLE
HubSpot - Get data from Lists 

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#2112]
**Describe the problem you are facing**
I would like to get the data from the Hubspot List as a dataframe/csv to then analyze it in a Gsheet

- Input 
List ID or name
- Model 
Get list in JSON
Clean JSON to create Dataframe 
- Output
Save Dataframe as CSV

**Comment by jravenel** [comment]
@FlorentLvr  can you help with that?

**Comment by FlorentLvr** [comment]
> @FlorentLvr can you help with that?

I am not sure to understand what you would like to extract from HubSpot. Can you please give more context (screenshot...) ?
It seems the API to get contact list is not available yet on HubSpot... :(

<img width="751" alt="image" src="https://github.com/jupyter-naas/awesome-notebooks/assets/48032461/3194bb9f-f1cf-421b-a124-bc595af2fd4f">

**Comment by FlorentLvr** [comment]
@jravenel, closing this issue because it's under development on HubSpot API
