### ISSUE TITLE
CICD - Run failed: .github/workflows/refresh_updated_at.yaml

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#2127]
<img width="655" alt="image" src="https://github.com/jupyter-naas/awesome-notebooks/assets/48032461/328a5664-ab6b-4bc8-8695-449b2de45219">

**Comment by FlorentLvr** [comment]
@Dr0p42, could you please remove this process from cicd to avoid the error messages please 🙏 ?

**Comment by Dr0p42** [comment]
Hello @FlorentLvr this has been disabled for two weeks now, if it's still happening, this means that your branch might not be up to date with the `master` branch. Can you confirm ? 

The file should look like this in your branch: https://github.com/jupyter-naas/awesome-notebooks/blob/master/.github/workflows/refresh_updated_at.yaml

**Comment by FlorentLvr** [comment]
@Dr0p42, I created a new branch yesterday and push a new commit on it and i still have this error: 
![image](https://github.com/jupyter-naas/awesome-notebooks/assets/48032461/d3966a37-78d8-441e-b83a-79cee6d1646b)

**Comment by FlorentLvr** [comment]
Thanks @Dr0p42, it's working well now :)
