### ISSUE TITLE
Fail on pip install

### ISSUE THREAD

**Issue by scottr99** [jupyter-naas/awesome-notebooks#2129]
Output after "pip install naas"

fatal error: too many errors emitted, stopping now [-ferror-limit=]
      20 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for uvloop
  Running setup.py clean for uvloop
Failed to build uvloop
ERROR: Could not build wheels for uvloop, which is required to install pyproject.toml-based projects

**To Reproduce**
pip install naas

**Expected behavior**
fatal error

**Additional context**
Using Python 3.10.12

**Comment by FlorentLvr** [comment]
Hi @scottr99! Thanks for getting in touch. We'll investigate this error. Since we've opened an issue on awesome-notebooks, could you kindly tell us the name of the template you attempted to run locally? Also, have you tried running it on Naas lab (cloud)?

**Comment by scottr99** [comment]
Hi. No I have not tried running it on Naas lab cloud. My error happened when trying to install naas, in a terminal.

**Comment by FlorentLvr** [comment]
Hi @scottr99! 
We are currently in the process of developing a new API version for Naas and, as such, unfortunately, we are not supporting local installations at this time. However, you can still explore and use Naas on the cloud. We anticipate that the new API version will be available for trial by the end of this year. Could you please let us know which Naas features you are particularly interested in?
