### ISSUE TITLE
Upwork - Get list of jobs from keywords

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#217]
The objective of this notebook is to get access to all the job list in Upwork for certain keywords. 

## Input 
- KEYWORDS = ["data", "python"]

## Model 
Connect to Upwork API, query from variables (https://developers.upwork.com/?lang=python#jobs_search-for-jobs) in KEYWORDS, and return dataframe with the following columns: 
- JOB_TITLE: Web developer
- JOB_DESCRIPTION: "I'm looking for..."
- JOB_SNIPPET: "Need a custom website <...>",
- JOB_URL: "
- JOB_WORKLOAD:  'workload': '30+ hrs/week"
-  BUDGET: 750,
-  CATEGORY: 'Web & Mobile Development',
- CLIENT : "Tesla"
- COUNTRY:  "Worldwide"
- DATE_CREATED: "2014-06-30"
- JOB_STATUS: "Open"
- JOB_TYPE: "Fixed"
-  SKILLS: ['css',
              'css3',
              'database-design',
              'database-programming',
              'english',
              'html',
              'javascript',
              'mysql',
              'php',
              'python'],

## Output: 
Return dataframe and export in Excel

**Comment by jravenel** [comment]
Hello @calok64 as discussed last week, here is the task we could start to work on to get the Naas slack channel with automatic updates on jobs. 

He first get this awesome-notebooks done, and then we can design a custom pipeline.

Good for you?

**Comment by calok64** [comment]
Hi Jeremy,

Sure will check this and start the work.

**Comment by jravenel** [comment]
@calok64, @OketunjiOludolapo is going to take over this task for her certification project.

**Comment by jravenel** [comment]
Not possible Upwork API is KO
