### ISSUE TITLE
Remotive.io - Get list of jobs from keywords

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#218]
The objective of this notebook is to get access to all the job list in Remotive.io for certain keywords. 

## Input 
- KEYWORDS = ["data", "python"]

## Model 
Connect to Remotive API, query from variables in input, and return dataframe with the following columns: 
- JOB_TITLE: Web developer
- JOB_DESCRIPTION: "I'm looking for..."
- JOB_SNIPPET: "Need a custom website <...>",
- JOB_URL: "
- JOB_WORKLOAD:  'workload': '30+ hrs/week"
-  BUDGET: 750,
-  CATEGORY: 'Web & Mobile Development',
- CLIENT : "Tesla"
- COUNTRY:  "Worldwide"
- DATE_CREATED: "2014-06-30"
- JOB_STATUS: "Open"
- JOB_TYPE: "Fixed"
-  SKILLS: ['css',
              'css3',
              'database-design',
              'database-programming',
              'english',
              'html',
              'javascript',
              'mysql',
              'php',
              'python'],

## Output: 
Return dataframe and export in Excel

**Comment by jravenel** [comment]
Hey @yaswanthkumargothi as discussed today, I let you take over the notebook done in R&D phase on remotive.io to send daily updates on the #04_work channel of the Naas Slack Club. 

The idea is to make it work as a standalone notebook without dependencies to the google sheet (with jobs that have been posted before)

**Comment by adriencombourieu** [comment]
Hi guys, Adrien CTO @ remotive.io here. Great to see you are interested in our data ;) Let us know if we can help!
Our public API documentation is now here: https://github.com/remotive-io/remote-jobs-api

**Comment by jravenel** [comment]
Hey @adriencombourieu, thanks for reaching out :) we have actually made our first notebook a few months ago with your API.
It's sending current opportunities for a certain set of keywords to our community slack. 

<img width="763" alt="Screenshot 2022-01-06 at 12 30 27" src="https://user-images.githubusercontent.com/21052349/148376567-c7367a19-e70d-4402-9f7a-a41f29655e7d.png">

Now we just need to build the template that automates it . 
Are you interested in building it with us and communicating about it? That would be awesome 😇

Feel free to reach out here so we can discuss the details: jeremy@naas.ai

**Comment by jravenel** [comment]
@yaswanthkumargothi are you still up for that or should we pass to another contributor?

**Comment by jravenel** [comment]
@OketunjiOludolapo as discussed :) this is. the issue and I have a notebook to share. Want to take it? 
cc @yaswanthkumargothi we keep you in the loop?

**Comment by OketunjiOludolapo** [comment]
> @OketunjiOludolapo as discussed :) this is. the issue and I have a notebook to share. Want to take it? cc @yaswanthkumargothi we keep you in the loop?

Yes, i will. Do attach the link to the notebook. Thanks

**Comment by yaswanthkumargothi** [comment]
> @yaswanthkumargothi are you still up for that or should we pass to another contributor?

Sorry @jravenel , I am fully occupied with work these days and couldn't check the mentions here. Will soon update you on interesting things happening here!

**Comment by yaswanthkumargothi** [comment]
> @yaswanthkumargothi are you still up for that or should we pass to another contributor?

Sorry @jravenel , I am fully occupied with work these days, and couldn't be able to check mentions and contribute. A lot of uncertainity might soon go away and expecting newer beginnings will help me more active in open-source! keep pushing @SanjuEpic @OketunjiOludolapo :+1: :rocket:

**Comment by jravenel** [comment]
No issue !!
