### ISSUE TITLE
Github - List of all files added 

### ISSUE THREAD

**Issue by Benjifilly** [jupyter-naas/awesome-notebooks#2181]
**Describe the problem you are facing**
I wanted to know the exact date of one of my templates, so I created a code to list all the files added with specifications such as the date.

**Describe the solution you'd like**
A code that give me the name of the files, date, path, url and maybe more

- Input 
contributor name, filter from when to when, filter by tool name, 
- Model 
get all files added
- Output
a list of the files added

**Comment by FlorentLvr** [comment]
Already existing.

**Comment by Benjifilly** [comment]
Didn't saw that sorry
