### ISSUE TITLE
Update the "Open in MyChatGPT" button to "Open in Naas Chat"

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#2196]
The button is not reflecting the recent changes needed to not refer to openAI/chatGPT. 
Change has already been made by @Dr0p42 on the search but still buttons need to be updated.

**Comment by FlorentLvr** [comment]
@jravenel, can you please provide me the link to get the button image?

**Comment by FlorentLvr** [comment]
@jravenel, could you please provide me the new logo? It is still not fixed but I can do it quickly?

**Comment by Dr0p42** [comment]
![open_in_naas_chat](https://github.com/jupyter-naas/awesome-notebooks/assets/22365519/63ba6351-1fe7-4394-a1a0-5bc6a18fa07e)
![Open_in_Naas_Lab](https://github.com/jupyter-naas/awesome-notebooks/assets/22365519/f6fafd47-40f9-4715-b43b-dc5e1fbe3bc0)
I was able to get this, let me know what you think

**Comment by FlorentLvr** [comment]
Integrate into awesome notebooks and search done 👍
