### ISSUE TITLE
Matplotlib - Create Piechart

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#2255]
This notebook will show how to create a piechart with Matplotlib. Pie charts are useful to represent proportions of a whole.

**Comment by MSaiKiran9** [comment]
hi @FlorentLvr  i would like to work on this can you assign me this ,I'm new to this repo can you please elaborate what exactly we should do here ?

**Comment by FlorentLvr** [comment]
> hi @FlorentLvr i would like to work on this can you assign me this ,I'm new to this repo can you please elaborate what exactly we should do here ?

Sure! You can work on the branch and the draft already created. Don't forget to add your name in the notebook and make sure everything is working fine! TY 🙏

**Comment by devvkumar** [comment]
Please assign me this issue

**Comment by FlorentLvr** [comment]
> Please assign me this issue

Hi @devvkumar, glad you want to contribute!
This issue is already taken but you could create new ones after reviewing your application.
Please follow these instructions in the awesome-notebook README.md to start contributing. -> https://github.com/jupyter-naas/awesome-notebooks/blob/master/README.md#how-to-contribute
Let me know if you have any questions! 🙏
Cheers!
