### ISSUE TITLE
Google Sheets - List sheets

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#2256]
This notebook lists sheets from a spreadsheet URL. It is usefull for organizations to quickly access the sheets of a spreadsheet.

**Comment by FlorentLvr** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [2256-google-sheets-list-sheets](https://github.com/jupyter-naas/awesome-notebooks/tree/2256-google-sheets-list-sheets)
- Notebook: [Google%20Sheets/Google_Sheets_List_sheets.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/2256-google-sheets-list-sheets/Google%20Sheets/Google_Sheets_List_sheets.ipynb)

**Comment by MSaiKiran9** [comment]
Hi @FlorentLvr can I work on this ?

**Comment by FlorentLvr** [comment]
@MSaiKiran9, would you like to work on this one?

**Comment by MSaiKiran9** [comment]
Sure @FlorentLvr
