### ISSUE TITLE
Google Sheets - Create new sheet

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#2257]
This notebook will show how to create a new sheet in Google Sheets using Python. It is usefull for organizations that need to create new sheets in Google Sheets.

**Comment by FlorentLvr** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [2257-google-sheets-create-new-sheet](https://github.com/jupyter-naas/awesome-notebooks/tree/2257-google-sheets-create-new-sheet)
- Notebook: [Google%20Sheets/Google_Sheets_Create_new_sheet.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/2257-google-sheets-create-new-sheet/Google%20Sheets/Google_Sheets_Create_new_sheet.ipynb)

**Comment by MSaiKiran9** [comment]
@FlorentLvr can I work on this ?

**Comment by FlorentLvr** [comment]
> @FlorentLvr can I work on this ?

Sure! Love that energy @MSaiKiran9 🔥

**Comment by MSaiKiran9** [comment]
Hi @FlorentLvr I'm trying to create new sheet using IAM and admin > service accounts , as when I'm creating it using Oauth client id's it'll redirect the client ( that's the hosted notebook ) to authorize in a hosted port which isn't possible in the notebook environment . So I used  IAM & admin > service accounts the final output will be something like this : 
<img width="631" alt="image" src="https://github.com/jupyter-naas/awesome-notebooks/assets/116418856/3c657885-2cb4-4759-a9e3-6fecfe9193ea">
Is it okay ?

**Comment by FlorentLvr** [comment]
> Hi @FlorentLvr I'm trying to create new sheet using IAM and admin > service accounts , as when I tried creating it using Oauth client id's it's redirecting the client ( that's the hosted notebook ) to authorize with gmail account in a hosted port which isn't possible in the notebook environment . So I used IAM & admin > service accounts . The final output will be something like this , where we also can share the sheet with specific people : <img alt="image" width="631" src="https://user-images.githubusercontent.com/116418856/276626439-3c657885-2cb4-4759-a9e3-6fecfe9193ea.png"> If everything is okay i'll push the changes ?

Hello @MSaiKiran9, it's perfect! Using a service accounts is the perfect method to handle GCP services. Keep up the good work! :)
