### ISSUE TITLE
LlamaIndex - Integrate with Neo4j

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#2268]
This notebook demonstrates how to use Llamaindex and Neo4j as graph store to perform request and response model for the custom data. It is usefull for organizations to quickly integrate Neo4j with Llamaindex.

**Comment by FlorentLvr** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [2268-llamaindex-integrate-with-neo4j](https://github.com/jupyter-naas/awesome-notebooks/tree/2268-llamaindex-integrate-with-neo4j)
- Notebook: [LlamaIndex/LlamaIndex_Integrate_with_Neo4j.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/2268-llamaindex-integrate-with-neo4j/LlamaIndex/LlamaIndex_Integrate_with_Neo4j.ipynb)

**Comment by mahimairaja** [comment]
Hi @FlorentLvr ,

I work with LLM's and graph db, I find this will fit me. I would love to work on this issue. 

Can you please assign this issue to me

**Comment by mahimairaja** [comment]
Thank you for sharing the url FlorentLvr

Happy to tell that,I have registered for the contributor program. Would like to proceed with the further steps...

**Comment by FlorentLvr** [comment]
> Thank you for sharing the url FlorentLvr
> 
> Happy to tell that,I have registered for the contributor program. Would like to proceed with the further steps...

Hello @mahimairaja! You should have received an email to join our team. Now, you can proceed to Step (https://github.com/jupyter-naas/awesome-notebooks/blob/master/README.md#step-2-technical-setup).

Please feel free to reach out if you have any questions! 🙏

**Comment by mahimairaja** [comment]
No @FlorentLvr, I have not received any mail yet

**Comment by mahimairaja** [comment]
> Hello @mahimairaja! You should have received an email to join our team. 

I have received the mail of the form I have filled, but not the invitation to join the team.

Kindly help me with this @FlorentLvr

**Comment by FlorentLvr** [comment]
> > Hello @mahimairaja! You should have received an email to join our team.
> 
> I have received the mail of the form I have filled, but not the invitation to join the team.
> 
> Kindly help me with this @FlorentLvr

@mahimairaja, you should have a received an invitation. 
Please check your email used in GitHub:
<img width="575" alt="image" src="https://github.com/jupyter-naas/awesome-notebooks/assets/48032461/7d3c5ad2-ef5d-462f-a85c-091bcd2bfafa">

**Comment by mahimairaja** [comment]
Thank you @FlorentLvr, I joined the awesome crew.

Kindly assign the issue to me

**Comment by FlorentLvr** [comment]
> Thank you @FlorentLvr, I joined the awesome crew.
> 
> Kindly assign the issue to me

Welcome :)

**Comment by mahimairaja** [comment]
Glad starting my weekend with this cool notebook

Let me clarify few things before raising the PR 

The gist of the notebook is to demonstrate the 

1. Using OpenAI llm api to embed the data using data connectors (here - Simple Directory Reader)  from Llama Index
2. Store it in the neo4j db instance - Knowledge Graph
3. Perform Retrieval Augmented Generation with OpenAI and the Knowledge graph built.
4. Display the response

Kindly comment on this @FlorentLvr

**Comment by FlorentLvr** [comment]
> Glad starting my weekend with this cool notebook
> 
> Let me clarify few things before raising the PR
> 
> The gist of the notebook is to demonstrate the
> 
> 1. Using OpenAI llm api to embed the data using data connectors (here - Simple Directory Reader)  from Llama Index
> 2. Store it in the neo4j db instance - Knowledge Graph
> 3. Perform Retrieval Augmented Generation with OpenAI and the Knowledge graph built.
> 4. Display the response
> 
> Kindly comment on this @FlorentLvr

@mahimairaja, yes totally! @srini047 do you want to add something more?

**Comment by srini047** [comment]
> > Glad starting my weekend with this cool notebook
> > Let me clarify few things before raising the PR
> > The gist of the notebook is to demonstrate the
> > 
> > 1. Using OpenAI llm api to embed the data using data connectors (here - Simple Directory Reader)  from Llama Index
> > 2. Store it in the neo4j db instance - Knowledge Graph
> > 3. Perform Retrieval Augmented Generation with OpenAI and the Knowledge graph built.
> > 4. Display the response
> > 
> > Kindly comment on this @FlorentLvr
> 
> @mahimairaja, yes totally! @srini047 do you want to add something more?

Nothing much @FlorentLvr, @mahimairaja let me know if you face any issues. Glad to assist you.

**Comment by mahimairaja** [comment]
Thanks, @srini047 for asking! Glad to hear from you!
