### ISSUE TITLE
Appwrite - User Authentication

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#2270]
This notebook will demonstrate how to use the Appwrite Python SDK to create a authentication and have options to `create_user`, `delete_user`, `list_all_users` as individual routines. It is usefull for organizations that need to manage user authentication.

**Comment by FlorentLvr** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [2270-appwrite-user-authentication](https://github.com/jupyter-naas/awesome-notebooks/tree/2270-appwrite-user-authentication)
- Notebook: [Appwrite/Appwrite_User_Authentication.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/2270-appwrite-user-authentication/Appwrite/Appwrite_User_Authentication.ipynb)

**Comment by abhinavs1920** [comment]
I want to work on this issue. Please assign it to me

**Comment by MSaiKiran9** [comment]
@teoliphant can I work on this ?

**Comment by FlorentLvr** [comment]
> @teoliphant can I work on this ?

@MSaiKiran9, sure go ahead! TY 🙏

**Comment by FlorentLvr** [comment]
@MSaiKiran9, just checking! Did you start working on it? Need any help?

**Comment by MSaiKiran9** [comment]
@FlorentLvr I was a little busy I'm starting this asap !
