### ISSUE TITLE
LangChain - QA on SQL Databases

### ISSUE THREAD

**Issue by leabuende** [jupyter-naas/awesome-notebooks#2272]
I'd like to add a notebook on performing QA, and Text-to-SQL queries on a SQL database using Langchain. It will be useful to quickly access relevant info from a structured data source.

**Comment by FlorentLvr** [comment]
@leabuende, Great idea!

Make sure you follow the procedure to start contributing: https://site.naas.ai/docs/developers/templates#how-to-contribute and your template is following our framework: https://site.naas.ai/docs/developers/templates#how-is-organized-a-template

 Your template should be stored in the LangChain folder and name: "LangChain_Perform_QA_on_SQL_Databases.ipynb". What do you think?
 
Let me know if you have any questions, 🙏 

Florent

**Comment by FlorentLvr** [comment]
@leabuende! Just checking in, is everything okay?

**Comment by leabuende** [comment]
All good @FlorentLvr, sorry for the delay ! Looking forward to feedback on my PR 🚀

**Comment by FlorentLvr** [comment]
> All good @FlorentLvr, sorry for the delay ! Looking forward to feedback on my PR 🚀

Amazing! We will have a look at it today :)
