### ISSUE TITLE
Python - Download Webpage as PDF

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#2275]
This notebook downloads a webpage as a PDF file using the Python library urllib. It is usefull for organizations that need to save webpages for archiving or for further analysis.

**Comment by FlorentLvr** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [2275-python-download-webpage-as-pdf](https://github.com/jupyter-naas/awesome-notebooks/tree/2275-python-download-webpage-as-pdf)
- Notebook: [Python/Python_Download_Webpage_as_PDF.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/2275-python-download-webpage-as-pdf/Python/Python_Download_Webpage_as_PDF.ipynb)

**Comment by FlorentLvr** [comment]
@mnsvag, Jérémy told me you were interested to work on this issue? Is that correct? Let me know if you have any question. 🙏

**Comment by mnsvag** [comment]
Hello @FlorentLvr Yes, I am  interested in working on this issue. Just got started!

**Comment by Ammar-Asim-23** [comment]
Hello @FlorentLvr . I am interested in working on this issue. Please assign it to me.

**Comment by FlorentLvr** [comment]
> [Ammar-Asim-23](/Ammar-Asim-23)

Hi @Ammar-Asim-23, I am glad you want to contribute! However, this issue has already been assign to @mnsvag.
You can find other issues available here: https://github.com/jupyter-naas/awesome-notebooks/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest+no%3Aassignee

Please follow these instructions in the awesome-notebook README.md to start contributing. -> https://github.com/jupyter-naas/awesome-notebooks/blob/master/README.md#how-to-contribute
Let me know if you have any questions! 🙏
Cheers!

**Comment by FlorentLvr** [comment]
@mnsvag! Just checking in, is everything okay? Let me know you need some help 🙏

**Comment by mnsvag** [comment]
@FlorentLvr, I created a pull request for the issue. Please check.
