### ISSUE TITLE
Medium - Publish article from Mardown file

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#2276]
This notebook explains how to publish an article from a Markdown file via the Medium API. It is usefull for organizations that need to quickly publish content on Medium.

**Comment by FlorentLvr** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [2276-medium-publish-article-from-mardown-file](https://github.com/jupyter-naas/awesome-notebooks/tree/2276-medium-publish-article-from-mardown-file)
- Notebook: [Medium/Medium_Publish_article_from_Mardown_file.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/2276-medium-publish-article-from-mardown-file/Medium/Medium_Publish_article_from_Mardown_file.ipynb)

**Comment by MSaiKiran9** [comment]
@FlorentLvr can i contribute ?

**Comment by FlorentLvr** [comment]
> @FlorentLvr can i contribute . App write finished

Sure! 💯
