### ISSUE TITLE
Matplotlib - Plot Wireframe

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#2278]
This notebook will demonstrate how to plot a wireframe using Matplotlib. It is usefull for data visualization.

**Comment by FlorentLvr** [comment]
🚀 Branch and template have been created and pushed. You should work on: 
- Branch: [2278-matplotlib-plot-wireframe](https://github.com/jupyter-naas/awesome-notebooks/tree/2278-matplotlib-plot-wireframe)
- Notebook: [Matplotlib/Matplotlib_Plot_Wireframe.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/2278-matplotlib-plot-wireframe/Matplotlib/Matplotlib_Plot_Wireframe.ipynb)

**Comment by dikshant182004** [comment]
hii @FlorentLvr plz assign this issue to me.

**Comment by YellowFoxH4XOR** [comment]
Hello @FlorentLvr  is this issue being currently worked on ?
If not can you assign me this issue 👆🏻

**Comment by FlorentLvr** [comment]
> Hello @FlorentLvr is this issue being currently worked on ? If not can you assign me this issue 👆🏻

No! You can take it 💯 :) @YellowFoxH4XOR
