### ISSUE TITLE
Matplotlib - Create Barchart: typo

### ISSUE THREAD

**Issue by MSaiKiran9** [jupyter-naas/awesome-notebooks#2282]
**Describe the bug**
I think there is a typo in the notebook : ax.bar(labels, values, label=bar_labels, color=bar_colors) here we should give label=labels instead of bar_labels 

**To Reproduce**
execute the notebook it'll show 
<img width="441" alt="image" src="https://github.com/jupyter-naas/awesome-notebooks/assets/116418856/8cd27377-662a-40c0-88b2-7a0091d2a169">

**Comment by FlorentLvr** [comment]
@MSaiKiran9, thank you for your feedback! Can you please try to fix it? 🙏

**Comment by MSaiKiran9** [comment]
sure @FlorentLvr

**Comment by FlorentLvr** [comment]
> sure @FlorentLvr should i open new branch for the same ?

A new branch! 🙏
