### ISSUE TITLE
Google Drive - Create shareable public link

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#2295]
This notebook will show how to create a shareable public link from a file stored in Google Drive. This is usefull for organizations to share files with external users without giving them access to the entire Google Drive.

**Comment by FlorentLvr** [comment]
🚀 Branch and draft template (generated by AI) have been created and pushed. You should work on: 
- Branch: [2295-google-drive-create-shareable-public-link](https://github.com/jupyter-naas/awesome-notebooks/tree/2295-google-drive-create-shareable-public-link)
- Notebook: [Google%20Drive/Google_Drive_Create_shareable_public_link.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/2295-google-drive-create-shareable-public-link/Google%20Drive/Google_Drive_Create_shareable_public_link.ipynb)

**Comment by mnsvag** [comment]
@FlorentLvr I  am  interested in working on this. Can you  assign it to me?

**Comment by FlorentLvr** [comment]
> @FlorentLvr I  am  interested in working on this. Can I self assign?

@mnsvag ! Sure 😁
