### ISSUE TITLE
Google Docs - Replace placeholders in document

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#2296]
This notebook shows how to replace placeholders in a Google Docs document. It is usefull for organizations that need to quickly create documents with personalized content.

**Comment by chriscarnold** [comment]
Hi @FlorentLvr can this be assigned to me? I would love to work on this!

**Comment by FlorentLvr** [comment]
> Hi @FlorentLvr can this be assigned to me? I would love to work on this!

Sure @chriscarnold!
Please follow these instructions in the awesome-notebook README.md to start contributing. -> https://github.com/jupyter-naas/awesome-notebooks/blob/master/README.md#how-to-contribute
Let me know if you have any questions! :pray:
Cheers!
