### ISSUE TITLE
Youtube - Send likes videos to Spotify playlist

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#230]
The objective of this notebook is to send likes on Youtube on a Spotify playlist. 

https://www.youtube.com/watch?v=7J_qcttfnJA&feature=youtu.be

To produce the notebook we will structure is this way 

Input : 
API keys

Model: 
Functions

Output: 
message: "Song X sent to spotify"

**Comment by pepyczech** [comment]
Hi, I would be interested in tackling this one - how do I change the status please? Also, it seems I don't have the privileges to publish my branch of awesome-notebooks. Thanks Joe

**Comment by jravenel** [comment]
Hey @pepyczech, thanks for your message, just added you to the contributor's team. Glad to have you with us.
You can change status now, see below👇
<img width="1525" alt="Screenshot 2022-01-02 at 21 12 47" src="https://user-images.githubusercontent.com/21052349/147888269-d2397cd6-2f1b-4ab9-9362-d0c98253b8f7.png">

**Comment by pepyczech** [comment]
Excellent, thank you so much
Looking forward to working with you
Joe

**Comment by jravenel** [comment]
👍👍 @pepyczech feel free to ask if you need any help !

**Comment by pepyczech** [comment]
> 👍👍 @pepyczech feel free to ask if you need any help !

Thanks, will do :)

**Comment by pepyczech** [comment]
@jravenel Submitted initial commit

**Comment by jravenel** [comment]
@pepyczech Can you please link your PR to this issue so we can review? We loss track of your comment sorry.
