### ISSUE TITLE
Invalid python syntax

### ISSUE THREAD

**Issue by jtiscione** [jupyter-naas/awesome-notebooks#2308]
**Describe the bug**
Invalid python syntax:

```
from pydub import AudioSegment
import os
new_path = os.path.join(os.getcwd(), "ffmpeg")
%env PATH=$new_path
```

  File "... /pydub-test.py", line 4
    %env PATH=$new_path
    ^
SyntaxError: invalid syntax

**Comment by YellowFoxH4XOR** [comment]
@jtiscione i think you are running this as a python file and not as a notebook. Hence its breaking to fix this 

`os.environ["PATH"] = new_path
`

instead of `%env PATH=$new_path`

**Comment by jtiscione** [comment]
You guessed right, I was running it as straight Python. I ended up doing what you've just suggested and it works.

**Comment by FlorentLvr** [comment]
> **Describe the bug** Invalid python syntax:
> 
> ```
> from pydub import AudioSegment
> import os
> new_path = os.path.join(os.getcwd(), "ffmpeg")
> %env PATH=$new_path
> ```
> 
> File "... /pydub-test.py", line 4 %env PATH=$new_path ^ SyntaxError: invalid syntax

Hey @jtiscione, Thank you for your feedback! Could you please specify the template from which this error came from?

**Comment by YellowFoxH4XOR** [comment]
@FlorentLvr https://github.com/jupyter-naas/awesome-notebooks/pull/2311 this PR should fix this bug as well even though this was due to replication of code from jupyter notebook to simple python script.

**Comment by jtiscione** [comment]
I haven't used Jupyter in several years so I was squinting at that punctuation. PR looks good.
