### ISSUE TITLE
Python[Convert audiofile from wav to mp3] - Download ffmpeg mv command is failing due to newer version 

### ISSUE THREAD

**Issue by YellowFoxH4XOR** [jupyter-naas/awesome-notebooks#2310]
**Describe the bug**
Wget commands in the download ffmpeg gives the newer version binary but there is a static version tied to mv command which makes the notebook prone to failure.

**To Reproduce**
1. Go to 'awesome-notebooks/Python/Python_Convert_audiofile_from_wav_to_mp3'
2. Click on 'run'
3. Scroll down

**Expected behavior**
The notebook should convert the wav to an mp3 file as expected.

**Screenshots**

**Additional context**

**Comment by FlorentLvr** [comment]
@YellowFoxH4XOR, good catch! 🙏
