### ISSUE TITLE
As a contributor, I want to use logo of the source tool in the notebook I make

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#2333]
I want to be able to put the logo at the root of the folder. 
Then push/merge and have the logo displayed inside github. 
I also need to see this logo inside the Naas Search, and make sure that if I click on the "Open In Naas Lab" button, I have the logo displayed inside the opened notebook in the Lab.

**Comment by Dr0p42** [comment]
## What needs to be done for that

- Get logos for each tool we have in the project.
- Store logo `.github/assets/logos/` the name of the logo needs to be the name of the directory it will be applied to.
 - Example: For `awesome-notebook/Notion` it will need to be `.github/assets/logos/Notion.png`
- CI/CD: On merge on master we need to: 
 - Upload each `.github/assets/logos` in the S3 bucket `arn:aws:s3:::naasai-public`
 - Update all notebooks to force the use of the logo stored in `.github/assets/logos` (use the public link from the S3 bucket). Commit and push.
 - In the json being sent to Algolia, add a `image_url` (using the S3 public link of the logo).
