### ISSUE TITLE
Linkedin - Create finetuning dataset from Profile information

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#2335]
As a user, I want to create a fine-tuning dataset from Profile information.
Example from what I did: https://docs.google.com/spreadsheets/d/176pEpSdtCcjeKkULdujcQ1otNTU-dv7BL69RsM4rLPI/edit#gid=0

**Comment by FlorentLvr** [comment]
Will be done in abi project
