### ISSUE TITLE
AI for Work - Create chat plugin

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#2341]
This notebook will show how to create a chat plugin for work. It will be usefull for organizations to create a chatbot to automate customer service.

**Comment by FlorentLvr** [comment]
🚀 Branch and draft template (generated by AI) have been created and pushed. You should work on: 
- Branch: [2341-ai-for-work-create-chat-plugin](https://github.com/jupyter-naas/awesome-notebooks/tree/2341-ai-for-work-create-chat-plugin)
- Notebook: [AI%20for%20Work/AI_for_Work_Create_chat_plugin.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/2341-ai-for-work-create-chat-plugin/AI%20for%20Work/AI_for_Work_Create_chat_plugin.ipynb)

**Comment by FlorentLvr** [comment]
Here is the google sheet links: https://docs.google.com/spreadsheets/d/18HChEH5ezs8p8pi1Y-u9yQFZdBPtMlONNjrHiH0VT3U/edit#gid=205410028

@jravenel, could you please provide me the 150 templates to be generated?

**Comment by FlorentLvr** [comment]
@jravenel, do you have a list in mind?

**Comment by jravenel** [comment]
hey @FlorentLvr I have made the selection and added a Naas column with 'W44-2023' (last week cut off)
Total: 182 templates 
Department: Marketing

![Screenshot 2023-11-08 at 15 38 44](https://github.com/jupyter-naas/awesome-notebooks/assets/21052349/eab35795-9ebf-4d77-9371-3f718eff64a8)
