### ISSUE TITLE
Pandas - Performing mathematical operations on dataframe

### ISSUE THREAD

**Issue by siddharth2011** [jupyter-naas/awesome-notebooks#2368]
**Problem Description**
This notebook will help the users to perform mathematical operation like, sum, median, mode, mean, standard deviation on the data present in a column of dataframe. Mean unveils the average, mode reveals the most frequent, median marks the middle ground, standard deviation gauges data dispersion, and sum tallies the grand total. Computing these will help to analyze and understand the data in a better fashion.

**Comment by siddharth2011** [comment]
@FlorentLvr  was busy with work. Could not accept guthub invite. Could you please send it again?

**Comment by FlorentLvr** [comment]
> @FlorentLvr was busy with work. Could not accept guthub invite. Could you please send it again?

Invitation sent!
