### ISSUE TITLE
Add connection templates in tools

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#2392]
Add a template to explain how to connect to a tool and add a standardize secret on naas

tags: #connectors #connections

**Comment by jravenel** [comment]
Name the template: "Tool - Setup Connection" 

Input 
- get your credentials
- setup variables 
Model 
- add secrets
Output
- show dataframe with the secrets added


**Tools:** 
1. AWS 
2. Notion 
3. LinkedIn
4. HubSpot 
5. Google Drive 
6. Google Sheet
7. GitHub 
8. Algolia
9. Buffer 
10. HuggingFace // to add
11. OpenAI 
12. LinkedIn Sales Navigator 
13. NewsAPI
14. PostgreSQL
15. MongoDB
16. Qonto
17. Spotify
18. Trello
19. Typeform
20. Youtube 

*Not Priority*
- Airtable
- Microsoft Sharepoint 
- Zapier

**Comment by FlorentLvr** [comment]
Merged as of today:
✅ AWS
✅ Buffer
✅ GitHub
✅ HubSpot
✅ LinkedIn
✅ Notion
✅ OpenAI

**Comment by FlorentLvr** [comment]
Merged as of today:
✅ Algolia
✅ Clockify
✅ Bitly
✅ Harvest
✅ Trello
