### ISSUE TITLE
OpenAI - Use GPT-4

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#2402]
This notebook will show how to use GPT-4 from OpenAI to generate text. It will be usefull for organizations that need to generate text from a given prompt.

**Comment by FlorentLvr** [comment]
🚀 Branch and draft template (generated by AI) have been created and pushed. You should work on: 
- Branch: [2402-openai-use-gpt-4](https://github.com/jupyter-naas/awesome-notebooks/tree/2402-openai-use-gpt-4)
- Notebook: [OpenAI/OpenAI_Use_GPT4.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/2402-openai-use-gpt-4/OpenAI/OpenAI_Use_GPT4.ipynb)

**Comment by jravenel** [comment]
GPT4
![image](https://github.com/jupyter-naas/awesome-notebooks/assets/21052349/c72f5d2c-aff6-4232-a684-fe286081e242)
