### ISSUE TITLE
Github - Get list of profiles that starred repo

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#243]
Input:
Repo url

Model:
Get list of people with login (pseudo), email, firstname, lastname, date if possible

Ouput:
Return dataframe withall thoses columns:  REPOSITORY_URL , FIRSTNAME, LASTNAME, LOGIN, DATE

https://docs.github.com/en/rest/reference/repos#get-community-profile-metrics

**Comment by jravenel** [comment]
Hey @billounet, @SanjuEpic has done this PR, you can see it here: https://github.com/jupyter-naas/awesome-notebooks/blob/master/Github/Github_Get_starred_members.ipynb

Hope it's ok for you. Looking forward to see you on a new issue :).
