### ISSUE TITLE
Fixes on Character templates

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#2439]
- [ ] Image are broken, since we used the link from ImagineAPI server that was deleted by mistake with no backup :s. 
- [ ] 's should be removed as the AI characters are not the property of the person they simulate

**Comment by FlorentLvr** [comment]
Can you please explain a bit more, I don't see any issue on my side: 
<img width="741" alt="image" src="https://github.com/jupyter-naas/awesome-notebooks/assets/48032461/b19cd6d1-ec01-4584-afa3-fa98a049d25c">

**Comment by jravenel** [comment]
Yes of course, here in the chat, I have a Madonna_3 image
![Screenshot 2023-12-06 at 18 59 13](https://github.com/jupyter-naas/awesome-notebooks/assets/21052349/0e69e201-3b41-4f7e-98b2-1443ed289a78)


But in awesome-notebooks, it's not the same name.
![Screenshot 2023-12-06 at 18 59 53](https://github.com/jupyter-naas/awesome-notebooks/assets/21052349/59666d24-5725-419d-bc33-1ab8746a44ea)

any idea why?
