### ISSUE TITLE
Logos and button to donwload KO

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#2490]
I cannot visualize logo of button in a notebook

**Comment by jravenel** [comment]
And idea why guys?

**Comment by srini047** [comment]
@jravenel Do you mean only on the Github?

**Comment by jravenel** [comment]
yes @srini047, can' you see this?
<img width="981" alt="Screenshot 2024-01-16 at 15 59 08" src="https://github.com/jupyter-naas/awesome-notebooks/assets/21052349/32c0c871-e37f-4067-a211-4027a3de5c78">

**Comment by srini047** [comment]
Yes, even I noticed. Seems to work fine both locally and as well as in Naas lab. Seems to be a issue with Github 👀

**Comment by FlorentLvr** [comment]
Fixed on GitHub
