### ISSUE TITLE
Naas Chat - Create Chat

### ISSUE THREAD

**Issue by FlorentRvl** [jupyter-naas/awesome-notebooks#2507]
- Create chat
- Create chat completion
- Create plugin completion
- List ai models
- Stop chat completion
- Get long lived token

**Comment by FlorentLvr** [comment]
🚀 Branch and draft template (generated by AI) have been created and pushed. You should work on: 
- Branch: [2507-naas-chat-create-chat](https://github.com/jupyter-naas/awesome-notebooks/tree/2507-naas-chat-create-chat)
- Notebook: [Naas%20Chat/Naas_Chat_Create_Chat.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/2507-naas-chat-create-chat/Naas%20Chat/Naas_Chat_Create_Chat.ipynb)
