### ISSUE TITLE
Pipedrive - Add an activity

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#2512]
This notebook adds a new activity in Pipedrive. It includes the 'more_activities_scheduled_in_context' property in the response's additional_data, which indicates whether there are more undone activities scheduled with the same deal, person, or organization.
```
```

**Comment by FlorentLvr** [comment]
🚀 Branch and draft template (generated by AI) have been created and pushed. You should work on: 
- Branch: [2512-pipedrive-add-an-activity](https://github.com/jupyter-naas/awesome-notebooks/tree/2512-pipedrive-add-an-activity)
- Notebook: [Pipedrive/Pipedrive_Add_an_activity.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/2512-pipedrive-add-an-activity/Pipedrive/Pipedrive_Add_an_activity.ipynb)

**Comment by abhigyan631** [comment]
Is this issue still open to work with?

**Comment by FlorentLvr** [comment]
> Is this issue still open to work with?

Hello, TY for reaching out but I am working on this issue. Would you like to contribute on another one? Are you working with Pipedrive? 🙏

**Comment by abhigyan631** [comment]
No, I was not sure whether anyone is still working with Pipedrive, I can start with something else, please let me know if you have something to work on, thank you.

**Comment by FlorentLvr** [comment]
> No, I was not sure whether anyone is still working with Pipedrive, I can start with something else, please let me know if you have something to work on, thank you.

Ok ok. Did you check other issues you would like to contribute on? Are you working in a specific tool that you would like to showcase with templates? :)

**Comment by abhigyan631** [comment]
For that I can go through the whole repo and test out the tools, can you please suggest something like a good first-issue thing that I can focus on? Like something I can set up locally without the need for any deployment on cloud services or things like that? Thank you.
