### ISSUE TITLE
feat: Create notebooks for CRUD operations using naas-python for assets

### ISSUE THREAD

**Issue by Dr0p42** [jupyter-naas/awesome-notebooks#2524]
### Description
Create a series of Jupyter notebooks to demonstrate the usage of naas-python for performing CRUD operations on assets. Each notebook should focus on a specific type of request, such as creating a assets, getting a assets, updating a assets, and deleting a assets. These notebooks will serve as a comprehensive guide for users looking to work with assets using naas-python.

### Tasks
1. Create a notebook for creating a assets using naas-python.
2. Develop a notebook for retrieving a assets using naas-python.
3. Implement a notebook for updating a assets using naas-python.
4. Create a notebook for deleting a assets using naas-python.
5. Ensure all notebooks are well-documented and easy to understand.

**Comment by FlorentLvr** [comment]
@l-loic, i checked your notebook and it does respect our framework. 
Could you please adapt it? 🙏 TY
https://github.com/jupyter-naas/awesome-notebooks?tab=readme-ov-file#how-is-organized-a-template
