### ISSUE TITLE
GitHub - List all comments and reactions from Closed Issues on a given repository

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#2535]
Input
- https://github.com/jupyter-naas/awesome-notebooks

Model:
- List all closed issues from repo
- Get comments and reactions from issue and concatenate in a dataframe

Output
- DataFrame

**Comment by FlorentLvr** [comment]
@varshakumarr, any udpates on this issue?

**Comment by varshakumarr** [comment]
> @varshakumarr, any udpates on this issue?

I am almost done!
