### ISSUE TITLE
Notion - Generate GSheets row for new items in Notion DB

### ISSUE THREAD

**Issue by tparente-ui** [jupyter-naas/awesome-notebooks#276]
Organize your key data effortlessly with this integration. Once it’s in place, this Notebook automatically sends each item added to a Notion database to a new row in a specified Google Sheets spreadsheet. Manage your KPIs and other details without having to manually juggle key data between platforms.

Adapted from this zap: https://zapier.com/apps/google-sheets/integrations/notion/597581/generate-google-sheets-rows-for-new-items-in-notion-databases

The Notebook can be like:

**Input**:

- Schedule:
    - Once your notebook have been executed completely, you can push to production by removing the "#"
    - `import naas`
    - `naas.scheduler.add(cron="*/15 * * * *")`every 15 min
- Import librairies
- Get the Notion DB
- Get the Gsheet DB

**Model**:

- Compare the Gsheet DB with the Notion one
    - in notion take the unique key
- Get the missing item
- Format it for the Spreadsheet Row

**Output**:

- Push the Spreadsheet Row into gsheet

**Comment by Arun-kc** [comment]
Hi @tparente-ui and @jravenel, I have started looking into this issue. Will be doing a PR soon!! 🙌
