### ISSUE TITLE
Notion - Add items to Notion DB from new rows in GSheets

### ISSUE THREAD

**Issue by tparente-ui** [jupyter-naas/awesome-notebooks#277]
Keep projects and workflows up to date without having to leave your spreadsheet! This integration automatically creates an item in a specified database in Notion as soon as it’s added to a new row in a specified Google Sheets spreadsheet.

Adapted from this zap: https://zapier.com/apps/google-sheets/integrations/notion/597582/add-items-to-notion-databases-from-new-rows-in-google-sheets

The Notebook can be like:

**Input**:
- Schedule:
    - Once your notebook have been executed completely, you can push to production by removing the "#"
    - `import naas`
    - `naas.scheduler.add(cron="*/15 * * * *")`every 15 min
- Import librairies
- Get the Notion DB
- Get the Gsheet DB

**Model**:
- Compare the Gsheet DB with the Notion one
    - in notion take the unique key
- Get the missing item from the sheet
- Format it for the Notion DB

**Output**:
- Push the item to the Notion DB

**Comment by poojashri** [comment]
Hi @tparente-ui @jravenel, I would like to work on this issue.
I will now explore the respective APIs and update my work here.

**Comment by jravenel** [comment]
> Hi @tparente-ui @jravenel, I would like to work on this issue. I will now explore the respective APIs and update my work here.

Hello Pooja, thanks for your message, no need to explore API we already have the gsheet and notion drivers :) It's a matter of combining them together with some logic in the middle.

https://documentation.naas.ai/drivers/notion
https://documentation.naas.ai/drivers/google-sheets

**Comment by poojashri** [comment]
That's great! i am spending time here, let me give more updates on the same. Meanwhile can the issue be assigned and moved to in progress. -Thanks, Pooja

**Comment by jravenel** [comment]
Excellent. I let you push this into "in progress" once you are on it 🤙

**Comment by poojashri** [comment]
Hi Jeremy,

I went through Gsheets and Notion drivers and have more clarity about this workitem. Below is my understanding of this issue and how to resolve it. I'll start working on it after your confirmation:

1. Connect with Gsheet and get all rows using the gsheet driver's get method
2. Connect with NotionDB and get all pages using the Notion Databases driver's get method
3. Compare the list of pages from notion db with the rows returned from gsheet and add non matching rows to a list
4. Create new pages in Notion db for each row in the non matching list using the Notion Pages driver's create method
5. For each created page, update the properties using the Notion Pages driver's retrieve and update methods

Let me know if I am missing something or if everything in order then i'll finish this and raise a PR.

**Comment by jravenel** [comment]
Hey @poojashri you got it ! The only missing part is the use the scheduler every x minutes to make it run in production.

**Comment by jravenel** [comment]
@poojashri checking in if you need help. All good?

**Comment by poojashri** [comment]
Hi Jeremy, little caught up with another stuff, will try to raise the PR, today EOD.

**Comment by poojashri** [comment]
Hi @jravenel I facing a permissions error, while pushing my notebook. If it's resolved I can push my wor here, I have got all the parts correct, aside from the update notion page in the end, i.e. while updating page(page.update()) in notion. It would be great if I could create a MR and show this to you.... Hope to hear back soon, Have also asked this on the Slack channel.

**Comment by jravenel** [comment]
Hey @poojashri can you please share the screenshot of the problems you are facing?
What do you mean by MR?
Thanks a lot.

**Comment by poojashri** [comment]
![docummentation error](https://user-images.githubusercontent.com/5314545/149560607-460dcb37-b8b4-4d7f-a038-1caff381d57e.png) Issue with git permissions
![Error in Notion page Update method ](https://user-images.githubusercontent.com/5314545/149560612-8b5fb2c5-ab76-4a84-8940-efa862349291.png) --> The page creation in the notion db went fine, but while updating the new rows, into the notion page I am getting this error... Can you suggest what's wrong on my end.. It's expecting a type for each property..properties returned from Create page driver is a dictionary, hence only key value pair I am getting. 
![git error](https://user-images.githubusercontent.com/5314545/149560615-8289a686-c55f-40fd-857d-9fc998896a5f.png)
I meant merge request to the master branch...

**Comment by jravenel** [comment]
Hey @poojashri 

I don't understand why you have a documentation.naas.ai page error when you are updating new rows ... it seems completely unrelated. can you share the code snippet you are using to get this page?

→ It seems you are in vs code. Can you do it from naas.ai interface ? creating a branch and pushing with personal access token as password?
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
