### ISSUE TITLE
Notion - Send emails via Gmail with new items in Notion DB

### ISSUE THREAD

**Issue by tparente-ui** [jupyter-naas/awesome-notebooks#282]
Set up this Notebook to effortlessly keep your stakeholders in the loop about updates to projects and workflows. As soon as it’s active, this integration automatically sends a custom email via Gmail to a specified recipient when a new item is added to your Notion database.

Adapted from this zap: https://zapier.com/apps/gmail/integrations/notion/597574/send-emails-via-gmail-with-new-items-in-notion-databases

The Notebook can be like:

**Input**:
- Schedule:
    - Once your notebook have been executed completely, you can push to production by removing the "#"
    - `import naas`
    - `naas.scheduler.add(cron="*/15 * * * *")`every 15 min
- Import librairies
- Get the Notion DB
- Open the file which the all mails sent

**Model**:
- Compare the items presents in the Notion DB with the mails list from the file
    - in notion take the unique key
- Get the missing items from Notion
- Format it into mail formar

**Output**:
- Send the mail

**Comment by Arun-kc** [comment]
Made a PR for this issue. 😄
