### ISSUE TITLE
WSR - Create a world map of COVID Active cases

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#290]
Take the work from :
https://github.com/jupyter-naas/awesome-notebooks/blob/master/Johns%20Hopkins/Johns_Hopkins_Covid19_Active_Cases.ipynb 

and create a world map with this design convention:
https://github.com/jupyter-naas/awesome-notebooks/blob/master/Plotly/Plotly_Mapchart_world.ipynb

Add the notebook template in the WSR (world situation room) folder in naas awesome-notebooks repo.

**Comment by jravenel** [comment]
@krishkatyal you are welcome to work on this and ask questions if needed.

**Comment by jravenel** [comment]
Here are the steps to contribute:
Step by step process: 

1→ Open free account on Naas.ai
2→ Clone awesome-notebooks repo
3→ Change status of this Issue to "In progress" so we can know you are working on it
4→ Create new branch with name of issue
5→ Create folder if needed in awesome-notebooks folder, and adapt notebook template to the current use case (check out how Linkedin templates are done for example)
6→ Once you are happy with the result, commit to the branch
7→ Open a pull request and tag me as a reviewer with a little comment on what you have done, but most of the explanations should be in the notebook itself
8→ Change status of this Issue to "Review" so we can know a review is pending
9→ Link the PR to this issue for tracking in the backlog
10→ Expect a feedback and merge in the next 48h :)

**Comment by RedaAllab** [comment]
@jravenel @jravenel 
Hello guys ! I made the necessary changes to make this template work.
Please check it.
