### ISSUE TITLE
Yahoo Finance - Get USD/INR daily and create chart.

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#293]
Title: Yahoo Finance - Get USD/INR daily and create chart.
Description: 

Input: 
ticker =. "INR..."

Model: 
- get the data 
- plot the data 
- generate markdown text

Output: 
- show graph

**Comment by carloocchiena** [comment]
issues still open? may I help? I have already forked and created the import for USDINR data on my local naas.ai account 
![image](https://user-images.githubusercontent.com/57464184/150507506-57ff5861-b93e-4d00-93a5-037342722c69.png)

**Comment by jravenel** [comment]
Yes @carloocchiena, @megha2907 is assigned to it for her first contribution.

**Comment by megha2907** [comment]
@jravenel I have created a pull request. Please review and let me know any required changes

https://github.com/jupyter-naas/awesome-notebooks/pull/308

**Comment by megha2907** [comment]
@jravenel @FlorentLvr 

While adding or removing dependencies, getting message as "Your file is added/removed to/from production" Is it an expected behaviour?
2. Also, Have used send email code snippet referring to documentation, but the file is not getting attached to sent email.
Please suggest

**Comment by megha2907** [comment]
@FlorentLvr Is PR completed as its still showing under New Issue. Is there anything that's need to be done on the issue? Please let me know
