### ISSUE TITLE
Yahoo Finance - Get ETH/USD daily and create chart

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#294]
Title: Yahoo Finance - Get ETH/USD daily and create chart
Description:

Input:
ticker =. "ETH-USD"

Model:
- get the data
- plot the data

Output:
show graph

**Comment by jravenel** [comment]
@PeaceBello as discussed here is the first contribution to get started :)

**Comment by PeaceBello** [comment]
@jravenel , alright Ill get started

**Comment by jravenel** [comment]
@PeaceBello can you please attach PR to this Issue ?
