### ISSUE TITLE
Github - Track of awesome notebooks created over time

### ISSUE THREAD

**Issue by SanjuEpic** [jupyter-naas/awesome-notebooks#302]
**Objective:** To keep track of the number of notebooks that evolved over the time

## Input:

- Repo url

## Model:
- Get information regarding commits i.e last committed date and commit name or notebook name.

## Output:
- Line chart for the no of awesome notebooks over time in days/month

**Comment by jravenel** [comment]
@SanjuEpic just added it to In progress in community roadmap.
