### ISSUE TITLE
TikTok - Get stats from API

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#307]
This article explains the process: https://towardsdatascience.com/how-to-collect-data-from-tiktok-tutorial-ab848b40d191

**Comment by calok64** [comment]
@jravenel This is working example and updated API https://pypi.org/project/PyTikTokAPI/#get-trending-videos
The link which is in the description has some issues in the API library.

Using the one from pypi.org gives the output. We are working on its model now

**Comment by jravenel** [comment]
@calok64 do you have a template to share? As discussed, templates are necessary building blocks for the content engine.

**Comment by calok64** [comment]
@jravenel Here is the PR
https://github.com/jupyter-naas/awesome-notebooks/pull/407
