### ISSUE TITLE
Metrics Store - Follow connections

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#321]
Please below the specification:
https://www.notion.so/naas-official/Number-of-connections-f22d2df11f574f7f96bdc16ef9be5796

**Comment by RiddhiDeshpande222** [comment]
@FlorentLvr I have created the PR. Kindly review and let me know the suggestions
https://github.com/jupyter-naas/awesome-notebooks/pull/335
