### ISSUE TITLE
Instagram - Get stats from business account

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#323]
We can get insights into follower counts, video views, engagement, reach, and more! This tutorial explains it:
https://www.youtube.com/watch?v=zwTohy42np4

Ideally, make one template per metric in the PR.

**Comment by jravenel** [comment]
Hi @mohamedabidi97 here is the issue we discussed about. 
The idea is to follow the pattern that we have done with [LinkedIn get post feed](https://github.com/jupyter-naas/awesome-notebooks/blob/master/LinkedIn/LinkedIn_Get_posts_feed_from_profile.ipynb) 

Here is the suggested content of the first notebook: 

Input :
- API KEY
- PROFILE 

Model: 
- Get list of posts and associated stats (views, likes, comment)

Output: 
- Display dataframe
 

Please follow the following process to raise the PR: 
Step 1: Open free account on [Naas.ai](http://naas.ai/)
Step 2: Clone awesome-notebooks repo
Step 3:  Change status of this Issue to “In progress” so we can know you are working on it
Step 4: Create new branch with a short name of the issue (ex: “gsheet-notion”)
Step 5: Create folder named with the source tool (if it does not already exist in the awesome-notebooks folder), and adapt notebook template to the current use case.
Step 6:  Once you are happy with the result, commit to the branch
Step 7: Open a pull request and tag me as a reviewer with a little comment on what you have done, but most of the explanations should be in the notebook itself
Step 8:  Change status of this Issue to “Review” so we can know a review is pending
Step 9:  Link the PR to this issue for tracking in the backlog
Step 10:  Expect a feedback and merge in the next 48h-72h

Good for you?

**Comment by mohamedabidi97** [comment]
Yes that’s good for me.
Thanks
