### ISSUE TITLE
RemoteOk - Post daily jobs not updating

### ISSUE THREAD

**Issue by SanjuEpic** [jupyter-naas/awesome-notebooks#368]
Areas to debug:
1. Changes to be made in the "Setup slack channel configuration" block
2. Avoiding duplication of jobs in the sheets
3. Sending jobs to the slack channel should be set up perfectly

**Comment by SanjuEpic** [comment]
Hi @FlorentLvr and @jravenel!
The existing code was running successfully and updating in the excel sheet, but not in the slack due to a small problem with the data frame column called i.e
this line needs to be replaced with this code -> "row.url -> row.URL"
I overlooked this statement previously, sorry for the inconvenience.

Will be making a new commit for this change :)

**Comment by FlorentLvr** [comment]
Thanks @SanjuEpic ! It's fixed.
