### ISSUE TITLE
AWS - Run query on  S3

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#406]
Today, I store my petabytes of data in a bucket S3, I would be able to query those files directly through naas.

**Comment by jravenel** [comment]
Duplicate with https://github.com/jupyter-naas/awesome-notebooks/issues/1013 @FlorentLvr @Dr0p42 ?

**Comment by FlorentLvr** [comment]
> Duplicate with #1013 @FlorentLvr @Dr0p42 ?

Yes, it has been done :
- [AWS - Read dataframe from S3 #1013](https://github.com/jupyter-naas/awesome-notebooks/issues/1013)
- [AWS - Send dataframe to S3 #1012](https://github.com/jupyter-naas/awesome-notebooks/issues/1012)

I close issue with comment
