### ISSUE TITLE
Notion - Generate Google Sheets rows for new items in Notion database

### ISSUE THREAD

**Issue by Dr0p42** [jupyter-naas/awesome-notebooks#422]
<img width="10%" alt="Naas" src="https://landen.imgix.net/jtci2pxwjczr/assets/5ice39g4.png?w=160"/>

# Notion - Generate Google Sheets rows for new items in Notion database

**Tags:** #notion #googlesheets #operations #automation

**Author:** [Firstname Lastname](https://linkedin.com/in/yourlinkedinid)

Here, you will create new row in your Google Sheets spreadsheet for new items your Notion database.
<br/>References :
- Google Sheets templates : [https://docs.naas.ai/templates/google-sheets](https://docs.naas.ai/templates/google-sheets)
- Notion templates : [https://docs.naas.ai/templates/notion](https://docs.naas.ai/templates/notion)

### Import libraries

```python
from naas_drivers import notion, gsheet
import naas
```

### Setup Notion

- [Get your Notion integration token](https://docs.naas.ai/drivers/notion)
- Share integration with your database

```python
# Enter Token API
NOTION_TOKEN = "*****"

# Enter Database URL
DATABASE_URL = "https://www.notion.so/********"
```

### Setup Google Sheets

- Share your sheet with our service account : 🔗 [naas-share@naas-gsheets.iam.gserviceaccount.com](mailto:naas-share@naas-gsheets.iam.gserviceaccount.com)

```python
# Spreadsheet URL
SPREADSHEET_URL = "------"

# Sheet name
SHEET_NAME = "Sheet1"
```

### Setup Naas

```python
# Schedule your notebook every hour
naas.scheduler.add(cron="0 * * * *")

#-> Uncomment the line below to remove your scheduler
# naas.scheduler.delete()
```

### Get dataframe from Notion database

```python
db_notion = notion.connect(NOTION_TOKEN).database.get(DATABASE_URL)
df_notion = db_notion.df()
```

### Get dataframe Google Sheets spreasheet

```python
df_gsheet = gsheet.connect(SPREADSHEET_URL).get(sheet_name=SHEET_NAME)
df_gsheet
```

### Get new entries in Notion database

```python
def my_function():
	...
	return

df_new = my_function()
df_new 
```

### Send data to Google Sheets

```python
# Send data to Google Sheets
gsheet.connect(SPREADSHEET_URL).send(
    sheet_name=SHEET_NAME,
    data=df_new,
		append=True,
)
```

**Comment by Dr0p42** [comment]
🚀 Branch and template have been created and pushed.

You should work on:
- Branch: [422-notion-generate-google-sheets-rows-for-new-items-in-notion-database](https://github.com/jupyter-naas/awesome-notebooks/tree/422-notion-generate-google-sheets-rows-for-new-items-in-notion-database)
- Notebook: [Notion/Notion_Generate_Google_Sheets_Rows_For_New_Items_In_Notion_Database.ipynb](https://github.com/jupyter-naas/awesome-notebooks/blob/422-notion-generate-google-sheets-rows-for-new-items-in-notion-database/Notion/Notion_Generate_Google_Sheets_Rows_For_New_Items_In_Notion_Database.ipynb)

**Comment by FlorentLvr** [comment]
Already done by @poojashri ! Just renamed the template in master.
