### ISSUE TITLE
GitHub - Add new Github issues as page in Notion database

### ISSUE THREAD

**Issue by Dr0p42** [jupyter-naas/awesome-notebooks#432]
<img width="10%" alt="Naas" src="https://landen.imgix.net/jtci2pxwjczr/assets/5ice39g4.png?w=160"/>

# GitHub - Add new Github issues as page in Notion database

**Tags:** #github #notion #operations #automation

**Author:** [Firstname Lastname](https://linkedin.com/in/yourlinkedinid)

This notebook is used to create Notion page in a database when a new Github issue is created.

<br/>References :
- Notion driver:
- Github SDK: [https://github.com/PyGithub/PyGithub](https://github.com/PyGithub/PyGithub)

### Import libraries

```python
import naas
```

### Setup Notion

```python
# Notion token
notion_token = "..."

# Specify database id
notion_database_id = "..."

notion.connect(notion_token)
```

### Setup Github

```python
# Github token
github_token = "..."

# Github repo on which we want to create issues.
github_repo_name = "..."

gh_client = Github(github_token)
```

### Setup Naas

```python
# Schedule your notebook every 15 minutes.
naas.scheduler.add(cron="*/15 * * * *")

#-> Uncomment the line below to remove your scheduler
# naas.scheduler.delete()
```

### Query notion database

```python
db_notion = notion.connect(NOTION_TOKEN).database.get(notion_database_id)
df_notion = db_notion.df()
```

### Get Github issues

```python
...
```

### Create notion page from Github issue

```python
def notion_page_from_gh_issue(issue, notion_database_id):
	...
```

### Iterate over each issue.

```python
for issue in gh_issues:
	notion_page_from_gh_issue(issue, notion_database_id)
	print(f'✅ Notion page created for issue {issue.url...}')
```

**Comment by SanjuEpic** [comment]
[Here](https://billowy-lemming-95e.notion.site/5d05fd69dc334985a8c0d0ebdaf33837?v=b20e25eadddd4756a754d9c7d23be68d) is the temporary output of this notebook

Image preview:
![sample_output_notion](https://user-images.githubusercontent.com/57587354/162808617-746f311f-eeb7-4e1d-95c2-cb2cca98ae6a.png)
