### ISSUE TITLE
Python - Download image from URL

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#434]
This template should show how to download an image from a URL

**Comment by israelabraham** [comment]
Hi @FlorentLvr, I'd like to take this up!

**Comment by israelabraham** [comment]
Hi @FlorentLvr, I'd like to take this up!

**Comment by jravenel** [comment]
@israelabraham I just added you to the opensource contributor team, please make sure to follow the contribution guide on the README and let me know if you need help

**Comment by israelabraham** [comment]
> @israelabraham I just added you to the opensource contributor team, please make sure to follow the contribution guide on the README and let me know if you need help

Definitely, thank you very much.

**Comment by jravenel** [comment]
Welcome @israelabraham 🙂
