### ISSUE TITLE
LinkedIn - Send people who view my profile in Notion

### ISSUE THREAD

**Issue by Octonathan** [jupyter-naas/awesome-notebooks#456]
I want to see the number people who view my profile over the year.

**Comment by jravenel** [comment]
Hi @Octonathan, are you referring to this view? 

<img width="845" alt="Screenshot 2022-04-14 at 15 40 30" src="https://user-images.githubusercontent.com/21052349/163414129-8eb41c21-aedc-4483-8183-af1a3ce0eeef.png">

What would be your use after getting this info? 
Thanks for the precision so we can start digging if it's doable.

**Comment by Octonathan** [comment]
Yes, exactly! The objective is to send the number of views of the linkedin profile in a Notion database and to create graphs like the one in attachment afterwards.

If possible, to put all the people who visited our Linkedin profile in a Notion database (in order to send them a connection request later with another automation)

Here is an example of a notion database in which we could send the data: https://octolio.notion.site/3da040100c9c47e8889719a7a07cc20f?v=b6f91d0a7478449ea438593af2588f9b

**Comment by FlorentLvr** [comment]
@Octonathan , i edited this issue to fit to your need :)
