### ISSUE TITLE
Google Analytics - Get traffic data

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#52]
GA enables you to get traffic data from your website 

Input : 
Google API Key => to be investigated

Model : 
Transform data from GA into a Dataframe

Output : 
- WEBSITE
- DATE
- TRAFFIC (unique visitors)
... any other KPI for traffic tracking

Created: March 24, 2021
https://naas.canny.io/requests/p/google-analytics-get-traffic-data

**Comment by Charles-de-Montigny** [comment]
I would like to be assigned to this issue!

**Comment by Dr0p42** [comment]
> I would like to be assigned to this issue!

Awesome, let us know if you need anything 💪

**Comment by Charles-de-Montigny** [comment]
Hey, I am under the impression that I haven't been add to the project as a contributor. @Dr0p42

**Comment by Dr0p42** [comment]
> Hey, I am under the impression that I haven't been add to the project as a contributor. @Dr0p42

Indeed, it should be good now 👍
