### ISSUE TITLE
Yahoo Finance - Get Brent Crud Oil trend and predictions 

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#579]
Using the same kind of model as https://github.com/jupyter-naas/awesome-notebooks/blob/master/YahooFinance/YahooFinance_Send_daily_prediction_to_Email.ipynb

Without the email sending part, but where the end is an HTML content with: 
- Logo → 🛢 (here an emoji but could be a URL in input) 
- Ticker | Full name → BZ=F | Brent Crude Oil
- Value | Variation in value (Variation in %) → 79.1411 | +8.9411 (+12.74%) with color coding red/green
- Graph with prediction 
- Text: 
""
In +DATA_POINT days, basic ML models predict the following prices: 

 **arima**: ARIMA
 **svr**: SVR
 **linear**: LINEAR
**compound**: COMPOUND
""

The idea behind it is to be able to create standalone analysis that can be later used in a data product by combining different templates from different market values together.

**Comment by jravenel** [comment]
@ayoub-berdeddouch if you want to help on this today to end hacktoberfest that would be great, tomorrow I plan to do a project with @Dr0p42 where we are going to create a newsletter that could use it. Btw we want to make it livestream if you want to join 2PM-4PM CET. 

Can you start working on it today? 
Are in interested in the livestream tomorrow?

**Comment by ayoub-berdeddouch** [comment]
Alright, @jravenel  I will work on it! 
For the Livestream, I would be traveling so I could miss it, but if there were a record of it, that would be great!

**Comment by jravenel** [comment]
Cool! If you think you can make the PR by tonight we will use your template as a base to build the data product tomorrow
