### ISSUE TITLE
Hugging Face - Create text summary

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#71]
Input: 
- Text string 

Model: 
Call Hugging face summarize naas drivers

Output : 
- Text string

**Comment by sachindavra** [comment]
Hi @jravenel, Is this a python issue?

**Comment by sachindavra** [comment]
Hi @jravenel,

Thanks for your reply.
If this is a good first issue, I would like to work on this. I am new to the opensource.
Could you explain the issue in detail.

**Comment by jravenel** [comment]
Hey @sachindavra, 

thanks! 

Here is the video explaining how to contribute with an example : https://www.youtube.com/watch?v=tJ_JW9U7pXA

@gagan3012 has done a driver (https://github.com/jupyter-naas/drivers/pull/83) that we need to document in a template. 
You are welcome to help :)
