### ISSUE TITLE
CSV - Return on Margin

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#747]

**Comment by Mukhtarmid** [comment]
@jravenel @FlorentLvr would you put some light on this issue? I can easily take it.

**Comment by jravenel** [comment]
The objective of all these "CSV - ...." issues were to create graphs based on raw CSV data. I don't think it's our priority anymore to be honest @Mukhtarmid, can we find another issue to assign to you?

**Comment by Mukhtarmid** [comment]
@jravenel, Sure! You can assign me! If I find some issues which suites me, I'll pick up!

**Comment by jravenel** [comment]
> @jravenel, Sure! You can assign me! If I find some issues which suites me, I'll pick up!

Ok then. I'll ping you, we are prioritising the list of templates to be done first with @FlorentLvr this week.
