### ISSUE TITLE
SpaCy - Build a sentiment analysis model using Twitter

### ISSUE THREAD

**Issue by tdubon** [jupyter-naas/awesome-notebooks#761]
To query Twitter data via the Twitter API and perform a binary sentiment analysis.

- Input: Data retrieved using bearer token from the Twitter developer platform. Clean and tokenize data.
- Model: Use spaCy packaged pipeline to classify tweets
- Output: Dataframe, word cloud file, and bar chart

**Comment by tdubon** [comment]
Here is the link to the file: https://app.naas.ai/user/tdubon6@gmail.com/doc/tree/Twitter_Data_Analysis_naas.ipynb

I'm not sure if that's the right way to get it linked to Github, but please let me know.

**Comment by FlorentLvr** [comment]
Hi @tdubon ! 
I hope you are doing well.
I would like to review your work but there is no PR. Would it be please possible to create one ?
Let me know if you have any issue.
Thank you very much :pray:

**Comment by tdubon** [comment]
Hi @FlorentLvr, I created a branch and corresponding PR. Please let me know if I need to change something to the setup/PR, as it's my first time.

Thank you!!

**Comment by jravenel** [comment]
Hi @tdubon, very cool template here but we are having some difficulties to make it run as there is dependencies with : 
- yaml file 
`-/Users/tdubon/twitter/config.yaml`
- json 
`/Users/tdubon/twitter/downloaded_tweets.json`

We might suggest changes on this: 
- put directly the bearer token in the input without YAML 
- move the functions on the model section and leave only: BEARER, QUERY (might need to re-write the function to pass only key words in list), LANG and simple variable to configure to make it simpler for the end user to (he can configure everything at the same place). 
- add a Slack notification output and a scheduler to run every day, this way someone that wants to be notified daily about evolution of certain set of keywords or accounts 

What do you think? 
We can try to suggest changes or do some peer programming with @Dr0p42 on this with you if you have time.

**Comment by jravenel** [comment]
Hi @tdubon we have worked on it with @Dr0p42 to : 
- put directly the bearer token in the input without YAML
- leave in the input section only the config of:  BEARER, TWITTER_QUERY, TWITTER_MAX_RESULT
- move the functions on the model section
- removed the fact that we need save json 
- renamed a few steps to tell what the function does (ex in Output section) 

and we believe it fits better in the SpaCy folder.
Hope you find this review valuable :)

**Comment by tdubon** [comment]
Thank you for finalizing the notebook @Dr0p42! @jravenel I also appreciate the feedback, particularly for future reference.

**Comment by tdubon** [comment]
While this ticket is closed, FYI I made updates to clean the file. I removed the hyperlinks, newline notation and punctuation. This affects the quality of the output. So let me know if I can edit the file to include it.

#remove hyperlinks
df["clean text"] = np.vectorize(cleanup_text)(df["clean text"], r'https?://\S+')

#remove new line notation
df["clean text"] = np.vectorize(cleanup_text)(df["clean text"], '\n[\w]*')

#remove punctuation
df["clean text"] = np.vectorize(cleanup_text)(df["clean text"], '#[\w]*')
