### ISSUE TITLE
HuggingFace - Explore API

### ISSUE THREAD

**Issue by gagan3012** [jupyter-naas/awesome-notebooks#81]
Hello, 
We are looking for demos for the following tasks:

- feature-extraction
- text-classification
- sentiment-analysis
- token-classification
- ner
- fill-mask
- translation

An example of how to do it is given here: https://github.com/gagan3012/awesome-notebooks/blob/nlp/Naas/Naas_NLP_Example.ipynb

**Comment by jravenel** [comment]
Need to rename the naas_drivers.nlp to naas_drivers.hugginface after this task is complete https://github.com/jupyter-naas/drivers/issues/146
