### ISSUE TITLE
Hubspot - Create and assign task 

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#85]
Use API endpoint to create tasks (engagement) in Hubspot

Documentation
https://legacydocs.hubspot.com/docs/methods/engagements/create_engagement
``

Input : 
- Hubspot API Key 
- User assigned to the task 
- Task title 
- Task content. 
- Task due date

Model: 
Post to Hubspot 

Output: 
- Success: "Task created successfully" 
- Fail: "Could not create the task, ask for on hello@naas.ai for more details"

**Comment by calok64** [comment]
@FlorentLvr update the template with required changes and pushed the latest file. You can review it now.

**Comment by calok64** [comment]
@jravenel @FlorentLvr Created files for CRUD tasks
Here is the PR https://github.com/jupyter-naas/awesome-notebooks/pull/370
