### ISSUE TITLE
Twilio - Get Daily reminders by SMS

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#893]
Send Daily SMS template using naas.scheduler feature

**Comment by srini047** [comment]
> @srini047, just add you on this issue as it seems to be something you can easily do using Twilio and naas scheduler. Is that correct?

Yes, absolutely. As long as the Twilio credits are available then we are good to go.

**Comment by srini047** [comment]
Also is there any specific SMS template that needs to be used?

**Comment by FlorentLvr** [comment]
> Also is there any specific SMS template that needs to be used?

No, but you can use this example: 
"Good morning! This is a friendly reminder that you have a workout session scheduled for 7 am today. Don't forget to get up and start your day with some exercise!"

You could send it every day at 6:50 as a reminder. What do you think?

**Comment by srini047** [comment]
> > Also is there any specific SMS template that needs to be used?
> > @srini047
> > No, but you can use this example:
> > "Good morning! This is a friendly reminder that you have a workout session scheduled for 7 am today. Don't forget to get up and start your day with some exercise!"
> 
> You could send it every day at 6:50 as a reminder. What do you think?

Yes, It's absolutely fine. Then I can take `time` and `message` from the user as input and tune the `naas.scheduler` to run at the time specified by the user.
