### ISSUE TITLE
LinkedIn - Get profile improve function

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#90]
Input:
LK credentials

Model:
Function : get_profile(public_id="url" or "public_identifier", urn="urn")

Output:
Dataframe with:

PROFILE_URN = Linkedin urn
PUBLIC_ID = Linkedin public id

FIRSTNAME : First name
LASTNAME : Last name
EMAIL : Email
FOLLOWERS : Number of followers
TWITER : Twitter account
BIRTHDATE_DAY : Day of birth in format DD
BIRTHDATE_MONTH : Month of birth in format MM
BIRTHDATE_YEAR : Year of birth in format YYYY
BIRTHDATE : Birthdate in format DD, MM - YYYY

ADDRESS : Address
COUNTRY : Country name
PHONE : Phone number
LANGUAGE

HEADLINE : Job description (headline)
SECTOR : Work industry
COMPANY :
COMPANY_1 :
COMPANY_2 :

**Comment by jravenel** [comment]
@FlorentLvr can we add : 

- SCHOOL
- AGE
?
