### ISSUE TITLE
Twitter - Share new Tweets from a Twitter list in Slack

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#902]

**Comment by kaushalkrishna2000** [comment]
Hello Can I take up on this Issue ?

**Comment by FlorentLvr** [comment]
> Hello Can I take up on this Issue ?

Sure! How would you structure your notebook regarding our IMO framework?

**Comment by kaushalkrishna2000** [comment]
Can you elaborate on IMO framework ?

**Comment by FlorentLvr** [comment]
> Can you elaborate on IMO framework ?

Sure, you can check our readme here: https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository- 

Basically, our goal is to make sure every notebook is build the same way to make it easier to understand.

In this issue, I would build the notebook as follow:
## Input
### Setup Variables
-> Twitter credentials

## Model
### Connect to Twitter
Make sure you can connect to your account

### Get list of tweets from Slack

### Create list of new tweets
Check if tweet already shared or not

## Output
### Share new tweets

**Comment by FlorentLvr** [comment]
@jravenel, can you elaborate a bit more on "from a Twitter list in Slack". I don't understand how we get the list of tweets. 
Maybe it will be more easy from GoogleSheets or a list directly in your notebook. Don't you think ?

**Comment by jravenel** [comment]
@FlorentLvr @kaushalkrishna2000 I dont remember this need using Slack. I feel it's better to concentrate on what you can do with Twitter API: send tweet, get list of tweets on a topic. We can close this and create new ones for next sprint. Ok ?

**Comment by kaushalkrishna2000** [comment]
Sure

**Comment by FlorentLvr** [comment]
@jravenel, I close this issue and we can talk about it in the next sprint!
