### ISSUE TITLE
Magento - Get sales data

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#92]
We can use this module https://pypi.org/project/python-magento/

Input, model, output to be defined.

**Comment by psahunitk** [comment]
@jravenel  I want to contribute on this.

**Comment by psahunitk** [comment]
@jravenel  Can you confirm?

**Comment by jravenel** [comment]
@psahunitk still interested in working on this?

**Comment by psahunitk** [comment]
@jravenel You can assign any other which noone has taken already.

**Comment by calok64** [comment]
@jravenel if this is on high priority u can assign to @psahunitk

**Comment by jravenel** [comment]
Hi guy @calok64 @psahunitk we will close this one as magento has premium to access their API.
