### ISSUE TITLE
Google Analytics - Get Slack Notificatons for new Goals on Google Analytics

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#940]

**Comment by srini047** [comment]
@FlorentLvr This seems to me a very interesting use-case and would like to work on it.

**Comment by FlorentLvr** [comment]
@srini047, i am not sure you have enough details to start working on it. Let me come back to you first!

**Comment by srini047** [comment]
> @srini047, i am not sure you have enough details to start working on it. Let me come back to you first!

Sure @FlorentLvr . Take your time
