### ISSUE TITLE
Fix Societe.com / Societe.ninja template and folder location

### ISSUE THREAD

**Issue by vlacomme** [jupyter-naas/awesome-notebooks#956]
Hi,

This script is no longer working with the latest HTML code of societe.ninja
https://github.com/jupyter-naas/awesome-notebooks/blob/master/Societe.com/Societe.com_Get_societe.ninja.ipynb

The return code is the footer of the HTML page 👍  
"Ce site est édité par l'association CYBERTRON.  Soutenez nos développeurs bénévoles en faisant un don."

(As a sidenote the example SIREN is invalid and this should be called Societe.ninja as societe.com is a competitor company)

Thanks!

**Comment by jravenel** [comment]
Good point @vlacomme thanks for bringing that up. 
Do you have a use case in mind so we can prioritize this fix?

**Comment by vlacomme** [comment]
@jravenel Societe.com & Societe.ninja can prove very useful to get useful data on French companies (address, manager, last legal documents...) and especially check that the company is still active.

**Comment by FlorentLvr** [comment]
> @jravenel Societe.com & Societe.ninja can prove very useful to get useful data on French companies (address, manager, last legal documents...) and especially check that the company is still active.

Hi @vlacomme ! 
Thank you for your feedback :pray:
Unfortunately, we can not debug this template because we can no longer access the data. It is blocked by the website. However, we can get some info displayed in company ninja by using the same sources:
- Company info using data.gouv
- Get the PDF "Avis de SIRENE"
- Get the PDF "Récapitulatif INPI"
Would it be things that could interested you ?

**Comment by FlorentLvr** [comment]
> > @jravenel Societe.com & Societe.ninja can prove very useful to get useful data on French companies (address, manager, last legal documents...) and especially check that the company is still active.
> 
> Hi @vlacomme ! Thank you for your feedback 🙏 Unfortunately, we can not debug this template because we can no longer access the data. It is blocked by the website. However, we can get some info displayed in company ninja by using the same sources:
> 
> * Company info using data.gouv (ex: https://entreprise.data.gouv.fr/api/sirene/v3/unites_legales/880612569)
> * Get the PDF "Avis de SIRENE"
> * Get the PDF "Récapitulatif INPI"
> 
> Would it be things that could interested you ?

Hi @vlacomme, 
Just checking in :)
Let me know if you could be interested on something above.

**Comment by vlacomme** [comment]
Hi @FlorentLvr , 
Sure, these are relevant ideas. The PDF export would be great. 
Thanks !

**Comment by FlorentLvr** [comment]
Hi @vlacomme !
Here are the templates related to your needs :
- Company info using data.gouv (ex: https://entreprise.data.gouv.fr/api/sirene/v3/unites_legales/880612569) : https://github.com/jupyter-naas/awesome-notebooks/blob/master/Data.gouv.fr/Data.gouv.fr_R%C3%A9cup%C3%A9ration_donn%C3%A9es_l%C3%A9gales_entreprise.ipynb
- Get the PDF "Avis de SIRENE" : https://github.com/jupyter-naas/awesome-notebooks/blob/master/Insee/Insee_Download_PDF_recap.ipynb
- Get the PDF "Récapitulatif INPI" : https://github.com/jupyter-naas/awesome-notebooks/blob/master/INPI/INPI_Download_PDF_recap.ipynb

You can try it on your naas by clicking on "Open in naas". 

Let me know if you have any question or feedbacks :)

**Comment by vlacomme** [comment]
Hi @FlorentLvr ,

Very useful. Thank you !
