### ISSUE TITLE
OpenStreetMap - Obtain geospatial data from the API 

### ISSUE THREAD

**Issue by pepyczech** [jupyter-naas/awesome-notebooks#962]
The Problem:
Working with incoplete geospatial or address data sets can be frustrating and a reliable method of data imputation would be really useful.

Solution:
Develop a notebook template that would allow look up complete address and/or geospatial data based on input of some address info or geospatial data, e.g.:

- Input - lat and long OR address search query (country, postcode OR country, city/city+street, etc.)
- Model - Use available public APIs, for example OpenStreetMap to obtain complete data set containing address and geopsatial data, where possible: lat, lon, altitude, country, city, street, building, etc
- Output - Pandas dataframe with complete location info

**Comment by FlorentLvr** [comment]
Done with Google Maps templates and geopy > https://github.com/jupyter-naas/awesome-notebooks/blob/master/Geopy/Geopy_Display_markers_on_map.ipynb
