### ISSUE TITLE
LinkedIn - Follow Number of Content Published

### ISSUE THREAD

**Issue by Valpiquard** [jupyter-naas/awesome-notebooks#968]
Wrong Chart Name 

The chart name generated by the scripts mentioned "Total content views" instead of "Total content published"

1. Go to LinkedIn - Follow Number of Content Published template 
2. Change : fig = create_linechart(df_trend, label="PUBLISHED_DATE", value="value_cum", title='Total Content Views')

Many thanks

**Comment by FlorentLvr** [comment]
@Valpiquard, it's done! TY for your feedback !
