### ISSUE TITLE
HubSpot - Get LinkedIn distance with contacts

### ISSUE THREAD

**Issue by Valpiquard** [jupyter-naas/awesome-notebooks#979]
Add to my HubSpot contact the distance I have with them on LinkedIn : 1st degree contact, 2nd degree.... In order to rate them and prioritize the actions I have to do

**Comment by ameygoes** [comment]
Hey do we have any progress on this? I want to take this up!

**Comment by FlorentLvr** [comment]
> Hey do we have any progress on this? I want to take this up!

Hey @ameygoes, you can get the distance by using this template: https://github.com/jupyter-naas/awesome-notebooks/blob/master/LinkedIn/LinkedIn_Get_network_from_profile.ipynb 🙏
