### ISSUE TITLE
Send in Blue - Get number of undelivered emails

### ISSUE THREAD

**Issue by Valpiquard** [jupyter-naas/awesome-notebooks#987]
The goal is to get the number of undelivered emails from campaign

**Comment by MinuraPunchihewa** [comment]
@Valpiquard I will take up this issue. I will look at working on the other sendinblue issues as well.

**Comment by MinuraPunchihewa** [comment]
@Valpiquard Is the pull request that I opened being reviewed? I already worked on this issue.
