### ISSUE TITLE
CI/CD - Make sure that a pull request is linked to an issue before merging.

### ISSUE THREAD

**Issue by Dr0p42** [jupyter-naas/awesome-notebooks#988]
The role of this issue is to add a new feature in the CI/CD logic. 

We would like to make sure that when a pull request is opened, an issue is linked to it. 

Why?

To follow everything that is being done in awesome-notebooks and make sure that we will be able to promote new developments.

**Comment by abrahamalen** [comment]
I can work on it @Dr0p42

**Comment by Dr0p42** [comment]
Awesome @abrahamalen, I assigned it to you. Let me know if you need help on this one ;)

**Comment by abrahamalen** [comment]
> Awesome @abrahamalen, I assigned it to you. Let me know if you need help on this one ;)

sure

**Comment by Dr0p42** [comment]
To do this one you should:
- Take a look at existing workflows in .github
- Create a new workflow to verify that the pull request have an issue attached. It could be done using some python code and PyGithub.

Then you will be able to open a pull request and test on your pull request that your code is working fine.

**Comment by Dr0p42** [comment]
> > Amazing to see you on this @abrahamalen ✌️
> 
> getting started slowly ✌️

Hello @abrahamalen, how are you doing in this one?

**Comment by Dr0p42** [comment]
👌 Ok @abrahamalen, ping me on Slack when you want 🚀.

**Comment by Dr0p42** [comment]
@abrahamalen can you push what you already did to be able to help you please? And also open a first pull request please
