### ISSUE TITLE
Oracle DB - Connect to API

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#99]
Info : https://datatofish.com/how-to-connect-python-to-an-oracle-database-using-cx_oracle/

TBD

**Comment by sou-joshi** [comment]
Would like to work on this @jravenel

**Comment by jravenel** [comment]
Hello @sou-joshi, awesome! Do you have an Oracle database available to test?
We are making a community call next Monday to discuss contributions. Please send me your email so I can add you ;)


FYI @FlorentLvr @Dr0p42

**Comment by SunnyChugh99** [comment]
Hi @jravenel, I can work on this issue if it's still open. Will need to check whether I can create a oracle database for testing.

**Comment by jravenel** [comment]
Hey @SunnyChugh99 I believe we were stuck as we don't have a oracle database for testing. We will need a company to sponsor this particular template. I would suggest to focus more on social media related templates like Twitter (we have a need on how to automate posts) or TikTok (get liked videos in a dataframe) this will help the community more I think 🙂
