### ISSUE TITLE
LinkedIn - Get the cookies automatically

### ISSUE THREAD

**Issue by Octonathan** [jupyter-naas/awesome-notebooks#995]
**Refresh my Linkedin cookies**
I'm frustrated with having to update my Linkedin cookies and especially having to search for them in my inspector.

**Describe the solution you'd like**
Automatically get my cookies : "li_at" and "JSESSIONID" with a button.

**Comment by Octonathan** [comment]
Additional details

Do the following process automatically: 
https://www.notion.so/LinkedIn-driver-Get-your-cookies-d20a8e7e508e42af8a5b52e33f3dba75

Process description:
When a button is pressed, the script will scrape the cookies ("li_at" and "JSESSIONID")

**Comment by FlorentLvr** [comment]
Hi @Octonathan ! TY for your feedbacks 🙏 . 
I put this issue in backlog. It is on our roadmap for the next weeks. 
We will come back to you to test it once it's done :)

**Comment by jravenel** [comment]
@Dr0p42 @FlorentLvr need to validate tests + code modification.

**Comment by Dr0p42** [comment]
I just published a new version of the extension to fix a "bug" where you had to log out and log back in Linkedin to have it working. Now as soon as you provide a naas token, it will send your Linkedin cookies.

Waiting for Google Extension approval. It should be quick

**Comment by FlorentLvr** [comment]
> I just published a new version of the extension to fix a "bug" where you had to log out and log back in Linkedin to have it working. Now as soon as you provide a naas token, it will send your Linkedin cookies.
> 
> Waiting for Google Extension approval. It should be quick

Amazing! Let me know when it's done! Can you create a video as well to show us the process? TY 🙏

**Comment by Dr0p42** [comment]
v1.2 is available for everyone 👏 https://chrome.google.com/webstore/detail/naas/cpkgfedlkfiknjpkmhcglmjiefnechpp?hl=fr&authuser=0

@FlorentLvr @jravenel

**Comment by jravenel** [comment]
I will test.
